### ISSUE TITLE
Use multiple selected values

### ISSUE THREAD

**Issue by chrisehlee** [brianvoe/slim-select#10]
How do i populate an array with only the selected values of a multiple select instance? I could'nt get the value i wanted using the <code>onchange:</code> object.

**Comment by brianvoe** [comment]
Can you give me some more info on what you are trying to do?

If you want to get the value(s) in the onchange callback the value key is the one to use.
```
{ 
"id": "56041290", 
"value": "value1", 
"text": "Value 1", 
"innerHTML": "Value 1", 
"selected": true, 
"disabled": false, 
"placeholder": null, 
"data": {} 
}
```

**Comment by brianvoe** [comment]
If you have a multi select and want to put together an array of values just loop through the array of objects and push to an array you want

``` javascript
let newArray = []
for (let i = 0; i < info.length; i++) {
    newArray.push(info[i].value)
}
```

**Comment by chrisehlee** [comment]
![screenshot 50](https://user-images.githubusercontent.com/12748310/30370686-3de51274-9870-11e7-86fd-ca04d6ffea6d.png)
Sorry i'm late..
In reference to the above screenshot, what i'm trying to achieve is that after selecting four distinct values. I would like submit them as an array while submitting the form.
I tried using the <code>onChange</code> method to cache the selected values (and i know i am wrong) but it repeats the method after every <code>onChange</code> method.
[Here](https://jsfiddle.net/amm9d5d3/3/) is a fiddle...hope it helps???

**Comment by brianvoe** [comment]
If im understanding you right, your issue is in the onchange function it keeps pushing to newArray and when you output the use of newArray it has duplicates? If thats the case you can just clear it first before looping through and pushing values to it.

Let me know if im understanding you right.

**Comment by chrisehlee** [comment]
Thank you so much... I just emptied the array as per your suggestion and its working as expecting.
Cheers.

**Comment by brianvoe** [comment]
Glad that worked for you!

More than welcome to get pull requests for any improvements anyone sees. The general idea was to keep this light and simple and i believe it has achieved that but i do find myself making minor improvements from time to time.

Thanks for using it and spread the word!
