### ISSUE TITLE
Slim select not working with case sensitive text

### ISSUE THREAD

**Issue by stanolacko** [brianvoe/slim-select#102]
On slimselectjs.com is example for select and multiselect. Both of them, when user types "best" autocomplete found option "Best".
But when user types "Best" autocomplete result is "No result"

**Comment by Shoplifter** [comment]
@brianvoe Fix would be in [config.ts line 100](https://github.com/brianvoe/slim-select/blob/master/src/slim-select/config.ts#L100). Change 
from `return opt.text.toLowerCase().indexOf(search) !== -1` 
to `return opt.text.toLowerCase().indexOf(search..toLowerCase()) !== -1`

Previously `search` has been lowerCased before it was used as a parameter for `searchFilter`. This seems to have changed (a good thing imho) but the default searchFilter should be adapted to the change to remain case insensitive.

@stanolacko 
as a workaround until this is fixed, you may consider using the `searchFilter` option like this:
````
{
    select: your_select_element,
    ... other options ...,
    searchFilter: function(opt, search) {
        return opt.text.toLowerCase().indexOf(search..toLowerCase()) !== -1
    }
}
````

**Comment by brianvoe** [comment]
I agree with what you guys are saying. i have a couple of other minor updates to do today, but ill be sure to get this in sometime today. 

Thanks for catching this!

**Comment by stanolacko** [comment]
Thanks for given example. I fixed it alone on my way (but similar)
I made this issue to change it in way of maintainer ;-)

**Comment by brianvoe** [comment]
Fixed and updated. v1.18.11
