### ISSUE TITLE
HTML Select "size" Attribute Does Not Work

### ISSUE THREAD

**Issue by wbraswell** [brianvoe/slim-select#104]
I am trying to set the "size" attribute, it renders correctly with normal select lists but it appears to be ignored by Slim Select.
https://www.w3schools.com/tags/att_select_size.asp

I have tried both static HTML and dynamic Javascript, neither works.

Static:
```
<select id="my_select" multiple size="2">
    <option value="value 1">Value 1</option>
...
</select>
```

Dynamic:
```
var my_select_object = document.getElementById('my_select');
my_select_object.size = my_select_object.length;
```

Ultimately, I need to be able to dynamically set the Slim Select to any sze via Javascript.

Can you please help me figure out how to do this?  Thanks in advance!  :-)

**Comment by brianvoe** [comment]
you can easily set the height of the list area. .ss-list

**Comment by wbraswell** [comment]
@brianvoe
Okay great!  I am looking in the documentation and searching google, but I don't see anything about how to set the "ss-list" component.  Can you please give me a simple example?  Thank you!

**Comment by brianvoe** [comment]
all your doing is styling the class 

.ss-list {
    height: 555555px;
}

**Comment by wbraswell** [comment]
@brianvoe 
Okay yes I can shrink the list height using the ".ss-list" class, however I can not **grow** the list beyond 200px.

In other words, the most I can see in any list is the "Search" bar plus 7 options, and if I have more than 7 options then it forces me to have a scrollbar which is not good.

Why can't the list grow beyond "height: 200px;" ?

**Comment by wbraswell** [comment]
@brianvoe 
The dropdown can not grow beyond 200px in height, can you please help?

**Comment by brianvoe** [comment]
![screenshot from 2019-03-02 13-11-46](https://user-images.githubusercontent.com/1580910/53686496-5f949700-3ced-11e9-9ee1-867b854799fb.png)

**Comment by brianvoe** [comment]
max-height: 666px !important;
