### ISSUE TITLE
valuesUseText option uses innerHTML.text instead of text attribute

### ISSUE THREAD

**Issue by Karel-Kroeze** [brianvoe/slim-select#105]
I'm running into an issue similar to #48 and #25, in that I want to display additional content on the options in the dropdown, but only the option label itself in the selected field.

In #25 the `valuesUseText` option was added, but that seems to use `innerHTML.text`, not the `text` attribute of the options. E.g. `{ innerHTML: "<b>Label</b><span class='details'>detailed info</span>", text: "Label" }` will be displayed as `Label detailed info`, and not `Label`.

A workaround is suggested in #48, using styles to hide the details in the selected field. While that will work, it feels rather clumsy. In addition, the documentation isn't exactly clear on this behaviour of the `valuesUseText` flag.

**Comment by Karel-Kroeze** [comment]
on some further reflection, it appears that if `text` and `innerHTML` are both supplied, the supplied `text` is overwritten by `innerHTML.text`. This should probably not be happening?

**Comment by brianvoe** [comment]
I think im going to stick with my previous answer. This is such a fringe case scenario that i can't justify clustering slim select with additional options that only a significantly small portion of people will actually use. Plus this really isnt that much to implement.

{innerHTML: 'Will show <span class="hideInSelection">wiil not show</span>'}
.placeholder .hideInSelection { display: none; }

**Comment by Karel-Kroeze** [comment]
Given the number of created issues, I would argue it's actually a relatively common use case. 

That said, can you explain the rationale for overwriting the `text` attribute of options by `innerHTML.text`? It would be much more logical for the `valuesUseText` option if this behaviour was not there. It would be much easier (and intuitive) to pass a sanitized string to `text`, rather than use css workarounds so that `innerHTML.text` produces the desired content.

**Comment by brianvoe** [comment]
Im open to pr's if its something you want prove via example.
