### ISSUE TITLE
Feature Request: afterChange event

### ISSUE THREAD

**Issue by rasmusgadensgaard** [brianvoe/slim-select#107]
I'm trying to change the class of the option which is selected. When I do that in the onChange event, it seems like the dropdown is rendered again after the onChange, which resets my change. 

A basic example: 
 This changes nothing:
`onChange: (info) => {
    $("div.ss-option").removeClass();
}`

If there were an event which is fired when slimselect is done rendering like: afterChange(info), I think I would be able to achieve it.

**Comment by brianvoe** [comment]
Slim select is going to render when it needs to. So altering slim select classes isnt a reliable way of making changes you want. 

I would need to know more about what you are trying to accomplish.
