### ISSUE TITLE
Feature Request: Selectable optgroups

### ISSUE THREAD

**Issue by ArneVanham** [brianvoe/slim-select#108]
Hi,

I really like the slimselect tool, but I run into performance issues when I want to use it with several hundreds or thousands of options. Also, the load times are getting very long when you click on optgroups with a lot of options linked to it.

Hence, I'd like to propose two features:

1. Show the optgroup tag, instead of showing the tags of all the underlying options. 
2. Call ajax when scrolling down so you can load the data on the fly rather than having to load everything at once. (I am already using the search ajax functionality, but this has a downside that you cannot visualize all the option)

Would it be possible to implement those two features?

Regards,
Arne

**Comment by brianvoe** [comment]
Hey Arne,

I totally hear you on this issue. I have really wanted to do some serious refactoring to optimize for performance and optimal render function call. That being said there are a handful of things that need to be updated before i can even consider trying to tackle your requests.

Ill try to keep it on the list of things to do.
Thanks.
