### ISSUE TITLE
Use other properties for data than value and text

### ISSUE THREAD

**Issue by carestad** [brianvoe/slim-select#109]
Is this possible to customise somehow?

Like, if my data source is an external one, I won't have much control of how the data is structured. It will usually be arrays of objects, but the keys might differ, and would probably more oftenly be `id` and `text` instead of `value` and `text`, for instance.

Currently I'm using Mobiscroll and their select, which allows for setting [`dataText`](https://docs.mobiscroll.com/javascript/select#opt-dataText) and [`dataValue`](https://docs.mobiscroll.com/javascript/select#opt-dataValuehttps://docs.mobiscroll.com/javascript/select#opt-dataValue) parameters, that just re-defines which keys the component should use, but I want to try out your component here instead. Just kind of hoping I don't have to re-map data all the time :crossed_fingers: 

Is something like this possible today, or could it be considered?

**Comment by brianvoe** [comment]
Im not sure if i fully understand but in regards to slim select the ajax function is basically a callback function. so you can do whatever fetch you want and once you receive your results from the server you would create an array of objects that you would send back to the callback function.

Hope this helps.
