### ISSUE TITLE
onChange returns alphabetically sorted values

### ISSUE THREAD

**Issue by numb92** [brianvoe/slim-select#11]
The onChange method returns alphabetically sorted values. Shouldn't it return the values in the same order as displayed?

**Comment by brianvoe** [comment]
So after looking at this in more detail i didnt implement any type of alphabetical sorting. What essentially is happening is based upon how its selecting may append to the end of the list or set the value of the original select and rebuild the select value in the order of the select options.

**Comment by brianvoe** [comment]
In any case I didnt see a value to make any adjustments to this issue.

**Comment by numb92** [comment]
I get your point in that this is not related to alphabetically sorting, my bad.

The issue is that the onChange, and I guess also the other events returns the selected values in the original order of the <option> tags, not in the order in which they where selected. 

This results in an inconsistent application when you use slimselectjs to build a page dynamically based on the selections, because the slimselectjs dropdown will display selected options in the order in which they were selected, while the events will return the original order.

**Comment by brianvoe** [comment]
I see your point. Ok so what I'm going to do to keep consistency is derive the visual selection and the output of selected values based upon the original order of the list. This should help your situation.

I'll let you know when this is done.

**Comment by brianvoe** [comment]
Ok v1.2.0. I updated the code make the multiselect value display in the same order as the original select. I also made sure the onchange values returning back are also in the order of the original select.

Thanks for submitting this issue!
