### ISSUE TITLE
showSearch: false prevents accessing first option

### ISSUE THREAD

**Issue by kgifford** [brianvoe/slim-select#112]
Creating SlimSelect with showSearch: false

A div with classes "ss-search ss-hide" is created on top of the first option element in the list making it impossible to select this first option

My temp solution is $(".ss-search").remove();

**Comment by brianvoe** [comment]
Sorry i dont think i completely follow your issue

**Comment by kgifford** [comment]
I want to disable search because I only have 8 options. 

On multi-select the "showSearch: false" option does not fully work

It hides the search box but leaves it on top of the first item in the list - meaning you can not select that first option.

**Comment by brianvoe** [comment]
ok i understand. let me take a look and see if i can get that resolved for you.

Thanks.

**Comment by brianvoe** [comment]
I updated the docs and added multi dropdown examples for the search section and didnt see any issues that you pointed out. you can take a look at the updated docs to see that it works as it should. I would look at your own code and see if there is anything that is interfering that would cause the issue you see in your own application.

**Comment by kgifford** [comment]
The conflict is a css library 
Here is a demonstration of the issue: https://jsfiddle.net/fd8w95um/

**Comment by brianvoe** [comment]
ya uptown.css:1495 is setting a min-height: 2.4rem;
