### ISSUE TITLE
Feature Request / Does it already exist?

### ISSUE THREAD

**Issue by CharlesLindberghMcGill** [brianvoe/slim-select#113]
Hey there,

I don't know if you take feature requests. Is it possible to re-order selected items? It's pretty important in an application I'm developing and it 'd be really handy to have it just be an option within slim-select.

Regards,
 - Chuck

**Comment by brianvoe** [comment]
Thanks for your submission. Its not currently something that exists. If you want to submit a pr I would be more than happy to take a look at it.
