### ISSUE TITLE
selectedIndex read from options and not from element

### ISSUE THREAD

**Issue by shillem** [brianvoe/slim-select#114]
I was testing your project but the object creation was throwing an error. I identified the problem and I am kind of surprised to notice that selectedIndex property is read in `this.main.select.element.options` instead of being read in `this.main.select.element`.

https://github.com/brianvoe/slim-select/blob/c9629db87d7ac02e2b45d7b6bfe92d41bc77bc52/src/slim-select/data.ts#L145

I changed the code to the following in order for your project to work:

```
var element = this.main.select.element;
if (element.selectedIndex !== -1) {
    var option = element.options[element.selectedIndex];
    var value = option.value;
    this.setSelected(value, 'value');
}
```

**Comment by brianvoe** [comment]
If you submit a pr i can get that in.

**Comment by brianvoe** [comment]
did a push live a moment ago. v1.19.0

Thanks again for catching that and for the pr.
