### ISSUE TITLE
Style of selected item

### ISSUE THREAD

**Issue by andp97** [brianvoe/slim-select#115]
Change the style of selected items. Not display this option like a disabled item.

**Comment by brianvoe** [comment]
I would be up for adding that. It would get in quicker if you did it and submitted a pr for it.

**Comment by brianvoe** [comment]
Added .ss-option-selected v1.19.0

**Comment by Acidic9** [comment]
@brianvoe For some reason every single one of my select options have the class `.ss-option-selected`.
Is this a bug?
