### ISSUE TITLE
How to get array of selected text and values for multi selects?

### ISSUE THREAD

**Issue by patel33hardik** [brianvoe/slim-select#118]
Hi, I am using slim-select for multiple selections,
can anyone suggest me how to get an array of selected values and texts?
i.e 
 selected_buttons = new SlimSelect({
            select: '#SelectQButton',
            placeholder: 'Select Buttons',
            closeOnSelect: false
        });
is that any function like selected_buttons.selected('text') ??
I want an array of selected values as well selected text.
It would be like this:
text_array = selected_buttons.selected('text')
value_array = selected_buttons.selected()

**Comment by brianvoe** [comment]
You can use the onChange callback and loop through selected values and pull out any values you want to maintain your own array of items you would like to use.

**Comment by patel33hardik** [comment]
All good and thanks, I got that using jquery 
However, you should enable such a feature to get a text.
text_array = selected_buttons.selected('text')

var select_button_text = $('#SelectQButton option:selected')
                .toArray().map(item => item.text);
Output: ["text1", "text2"]

var select_button_text = $('#SelectQButton option:selected')
                .toArray().map(item => item.value);
Output: ["value1", "value2"]

If you use .join()

var select_button_text = $('#SelectQButton option:selected')
                .toArray().map(item => item.text).join();
Output: text1,text2,text3
