### ISSUE TITLE
Addable

### ISSUE THREAD

**Issue by pywebdesign** [brianvoe/slim-select#12]
Hi,

so I worked on adding an "add" option function on slim-select.

When a user search for something and press enter it is added as-entered. 

I have made a lot of progress but being unfamiliar with typeScript I am unable to finish. When adding many elements they sometimes appear doubled.

If this options interest you I would love to ask for help on my implementation.

to test simply build and run addable.html

```
...

var slim = new SlimSelect({
        select: '.select-multiple',
        addable: true
      })

...
```

Please refer yourself to the additional commit on my fork

https://github.com/pywebdesign/slim-select/commit/ffc3ddd8cb96c6566b66ff3f6861ca7734b0af7d

Thank you for this amazing tool

**Comment by brianvoe** [comment]
Thanks for the feedback. If you could make a pull request i can take a look at it.

**Comment by pywebdesign** [comment]
Done. You send me on a quest to learn TypeScript. It is amazing. Thanks @brianvoe

**Comment by brianvoe** [comment]
Thanks for the pr. I have been trying to figure out how to get this properly integrated. Im not against the idea but i would like to get some background on the use case you need it for. This isnt normally something you see in a select dropdown, so if you could point me at one that might possibly do something similar to this.

Ill try to figure out how to get this in just need some more convincing first.

Thanks!

**Comment by pywebdesign** [comment]
I find it very useful for a drop-down for cities for examples. 

You provide all major cities and the user can also define a city you did not think of.

I will be using it on a website where people will be able to describe some objects with types and define new type on the fly.

Thanks!

**Comment by brianvoe** [comment]
Ok. Give me some time and ill work this in. Thanks.

**Comment by pywebdesign** [comment]
see the PR

**Comment by brianvoe** [comment]
Just a heads up i built this out. take a look and let me know what you think
