### ISSUE TITLE
Method Selected() returns wrong Id

### ISSUE THREAD

**Issue by igloar96** [brianvoe/slim-select#120]
My data is : { value: obj.id , text: obj.nombre }
[{"id":0,"nombre":"A-0605201901","ubicacion":"Buenos Aires test "},{"id":5,"nombre":"A-05052019541021","ubicacion":"san juan"},{"id":6,"nombre":"A-0505201951-TDF","ubicacion":"Tierra del Fuego - 1"}]

When i uses the .selected() method, the first id that i have is wrong.
![image](https://user-images.githubusercontent.com/43254184/57262446-64a1f980-7042-11e9-9d48-e549627a1e9c.png)

**Comment by igloar96** [comment]
thats happens when the id is a number

**Comment by brianvoe** [comment]
I would have to see more code to rule this as an issue
