### ISSUE TITLE
Drop down doesn't collapse when tabbing quickly between controls.

### ISSUE THREAD

**Issue by knowankit** [brianvoe/slim-select#122]
When I hit tab quickly then drop down doesn't collapse. However if I hit tab slowly then it works fine. You can also check this issue on your website http://slimselectjs.com/.

Result image of hitting tab slowly
![image](https://user-images.githubusercontent.com/44323532/57905801-67e48300-7895-11e9-9475-671f7db922f0.png)

Result image of hitting tab quickly
![image](https://user-images.githubusercontent.com/44323532/57905823-79c62600-7895-11e9-8387-a492d3252b12.png)

**Comment by AngeloStavrow** [comment]
You can see a particularly egregious example of this if you tab quickly through the select fields in this project:

https://2019-stackoverflow-public-data.glitch.me/

Source code here:

https://glitch.com/edit/#!/2019-stackoverflow-public-data?path=index.html:1:0

**Comment by knowankit** [comment]
@AngeloStavrow I have fixed the code and very soon I will be creating a PR for this.

**Comment by brianvoe** [comment]
Sorry for the delay ill get this fixed or merge in your pr tomorrow

**Comment by brianvoe** [comment]
I was able to fix this without needing to change the timeoutDelay. but i left the pr in, in the case somone wanted to change the slide in/out animation timing. v1.21.0
