### ISSUE TITLE
SlimSelect not syncing with original select

### ISSUE THREAD

**Issue by Acidic9** [brianvoe/slim-select#126]
In my JavaScript, I'm updating the original select to disable some options. Tested with both `optionEl.disabled = true` and `optionEl.setAttribute('disabled', 'true')`.

If I inspect elements, I can see my original select indeed changes but SlimSelect does not pick this up.

Is there something I'm doing wrong or is this a bug? I thought the default behaviour of SlimSelect was to watch the original select and update the SlimSelect input to match the updates.

**Comment by Acidic9** [comment]
https://codesandbox.io/s/runtime-dawn-xmnu1?fontsize=14

Here is an example showing the issue.
On change I am disabling the `XYZ` option, but SlimSelect doesn't pick it up.

**Comment by brianvoe** [comment]
Slim select uses a mutation observer for any select changes. The only thing that pops in my head regarding your issue is there are specific time when i disable the observer that caused infinite loops and i think on change is one of them. https://github.com/brianvoe/slim-select/blob/master/src/slim-select/select.ts#L53

Try disabling it not in the onchange callback.

**Comment by Acidic9** [comment]
Still not working. I removed it completely from the onChange event and just used a setTimeout below the initialisation of SlimSelect, but still doesn't work.

**Comment by brianvoe** [comment]
bummer. I would need some time to look into it and see what things mutation observer does and doesnt trigger properly with. I would say if you need this to work. you can use the setData method and not directly alter the select and use slim select functionality.

**Comment by Acidic9** [comment]
Thanks heaps for the help - I just manually disabled the option by adding the disabled class to it and adding `pointer-events: none` to the disabled class.

**Comment by brianvoe** [comment]
So that wont actually disable it. but if it works for you then so be it. Sorry i couldnt be more help. sometimes javascript doesnt give you the most simple things to deal with.

**Comment by Shoplifter** [comment]
I also needed this feature and tried to work around the issue by dis/enbaling options in the original select, then destroying and re-initializing SlimSelect. That works fine in all browsers but IE11. IE11 takes over the `style="display:none;"` from the original select. Should that be removed when destroying SlimSelect or not taken over with re-initializing?
