### ISSUE TITLE
Ability to deselect values in dropdown

### ISSUE THREAD

**Issue by evromalarkey** [brianvoe/slim-select#127]
Curently if you select a value, `ss-disabled` class is added. It would be great to have an option to disable this, so if you select multiple values, you can also deselect them in the dropdown.

**Comment by brianvoe** [comment]
Thanks for reaching out. In regards to ss-disabled in your situation if you want it styled differently i would suggest just making css changes you want as an override. 

In regards to a deselection button on the option. Im not against this as an option if you want to submit a pr for it. But this hasnt been a very highly requested feature that many people would use. So if you want this feature in i would ask you to add it and ill check the pr and get it in.

Thanks

**Comment by evromalarkey** [comment]
CSS change wouldn't work for me in this case, I want to use the multiple select with custom styled selected values (without tags). I've done this via CSS, but I can't deselect the values now.

![obrazek](https://user-images.githubusercontent.com/6872956/58579469-6fb80600-824b-11e9-95e9-b20abdf8abf7.png)

Option to enable deselection of values in dropdown (clicking on the selected value) would solve this for me. I'm not good in TypeScript, but I can take a look if I've could do it and send pr.

**Comment by brianvoe** [comment]
v1.22.0
