### ISSUE TITLE
slim-select with ajax search autocomplete, duplicate items in dropdown list

### ISSUE THREAD

**Issue by viseth** [brianvoe/slim-select#129]
Hi, 

Thanks for the good work !
I'm using slim-select with ajax search autocomplete and came accross the following issue :

```
            slimSelectProbeAdd = new SlimSelect({
                select: '#probesAdd',
                searchingText: 'Searching...', // Optional - Will show during ajax request
                ajax: function (search, callback) {
                    // Check search value. If you dont like it callback(false) or callback('Message String')
                    if (search.length < 3) {
                        callback('Need 3 characters')
                        return
                    }

                    // Perform your own ajax request here
                    //fetch('https://jsonplaceholder.typicode.com/users')
                    fetch('http://localhost:9090/getProbes')
                    .then(function (response) {
                        return response.json()
                    })
                    .then(function (json) {
                        let data = []
                        for (let i = 0; i < json.length; i++) {
                            console.log(json[i].Name)
                            data.push({text: json[i].Name})
                        }

                        // Upon successful fetch send data to callback function.
                        // Be sure to send data back in the proper format.
                        // Refer to the method setData for examples of proper format.
                        callback(data)
                    })
                    .catch(function(error) {
                        // If any erros happened send false back through the callback
                        callback(false)
                    })
                }
            })

```

Once selected the item, I still have 2 occurences of it in the select dropdown list: one which is greyed out (which is Ok), but I still have another one which is not greyed out (in other words still selectable) (which is not OK).

![Capture1](https://user-images.githubusercontent.com/1708388/58791234-1efd3000-85f2-11e9-9e57-b70507aa3867.JPG)

How can I prevent this to happen ?

Thanks,

**Comment by brianvoe** [comment]
in your fetch response while looping through do an exclude of any data that is already in your selected values

**Comment by viseth** [comment]
@brianvoe thanks, I actually add a loop and exclude the item from the list and it works.
I was wondering how to pre-populate the slimselect form with existing value and at the same time keep the ajax feature dropdown ?

![image](https://user-images.githubusercontent.com/1708388/58974103-f035b400-87c1-11e9-9ad2-910573f49eb2.png)


![image](https://user-images.githubusercontent.com/1708388/58974063-d4321280-87c1-11e9-81df-0c09844b2983.png)


Thanks for any hints, and keep up the good work :-)

**Comment by brianvoe** [comment]
The setData method is you best use for setting your values whether or not you use the ajax method

**Comment by viseth** [comment]
@brianvoe thanks, do you have by any chance a small example on hand ?

**Comment by brianvoe** [comment]
http://slimselectjs.com

**Comment by viseth** [comment]
@brianvoe thanks, any chance to have a prepopulate option in slimSelect as with the jquery-tokeninput (http://loopj.com/jquery-tokeninput/) ?

            slimsel = new SlimSelect({
                select: selectId,
                allowDeselect: true,
                placeholder: selectId.options[0].text,
                data: getData(selectId),
		prepopulate: getPrePopulateData(),
		searchingText: 'Searching...'
				
            });
