### ISSUE TITLE
Feature request: Add an option to show native dropdown on mobile devices

### ISSUE THREAD

**Issue by valentin-** [brianvoe/slim-select#131]
Would be great if there is an option to keep the default select behaviour on mobile devices.

Just like https://codepen.io/Mobius1/pen/QgdpLN (first example)

Desktop: Use styled dropdown list
Mobile agent: Show native device dropdown list

Cheers

**Comment by brianvoe** [comment]
Im open to any solutions to this. Havent come across a great plan of action that didnt require me to make major changes in functionality
