### ISSUE TITLE
Placeholder make text-overflow: ellipsis work again.

### ISSUE THREAD

**Issue by IrvingArmenta-ML** [brianvoe/slim-select#132]
I think the base CSS should be changed, since having `display: flex` on an element with `text-overflow: ellipsis` does not work as expected.

I'm talking about this: 
```
.ss-main .ss-single-selected .placeholder {
  display: flex;
  flex: 1 1 100%;
  align-items: center;
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
  text-align: left;
  width: calc(100% - 30px);
  line-height: 1em;
  -webkit-user-select: none;
  -moz-user-select: none;
  -ms-user-select: none;
  user-select: none;
}
```
I removed `display: flex` and `flex: 1 1 100%` in order to make it work as expected, I also had to add a `line-height` so it could be centered vertically. 

This codepen has some work arounds for using `display: flex` with `text-overflow` 
https://codepen.io/chriscoyier/pen/zqedEr

**Comment by brianvoe** [comment]
Unfortunately that would bring up other issues. But ill look into getting the ellipsis working again.

**Comment by nwe199** [comment]
Help me my date

**Comment by brianvoe** [comment]
Im open to a pr fix if you want to merge in a fix
