### ISSUE TITLE
An invalid form control with name='' is not focusable.

### ISSUE THREAD

**Issue by badpenguin** [brianvoe/slim-select#133]
When i had the required attribute to a select the browser is unable to display native validation message and in the chrome console i get:
```An invalid form control with name='...' is not focusable.```
Any idea how to fix this?

**Comment by brianvoe** [comment]
Slim select currently doesnt adheard or deal with anything in regards to required attributes on the original select. Im open any pr's if you would like to add that functionality.

**Comment by Mellis84** [comment]
My solution for adding a focus state to slim select is using the above solution with this little bit of added css.

```
select[required] {
  display: block !important;
  position: absolute;
  clip: rect(0, 0, 0, 0);
  pointer-events: none;

  &:focus {
    + .ss-main .ss-single-selected {
      border-color: aqua;
    }
  }
}```

Hope this helps anyone.

**Comment by columbian-chris** [comment]
> My solution for adding a focus state to slim select is using the above solution with this little bit of added css.
> 
> ```
> select[required] {
>   display: block !important;
>   position: absolute;
>   clip: rect(0, 0, 0, 0);
>   pointer-events: none;
> 
>   &:focus {
>     + .ss-main .ss-single-selected {
>       border-color: aqua;
>     }
>   }
> }
> ```

This addition didn't work for me. 🙁

**Comment by koen-at-peppered** [comment]
@brianvoe this should be re-opened. Currently slim-select doesn't behave properly and throws errors on simple native form validation (e.g. required fields).

**Comment by brianvoe** [comment]
Submit a pr

**Comment by jasomdotnet** [comment]
> @brianvoe this should be re-opened. Currently slim-select doesn't behave properly and throws errors on simple native form validation (e.g. required fields).

Same problem here. I tought that library with 30K week download will have this basic solved. 

[TomSelect](https://github.com/orchidjs/tom-select) solved required form validation but has ugly design (not clear it's a select field + blinking text cursor + twice so big).

**Comment by jasomdotnet** [comment]
> > My solution for adding a focus state to slim select is using the above solution with this little bit of added css.
> > ```
> > select[required] {
> >   display: block !important;
> >   position: absolute;
> >   clip: rect(0, 0, 0, 0);
> >   pointer-events: none;
> > 
> >   &:focus {
> >     + .ss-main .ss-single-selected {
> >       border-color: aqua;
> >     }
> >   }
> > }
> > ```
> 
> This addition didn't work for me. 🙁

```
    select[required] {
        display: block !important;
        position: absolute;
        clip: rect(0, 0, 0, 0);
        pointer-events: none;
    }
    select[required]:focus + .ss-main  {
        border-color: aqua;
    }
```
