### ISSUE TITLE
Feature request: prepopulate option

### ISSUE THREAD

**Issue by viseth** [brianvoe/slim-select#134]
Thanks for the amazing work, it would be nice to have a prepopulate option in slimSelect as with the jquery-tokeninput (http://loopj.com/jquery-tokeninput/) ? Is something that would make sense ?

            slimsel = new SlimSelect({
                select: selectId,
                allowDeselect: true,
                placeholder: selectId.options[0].text,
                data: getData(selectId),
		prepopulate: getPrePopulateData(),
		searchingText: 'Searching...'
				
            });

**Comment by brianvoe** [comment]
Thanks for the kind words. Im not sure i fully understand what your request it.

**Comment by viseth** [comment]
@brianvoe, here' some screenshots:

![edit](https://user-images.githubusercontent.com/1708388/59446605-1bdc1e00-8e02-11e9-9ad4-df1a3a817c7b.png)

then the edit windows appears

![edit2](https://user-images.githubusercontent.com/1708388/59446624-272f4980-8e02-11e9-84ae-e1be1129e345.png)


the idea wold be to have 


        slimsel = new SlimSelect({
            select: selectId,
            allowDeselect: true,
            placeholder: selectId.options[0].text,
	    prepopulate: getPrePopulateData(),
	    searchingText: 'Searching...'
           ajax: function (search, callback) {
					if (search.length < 3) {
						callback('Need 3 characters')
						return
					}
					// Perform your own ajax request here
					//fetch('https://jsonplaceholder.typicode.com/users')
					fetch('http://localhost:9090/keysOnly')
					.then(function (response) {	
						return response.json()
					})
					.then(function (json) {
						let data = []
						for (let i = 0; i < json.length; i++) {
							data.push(json[i].Name)
						}
						callback(data)
					})
					.catch(function(error) {
						// If any erros happened send false back through the callback
						callback(false)
					})
				}
	
        });


getPrePopulateData() {
//ajax function that returns a json array [{"text":"value1'},{"text":"value2}"]

}

Does it make sense that prepopulate feature ?

**Comment by brianvoe** [comment]
If your referring to prepopulate with selected data. then you can use either data: [{text: 'thing', selected: true}] or the method setData
