### ISSUE TITLE
List content chopped off when wrapped in div with no overflow

### ISSUE THREAD

**Issue by osuwariboy** [brianvoe/slim-select#136]
Basically, to reproduce the bug, I used the codepen below:

https://codepen.io/jelenaherceg/pen/wpqdwq

All you have to do is wrap your list inside a div with no overflow and you won't see anything appear even though the list's actually open.

`<div style="overflow:hidden"></div>`

This is because the list's options (or more specifically, the visual elements replacing the list's options) are put right next to the list, making them part of the same stacking context. This causes the items to become "trapped" in their container instead of floating above the page, thus causing this sort of strange behavior. So far, the only way I can think of to prevent this is to put the visual elements at the root of the DOM, thus enabling them to appear above everything else on the page.

**Comment by brianvoe** [comment]
Im a aware of the "issue". But adjusting your own css containers would easily fix slim select being cut off.
