### ISSUE TITLE
input select field flickering and ajax call being called multiple times

### ISSUE THREAD

**Issue by viseth** [brianvoe/slim-select#137]
I'm seeing the fllowing behaviour while implementing slimselect with ajax: the input multiple select field is flickering as many time as the ajax are being called. Here's some screenshots :

![downtime1](https://user-images.githubusercontent.com/1708388/59564247-b0ce5980-9044-11e9-9d35-2bc5a9527568.png)

![downtime2](https://user-images.githubusercontent.com/1708388/59564250-b4fa7700-9044-11e9-9feb-581da6566407.png)

![downtime3](https://user-images.githubusercontent.com/1708388/59564251-ba57c180-9044-11e9-8d61-e6f38cf4906c.png)

Am I missing something. Why do the ajax call is being called multiple times and not one time only ?
Anyway thanks for the good work !

**Comment by brianvoe** [comment]
Thanks for the kind words!

I was able to recreate what your talking about. Ive wanted to rework this function but worry about breaking backwards capabilities. I actually wanted to just get it integrated into the search method considering its just a glorified callback method, cause you do all your fetching on your own.

I dont know if you have a deadline but ill try to see if i can try to work on this in the next few weeks.

Sorry

**Comment by viseth** [comment]
Next week would be great as I am using slimSelect elsewhere in my projet.
Keep it up :-)

**Comment by viseth** [comment]
@brianvoe , did you have time to correct this issue ?

**Comment by brianvoe** [comment]
I have looked into this. i have a running development of changes im doing this is in there

**Comment by brianvoe** [comment]
I attempted to put some time into this. I wasnt able to come up with a solution at this time. I did a release today with a list of other updates. Im not giving up on this, I just wanted to keep you updated on where I am with this. Sorry.

**Comment by viseth** [comment]
@brianvoe ok no problem. watching anyway your progress on it.
Thanks,

**Comment by viseth** [comment]
@brianvoe any news on this issue ?
Thanks,

**Comment by viseth** [comment]
@brianvoe any progress, please?
Thanks,

**Comment by brianvoe** [comment]
Ill take a look at it tomorrow and see what i can do.

**Comment by viseth** [comment]
@brianvoe any update?
Thanks

**Comment by brianvoe** [comment]
I did take a look at it. Made some headway, going to put some more work into it today

**Comment by viseth** [comment]
@brianvoe Thanks, appreciate your effort and work!

**Comment by viseth** [comment]
@brianvoe any progress on this issue since you made some headway.

**Comment by viseth** [comment]
@brianvoe did you think you can sort out that flickering issue or should I just find another library ?  Well rather stick with ours but I need this flickering issue to be solve for my project.
Thanks

**Comment by viseth** [comment]
@brianvoe, any news on this issue ? Thanks,

**Comment by brianvoe** [comment]
Im aware of the issue. I have some work into redoing a good portion of that part. I havent had too much time to work on it but its in the queue

**Comment by viseth** [comment]
@brianvoe, please any progress on this issue. The fact that it is being called multiple times makes the auto completion very slow. Thanks

**Comment by viseth** [comment]
@brianvoe, any news or should I start searching for an alternative for slimselect ?
Thanks

**Comment by brianvoe** [comment]
I have a running branch for reworking major parts of the render "engine" but it becomes a domino effect of tackling a bunch of other things and possibly a new major release. I have a possible simple solution with using debouncing that im trying out currently that hopefully solves this issue

**Comment by viseth** [comment]
@brianvoe does the workaround with debouncing worked ?

**Comment by Papaya-web-solution** [comment]
Hello and thank you for your work. It's very good and nice.
But unfortunately I have the same problem as viseth.
If you have a solution, even temporary, I'm interested, because I use big data

Thanks a lot and good luck
Marco

**Comment by brianvoe** [comment]
New version of slim select has been released. If this is still an issue let me know and ill try to take care of it.
