### ISSUE TITLE
avoid dropdown from closing after select an option (for multi-select)

### ISSUE THREAD

**Issue by syamsoul** [brianvoe/slim-select#139]
Hi..

Based on the title, how to prevent the dropdown menu from closing after select an option (for multi-select)...

currently (for example) in a multi-select element, got 3 option...if i want to select 2 option...i must click and open the dropdown, select 1st option..and then the dropdown will close...and i must click and open the dropdown again, then select 2nd option...

you see what's the problem there?

it would be nice if after i select the 1st option, the dropdown will never close, and straightaway i can choose the 2nd option..

how to do that?

**Comment by syamsoul** [comment]
i am very sorry...there should not be an issue...

just use `closeOnSelect: false`

**Comment by brianvoe** [comment]
haha no problem. Hope you enjoy using it. If you like it give it a star
