### ISSUE TITLE
IE 11 error - Object doesn't support this action

### ISSUE THREAD

**Issue by fi5u** [brianvoe/slim-select#14]
When opening http://slimselectjs.com in IE11, and changing the dropdown, an error shows:

```
Object doesn't support this action
```

This is referring to [this line](https://github.com/brianvoe/slim-select/blob/master/src/slim-select/select.ts#L46)

```
this.element.dispatchEvent(new Event('change'))
```

There is a possible fix on SO [here](https://stackoverflow.com/a/32889608/997596).

**Comment by brianvoe** [comment]
Ok this should be an easy fix. Ill get this fix shortly

**Comment by brianvoe** [comment]
I made updates to fix ie issues. v1.3.2

**Comment by fi5u** [comment]
Thanks for the quick fix!

**Comment by brianvoe** [comment]
No problem. Let me know how its been working for you so far and if you need anything else. Really trying to see how much i can replace chosenjs and select2.

Any insight you can give me on why you choose mine would help to so i could push that a little harder as well

**Comment by fi5u** [comment]
The main requirements for us were that it has a simple API and no dependency. It was actually quite hard to find a decent dropdown without a jQuery/React dependency. Great work!

**Comment by brianvoe** [comment]
Thats what i was going for. Thanks!
