### ISSUE TITLE
Testing with Puppeteer

### ISSUE THREAD

**Issue by stanolacko** [brianvoe/slim-select#140]
I'm playing with automated testing with Puppeteer, but I'm not able to simulate user click slim select and choose value by press arrow down and enter.
Which commands of puppeteer (click, type, keyboard.press) use to simulate user type?

**Comment by brianvoe** [comment]
its the main container .ss-main

**Comment by stanolacko** [comment]
Sorry, main container not works. Even when you try something like $('.ss-main').click() or $('.ss-main').trigger('click') select is not opening.
Even the same in puppeteer..

**Comment by brianvoe** [comment]
https://github.com/brianvoe/slim-select/blob/master/src/slim-select/slim.ts#L125

**Comment by stanolacko** [comment]
Well I'm playnig with puppeteer and slim-select for couple of hours with no lack.
Did you try it?

**Comment by brianvoe** [comment]
I dont need to try it with puppeteer to know the click event is on the main container.

**Comment by stanolacko** [comment]
Maybe, when you'll test, youll be able to check, that it not works for puppeteer.
I really like your alternative to <select>, mainly for ajax  @requestest.
This is reason, why I want to integrate to tests (also with ajax requestes) to prevent some errors like was last one #102 
This can really help to find a way, how to integrate in puppeteer.
