### ISSUE TITLE
Wrong cursor on placeholder 

### ISSUE THREAD

**Issue by Benj4m1n55** [brianvoe/slim-select#145]
![idFfuFgXGK](https://user-images.githubusercontent.com/38720155/60160741-4a8cc800-97f6-11e9-8667-cf379d968169.gif)

I came across this litte issue. 

This was change in following commit: 
https://github.com/brianvoe/slim-select/blob/a1cedacf9577670b067aaf9700f28ff74825bcd1/src/slim-select/slimselect.scss#L71-L74

**Comment by brianvoe** [comment]
Thanks for pointing that out. ill try to get to this along with a few other things.

**Comment by brianvoe** [comment]
P.S. I just wanted to say THANK YOU for providing a gif showing the issue. I cant tell you how many people want me to guess how to replicate their issue. I think im going to require gifs before someone can submit an issue.

**Comment by Benj4m1n55** [comment]
> 
> 
> P.S. I just wanted to say THANK YOU for providing a gif showing the issue. I cant tell you how many people want me to guess how to replicate their issue. I think im going to require gifs before someone can submit an issue.

No problem! 
They are actually super easy to make one. I use [ShareX](https://github.com/ShareX/ShareX).
This one is a clone for Linux [Sharenix](https://github.com/Francesco149/sharenix).
