### ISSUE TITLE
Selectbox duplicated after validating form!

### ISSUE THREAD

**Issue by Fruchtgummi** [brianvoe/slim-select#147]
i use your script in forms. Whren I send the formular, start the ajax-call from other global-script and the back give the validation back.

before:

![image](https://user-images.githubusercontent.com/2059888/60249808-d4f02d00-98c5-11e9-9507-65f6177a83cb.png)

after ajax-call:

![image](https://user-images.githubusercontent.com/2059888/60249867-eb968400-98c5-11e9-9d49-dba0a821f682.png)

It seems like the old-selectbox with appears.

**Comment by brianvoe** [comment]
Looks more like a developer error when initiated slim select. Ive never once seen this happen.

**Comment by Fruchtgummi** [comment]
Really that's your answer?

With so much initiative, we prefer to throw this "tool" out of our race.

Thank you for your time!
