### ISSUE TITLE
IE11 remains hidden because of display:none

### ISSUE THREAD

**Issue by badpenguin** [brianvoe/slim-select#148]
Any idea where to look why .ss-main remains with "display:none" with IE11?
If i open the slimselectjs.com it works but on my self the select box remains hidden.
If by F12 i remove display:none from .ss-main then it works normally.
Probably some timeing/event conflict with other JS? I dunno where to look.

I've temporary mitigated the problem by adding:
```
.ss-main.slim-select {
	display: block !important;
}
```

**Comment by brianvoe** [comment]
Im not sure what your seeing. When i use browserstack on ie 11 everything seems to be fine with me.

<img width="1527" alt="Screen Shot 2019-06-27 at 10 56 35 AM" src="https://user-images.githubusercontent.com/1580910/60281311-58ac1880-98ca-11e9-8ff0-4a3520266e56.png">

**Comment by badpenguin** [comment]
I tested the old version to see where is start breaking.
Version 1.17 is the latest i got working. 
From 1.18 and futher its not working anymore.

**Comment by brianvoe** [comment]
I just sent you a screen shot of it working. Just saying it isnt working doesnt help me see the issue. What am i suppose to do with "its not working anymore"?

**Comment by badpenguin** [comment]
Same as the other tickets, will create a codepen. Cool down.

**Comment by brianvoe** [comment]
If you want people help you with your issue. Probably not a good idea to tell them to "cool down"

**Comment by badpenguin** [comment]
> If you want people help you with your issue. Probably not a good idea to tell them to "cool down"

sorry, wrong translation from native language, probably better "please wait a few hours"

**Comment by glaszig** [comment]
i'm having the same issue. inspecting the behavior on the slim-select website i see that the `setData()` example just leads to an updated container div (`ss-main`). when i use `selectElement.slim.setData(newData)` in my application, it recreates the entire container div, gives it a new `ssid` and in that way also copies the `display:none;` property from the select tag.
on top of that, id do experiance the same behavior in safari but there _it does not copy the style from the select tag_.

i cruised around in the slim-select code and found that in the `Config()` constructor, on IE11, `info.select.style.cssText` is `display:none;` but on safari (and other modern browsers) it's empty.

i do not do any special things, just call `setData()` but for me the entire container div gets recreated. i suspect something is off with the mutation observer.

**Comment by glaszig** [comment]
ha! i posted "i do not do any special things" and it came to my mind that i have an event handler for `DOMNodeInserted` that creates slim-select instances for newly added elements:

```js
document.addEventListener('DOMNodeInserted', e => {
    if (e.relatedNode.matches(multipleSelectSelector)) {
      createMultipleSelect(e.relatedNode)
    }
  })
```

of course, slim-select triggers those events, that handler creates new slim-select over existing ones and for that reason copies the existing styles from the original select.

it's basically my fault but i don't understand the different behavior in ie11. `DOMNodeInserted` is supposed to be buggy in ie9 but i guess so it is with all ms-developed js engines -.-

**Comment by brianvoe** [comment]
Interesting. Javascript gets tricky to deal with when doing special things and/or large complicated actions. In your situation I would suggest destroying them first before running create
