### ISSUE TITLE
Multiselect is not closeable per click

### ISSUE THREAD

**Issue by Benj4m1n55** [brianvoe/slim-select#149]
It's not possible to close the multiselect per click again after you open it per click on the main div.
The single select worked as intended as you can see blow in the gif.

![uDghleZX2N](https://user-images.githubusercontent.com/38720155/60388350-5b686280-9ab0-11e9-8db1-4739ea576959.gif)

https://github.com/brianvoe/slim-select/blob/d42ed9cacda116cbfd92f6295f65ecdd4aa97a6e/src/slim-select/slim.ts#L209-L211

It worked after i replaced 
`this.main.open()`
with this
`this.main.data.contentOpen ? this.main.close() : this.main.open()`

**Comment by brianvoe** [comment]
Thanks for pointing this out i have made that update and it will go up in the next release
