### ISSUE TITLE
Feature Request - Specify Opening Direction (Upwards or Downwards)

### ISSUE THREAD

**Issue by Kelderic** [brianvoe/slim-select#15]
Currently when a multi-select is opened, it toggles between opening upwards and downwards. (IE the first click, it slides up. Next time it's opened, it slides down. Then up, then down, etc) It would be wonderful to have an option to specify opening direction. (And also thank you for this script, it's really awesome)

**Comment by brianvoe** [comment]
Hey Keldric,
Thanks for the submission, so the reason that it picks either to go up or down is based upon if it is going to go off screen. As far as IE, i was able to replicate it toggling between the both directions it sounds like a quirky bug.

In regards to being able to select it as an configuration option. I think i can make that happen. Ill get that in today.

If you could star it and help spread the word I would be much appreciated!

**Comment by Kelderic** [comment]
I was just testing in Firefox where the behavior is the same, but yeah screw IE. Anyway, much appreciated! And I've starred the repo and also just tweeted about it.

Follow up question ... is there an option to include or not include the searchbox?

**Comment by brianvoe** [comment]
Thanks! As far as the searchbox you can just do ```showSearch: false```

**Comment by Kelderic** [comment]
Awesome. Last suggestion (and I totally understand if it's not feasible): It would be really great to be able to drag and drop selected options to change the order. Maybe changing the order of the actual hidden select element as well.

**Comment by brianvoe** [comment]
Haha oh wow. Ya i think that might be a little out of scope. Ill keep it on my list and maybe at some point i can prioritize it in somehow. 

I always open to pull requests to if your up to try. 😄

**Comment by Kelderic** [comment]
Yeah I took a look at it but I've never used `ts` or `scss`, so I was a little lost. I may try to figure it out eventually though, because I've already written some drag and drop stuff for a separate purpose.

**Comment by brianvoe** [comment]
👍

**Comment by brianvoe** [comment]
Added showContent which will allow 3 options 'auto', 'up' or 'down'. I fixed the up down toggle weirdness (wasnt ie specific). Also added ability to do innerHTML stuff. Docs are all updated with this stuff. v1.4.0 you should be all good.
