### ISSUE TITLE
Suggestion to change the color

### ISSUE THREAD

**Issue by Benj4m1n55** [brianvoe/slim-select#150]
For accessibility reasons i suggestion to change either the default text color or the default background color on the multiselect.

The white text color is not legible with the primary blue color.

I used Googles Color Tool for this:
[Material Design Color Tool](https://material.io/tools/color/#!/?view.left=1&view.right=1&primary.color=5897fb)

Or this site: 
[Webaim](https://webaim.org/resources/contrastchecker/)

**Comment by brianvoe** [comment]
Im open to a more specific suggestion but i havent had anyone had an issue. And even if they did they are more than welcome to change those colors either through scss or by simple css overrides. 

Thanks for the suggestion though.
