### ISSUE TITLE
selectByGroup issue on IE1

### ISSUE THREAD

**Issue by AndreF010203** [brianvoe/slim-select#151]
Hi, 

On IE11, the selectByGroup option isn't working. 

Here is my workaround: 

```
function IEslimSelectWorkaround(){ 
    var ua = window.navigator.userAgent;
    var msie = ua.indexOf("MSIE ");
    if (msie > 0 || !!navigator.userAgent.match(/Trident.*rv\:11\./)){
    	$(document).on("mousedown", ".ss-optgroup-label.ss-optgroup-label-selectable", function(e){
    		e.preventDefault();
    		$(this).nextAll('.ss-option').each(function(){
    			$(this).click();
    		});
    	});
    }
}
```

**Comment by brianvoe** [comment]
Thanks for helping resolve an ie11 issue. Right now due to the difficulty and lower an lower usage of ie11 I am going to pass on putting too much effort or additional code for the specific purposes of makeing ie11 continue to work.
