### ISSUE TITLE
Unable to get property 'ssid' of undefined or null reference, IE11

### ISSUE THREAD

**Issue by Maris1984** [brianvoe/slim-select#152]
IE11 throws the following console error "Unable to get property 'ssid' of undefined or null reference" and the slimselect is not rendered.
Slimselect is loaded inside a JQuery Confirm dialog box (https://craftpip.github.io/jquery-confirm/), by finding the <select> object via "var obj = modal.$content.find('#myfield')[0]" and then initiated via "select: obj".
It does work on Chrome.

**Comment by brianvoe** [comment]
I looked into this and couldnt find an fix for this. Im open to pr's if you find a simple fix for this. But as of right now i cant continue to put much more work into making sure ie11 still works given its very low usage counts.
