### ISSUE TITLE
Standard markup for the placeholder option

### ISSUE THREAD

**Issue by stof** [brianvoe/slim-select#154]
SlimSelect expects to set `data-placeholder="true"` on an option to make it the placeholder.

The way this works in the HTML spec is that "placeholder" option is given an empty value attribute. From the [HTML spec](https://html.spec.whatwg.org/multipage/form-elements.html#placeholder-label-option):

> If a select element has a required attribute specified, does not have a multiple attribute specified, and has a display size of 1; and if the value of the first option element in the select element’s list of options (if any) is the empty string, and that option element’s parent node is the select element (and not an optgroup element), then that option is the select element’s placeholder label option.

It would be great if the library could support that behavior.

**Comment by brianvoe** [comment]
Im open to a pr if you have something in mind you want to implement.

**Comment by Prithviraj-cyber** [comment]
OK

**Comment by mnba91** [comment]
انت كيف تحكم علي طوال الفرصه شي حلوووو.

**Comment by nacia23** [comment]
>

**Comment by nacia23** [comment]
Good 

>

**Comment by JeffersonMat** [comment]
Good!

**Comment by Tylenol11** [comment]
> SlimSelect expects to set `data-placeholder="true"` on an option to make it the placeholder.
> 
> The way this works in the HTML spec is that "placeholder" option is given an empty value attribute. From the [HTML spec](https://html.spec.whatwg.org/multipage/form-elements.html#placeholder-label-option):
> 
> > If a select element has a required attribute specified, does not have a multiple attribute specified, and has a display size of 1; and if the value of the first option element in the select element’s list of options (if any) is the empty string, and that option element’s parent node is the select element (and not an optgroup element), then that option is the select element’s placeholder label option.
> 
> It would be great if the library could support that behavior.

**Comment by Litecoinlord** [comment]
Good
