### ISSUE TITLE
Small offset between ss-single-selected and ss-content on Firefox

### ISSUE THREAD

**Issue by Applelo** [brianvoe/slim-select#157]
On Firefox, when I resize the window, a small offset appears between .ss-single-selected and .ss-content. It's more visible when I customize the border width.

![Screen Shot 2019-07-23 at 1 26 40 PM](https://user-images.githubusercontent.com/7613286/61733539-07b70500-ad4e-11e9-95fd-a8ce99058d80.png)

**Comment by brianvoe** [comment]
No sure what i could do. If a browser treats border or width/padding/margins differently that causes border misalignment. Im opent o adjustments that could "fix" this.
