### ISSUE TITLE
Problem with z-index of multi "multi select"

### ISSUE THREAD

**Issue by Feri10** [brianvoe/slim-select#159]
I'm using multi slimselect dropdown in nintex form.
my problem is z-index. At first i couldn't see items because another dropdown hides them.

![image](https://user-images.githubusercontent.com/11360487/62420384-72e5cd00-b6a6-11e9-8255-81ea83efb462.png)

When i scroll down it shows correctly. But i want to when i click on any dropdown bring to front and show its items.

**Comment by brianvoe** [comment]
Thats more the usage of your own css. Try adjusting priority of overlapping elements

**Comment by Feri10** [comment]
I did. But i have problem yet. 
i did bring to front elements in bottom to top, but when multi select at the bottom of page display items on others multi select that i set "bring to front".

**Comment by benvanlooy** [comment]
I'm seeing the same issue
![Screenshot 2022-04-25 at 14 22 02](https://user-images.githubusercontent.com/3709877/165088029-8f33f3ca-f8d9-4a4c-8c4d-5b8788dcb17a.png)
