### ISSUE TITLE
Keyboard support

### ISSUE THREAD

**Issue by kswedberg** [brianvoe/slim-select#16]
I'm seeing a couple issues when trying to use the selects with keyboard:

1. With single-select, as soon as I choose an option, it _appears as if_ the widget has lost focus, and there is no way to expand it again unless I tab out and then shift-tab back in (or vice versa). I think what's going on is that the option is actually still holding on to the focus. If I hit the down arrow key, I don't see a change, in the select's value, but if I then press Return, the next option's value appears.

2. With multi-select, I can't figure out how to remove an option (using the keyboard) that I've already selected. I can only select additional options. Maybe I'm missing something here?

Thanks for the widget.

**Comment by brianvoe** [comment]
Those are really good observations. I see where your going with this. Ill make adjustments.

In regards to multi select i can try to see if i can figure out a keyboard shortcut for removing selected items but if i do something like the delete button i would have to just remove the last on the list and not sure how important people find that.

**Comment by brianvoe** [comment]
Also im trying to get the star count on this package up to get this used more. If you like this any way you could give it a star?

Thanks

**Comment by kswedberg** [comment]
Thanks for the prompt reply. I haven't looked at the codebase, but what I had in mind was giving the selected options a `tabIndex` property so the user could tab through them…and then, yes, press the delete button to delete them in turn.

**Comment by brianvoe** [comment]
So i updated some select issues you pointed out. Ill keep the delete possibilities in mind.

**Comment by kswedberg** [comment]
Excellent! Those are great additions to the keyboard accessibility. Thanks!
