### ISSUE TITLE
Get selected Data 

### ISSUE THREAD

**Issue by aeadedoyin** [brianvoe/slim-select#160]
Thanks for this library.
_You rock!_

Please, there isn't a way to get selected object i.e { Text and Value }.
The current `getSelected` only gets the value of the selected option, not the text and it will be useful to be able to the object, that way whichever of the two attributes can be consumed.

**Comment by sinoergin** [comment]
Firstly, you can use setData() method. Example;
```
var values = [ {text:'1', value:'1'}, {text:'2', value:'2'}]
slimSelectSelector.setData(values)
```
and you need selected value. Example;
`slimSelectSelector.selected()`

and you can find text value from selected value. Example;
`values.filter(function(val) { if(val.value==selectedValue) { return val.text; } })`

**Comment by brianvoe** [comment]
@sinoergin is correct. I currently dont return the full object of all selected values just the value. So currently to do what you would like follow the example above
