### ISSUE TITLE
Download link in http://slimselectjs.com/install fails

### ISSUE THREAD

**Issue by drmad** [brianvoe/slim-select#161]
Hi. 

Love your library :smiley: but the download link fails with

`TypeError: Argument 1 is not valid for any of the 1-argument overloads of URL.createObjectURL. install.vue:18`

in Firefox. In Chrome, this is the error:

`install.vue:18 Uncaught TypeError: Failed to execute 'createObjectURL' on 'URL': No function was found that matched the signature provided.
    at e (install.vue:18)
    at XMLHttpRequest.t.onload (install.vue:28)`

HTH

**Comment by brianvoe** [comment]
Thanks for finding that! Ill look into it

**Comment by devcustrom** [comment]
@brianvoe The link still doesn't work)

**Comment by brianvoe** [comment]
New version of slim select has been released. If this is still an issue let me know and ill try to take care of it.
