### ISSUE TITLE
Can't activate addable and ajax at same time

### ISSUE THREAD

**Issue by TheKeyblader** [brianvoe/slim-select#164]
When Addable and ajax option is activate at same time.
Addable doesn't work 

here sandbox: https://codesandbox.io/s/mystifying-bassi-ctrzk?fontsize=14

**Comment by brianvoe** [comment]
Ok ill take a look at it. Thanks.

**Comment by brianvoe** [comment]
New version of slim select has been released. If this is still an issue let me know and ill try to take care of it.
