### ISSUE TITLE
Add css class from selected option to placeholder

### ISSUE THREAD

**Issue by OppaPoo** [brianvoe/slim-select#165]
For css class option can it add the css class from the selected option to the placeholder, for my case I want to add the flag class to the placeholder.
here is an example : [https://codesandbox.io/s/brave-water-zdhfm](https://codesandbox.io/s/brave-water-zdhfm)

**Comment by brianvoe** [comment]
I was trying a few things as a work around. But I think the easiest thing that would also enable your ask would be to grab the innerhtml of the option that has a placeholder and then you could put anything you want in there.

**Comment by OppaPoo** [comment]
![image](https://user-images.githubusercontent.com/15043508/64583809-9f36ec80-d3bc-11e9-8054-853cc065ae9a.png)
Great!! It's work now. one more question if I want to set the default selected to EN-US.

Thank you very much

**Comment by brianvoe** [comment]
selected: true
