### ISSUE TITLE
SlimSelect in jQuery dialog() does not work

### ISSUE THREAD

**Issue by diderich** [brianvoe/slim-select#167]
When creating a SimSelect selector in a jQuery dialog, the list does not fully show, as the selection stays within the dialog window and not the whole screen. Without SlimSelect the selector is fully shown (but not near as nice).

![a](https://user-images.githubusercontent.com/10230144/64905386-e7fde680-d6d7-11e9-9207-dfad83331871.png)

![b](https://user-images.githubusercontent.com/10230144/64905397-1d0a3900-d6d8-11e9-8bf6-c7e087afd25d.png)

![c](https://user-images.githubusercontent.com/10230144/64905389-ecc29a80-d6d7-11e9-8271-c3827a807d7e.png)

**Comment by brianvoe** [comment]
I understand your situation. Slim select renders the list at the location in which the select exists. So you will need to make css alterations in order to get it to work in the dialog box.
