### ISSUE TITLE
Regarding dist files

### ISSUE THREAD

**Issue by silverwind** [brianvoe/slim-select#17]
To allow source files to be identifyable in source-mapped stack traces it would be beneficial to name them like the project. Also, I recommend including both minfied and unminfied files as there are use cases for both, so ideally you would have these dist files:

````
slim-select.js
slim-select.css
slim-select.min.js
slim-select.min.css
````

**Comment by brianvoe** [comment]
I can make that change. Ill get that in asap.

**Comment by brianvoe** [comment]
I update the webpack config to output
```
slimselect.js
slimselect.css
slimselect.min.js
slimselect.min.css
```
I submitted to the cdn to update this as well. That might take a bit to get going but should be updated within the next couple of days.
