### ISSUE TITLE
Multi select ss-add line thickness

### ISSUE THREAD

**Issue by ToishY** [brianvoe/slim-select#171]
I don't know if this should be regarded as a "real" issue, but the lines in  `ss-add` in the multi select box is have a different "thickness" compared to `ss-cross` ([second multi select box](https://slimselectjs.com/selects)). 

![slimselect](https://i.imgur.com/wRiAJfy.png)

It's actually quite noticable (like it's transforming).

**Comment by ToishY** [comment]
Hmm so after more than half a year it seems that I'm still the only one who cares about appearance. 
Btw the demo also shows that the more multiple select boxes you put besides each other, the "uglier" the `ss-plus` gets. `ss-cross` seems unaffected through all of this.

![slimselect](https://i.imgur.com/cL5tZdg.png)

**Comment by ToishY** [comment]
Because I was fed up with a looking ugly, I decided to use the arrow from `single-selected` and replace the `ss-add` by `ss-arrow`

```
<style>
    .ss-main .ss-multi-selected .ss-arrow {
        display: flex;
        align-items: center;
        justify-content: flex-end;
        flex: 0 1 auto;
        margin: 0 6px
    }

    .ss-main .ss-multi-selected .ss-arrow span {
        border: solid #666;
        border-width: 0 2px 2px 0;
        display: inline-block;
        padding: 3px;
        transition: transform .2s,margin .2s
    }

    .ss-main .ss-multi-selected .ss-arrow span.arrow-up {
        transform: rotate(-135deg);
        margin: 3px 0 0
    }

    .ss-main .ss-multi-selected .ss-arrow span.arrow-down {
        transform: rotate(45deg);
        margin: -3px 0 0
    }
</style>

<script>
$('.custom1-select .ss-multi-selected .ss-add, .custom2-select .ss-multi-selected .ss-add').replaceWith('<span class="ss-arrow"><span class="arrow-down"></span></span>');

$(document).on('click', '.custom1-select, .custom2-select', function () {
    var ci = $(this).children('.ss-multi-selected').children('.ss-arrow').children('span');
    if( ci.attr('class') == 'arrow-down' ){
        ci.removeClass('arrow-down').addClass('arrow-up');
    }else{
        ci.removeClass('arrow-up').addClass('arrow-down');
    }
});
</script>
```

**Comment by brianvoe** [comment]
People like you are the reason open source developers get burnt out. Instead of just complaining how about you actually contribute, create a pr and actually present what you think would be a better option.

**Comment by ToishY** [comment]
> People like you are the reason open source developers get burnt out. Instead of just complaining how about you actually contribute, create a pr and actually present what you think would be a better option.

I don't know why you have to get personal like that. Isn't the whole idea of posting an issue here, to fix that issue and improve the project? I'm not here to talk shit on you personally or the whole project if that's what you're thinking. I like slim-select, and I think this is just one of those things which is easy to "fix", that's why I posted it here. Anyway, if I sounded hostile, my apologies. But let's be fair, I've also provided an alternative for those who don't like the current appearance of the plus-sign.

**Comment by brianvoe** [comment]
"Hmm so after more than half a year it seems that I'm still the only one who cares about appearance."
"Because I was fed up with it looking ugly"

Those were the words you decided to use.

**Comment by brianvoe** [comment]
If you really care about the appearance and wanted improve it make a pr and show screen shots of what the new one would look like.

**Comment by ToishY** [comment]
I've already apologized for my poor choice of words and here you are still going on about it. And for the second time, I've provided an alternative above which works for me. You can decide for yourself what to do with that, I'm just not going to spend any more time on this.
