### ISSUE TITLE
Checking the selected value to execute simple css transforms

### ISSUE THREAD

**Issue by odrastudio** [brianvoe/slim-select#172]
It might be a trivial question (starting developer) but I can't seem to figure out how to use and distinguish selected values (native select API?). The task I wanna perform is pretty simple, just change contents of a div below the dropdown based on the selection. Did ton of google, stack etc searching but nothing worked yet.

**Comment by brianvoe** [comment]
if im understanding you correctly. Sounds like you want to do an onChange and then on the value select in the onChange do a setData and change the options based upon your previous selection.

**Comment by odrastudio** [comment]
Phrased it a bit different, sorry! I do not want parse the data directly but just set for example 3 rules eg.:
if Option 1 was selected then execute this jQuery and add class to an item, remove other etc.

I am a beginner and I can't figure out the way to do it since native HTML select is disabled. If it is too much too ask don't worry!

**Comment by brianvoe** [comment]
ya without seeing and working with it myself not sure i follow how i can help. but the slim select website has all the functions layed out with usage examples. Look through them all and im sure the functionality you need is there. slimselectjs.com
