### ISSUE TITLE
Value attribute of options not preserved

### ISSUE THREAD

**Issue by digiperfect-janak** [brianvoe/slim-select#173]
It seems the value attribute of options is not preserved by slim select. As soon as slim select is applied, the value attributes (which in my case are different from the text/labels), get modified. They are replaced by the text of the options. Further attempts to get the selected value result in the text being returned.

Note that I am using the innerHTML option as well.

**Comment by digiperfect-janak** [comment]
Sorry - discovered the issue. I was explicitly providing the data to the select as well as the reference to the HTML DOM select element. The explicit data was overriding the original DOM (which had values set), while the explicit data array did not have the value field set. 

Perhaps - if both options are provided, slimselect could give a warning.

**Comment by brianvoe** [comment]
New version of slim select has been released. If this is still an issue let me know and ill try to take care of it.
