### ISSUE TITLE
Select open in 'above' state even if exists enough free space at bottom

### ISSUE THREAD

**Issue by User756675678** [brianvoe/slim-select#175]
Example code:
https://jsfiddle.net/q0so1j4u/1/

Video from real usage:
https://streamable.com/or9uv

Screen from js fiddle:
![scr_1571777041](https://user-images.githubusercontent.com/53032556/67330970-d9e88480-f525-11e9-90f8-f9df914fb362.png)

Solution: #174

**Comment by User756675678** [comment]
Video from jsfiddle:
https://streamable.com/vc7dv

I only resize result area and press button `Run`. Nothing more.

**Comment by User756675678** [comment]
It is happens because wrong math. And select need twice height of options for open in state 'below'.  
Because height added twice, as I pointed on pull request page.

**Comment by brianvoe** [comment]
jsfiddle uses an iframe for its results. This functionality works as it should

**Comment by brianvoe** [comment]
![openclose](https://user-images.githubusercontent.com/1580910/67338289-6d9e5e80-f4ee-11e9-9cde-587b644e220f.gif)

**Comment by User756675678** [comment]
Wrong. Without frame bug present.
https://fiddle.jshell.net/q0so1j4u/1/show/
![bug3](https://user-images.githubusercontent.com/53032556/67399585-23cc7b80-f5b5-11e9-87bf-526d69d0ea32.gif)

**Comment by brianvoe** [comment]
<img width="1138" alt="Screen Shot 2019-10-23 at 9 29 53 AM" src="https://user-images.githubusercontent.com/1580910/67403547-b77f5700-f577-11e9-902f-a2cbf52c50b3.png">

**Comment by User756675678** [comment]
https://fiddle.jshell.net/q0so1j4u/1/show/light/
![ezgif-2-7d09ab86d78b](https://user-images.githubusercontent.com/53032556/67407369-0ea91a00-f5c0-11e9-9310-fda84cab99ba.gif)
