### ISSUE TITLE
onChange Event is called twice when element changed

### ISSUE THREAD

**Issue by yhilcenko-fa** [brianvoe/slim-select#18]
Whenever the version of SlimSelectJs version you used, the "onChange" event is called twice when element changed.

Very simple example using latest SlimSelectJs Lib (1.4.3).
https://jsfiddle.net/0yqfabm8/

**Comment by brianvoe** [comment]
Good catch. Ill fix that.

**Comment by brianvoe** [comment]
Updated the script and published to npm. v 1.5.0.

Thanks!
