### ISSUE TITLE
Browser support and keyboard events

### ISSUE THREAD

**Issue by levmorozov** [brianvoe/slim-select#180]
How can it support IE 11+, Chrome 30+, Safari 9+, if slim-select uses KeyboardEvent .key instead of good old keyCode ?

https://caniuse.com/#search=KeyboardEvent%20.key

**Comment by brianvoe** [comment]
webpack babel

**Comment by levmorozov** [comment]
I was talking about production build (dist/slimselect.js). So its already after babel.
