### ISSUE TITLE
How a get the single selected.

### ISSUE THREAD

**Issue by Fruchtgummi** [brianvoe/slim-select#183]
Ok, i can find the all selected elements in array with select.selected().

How i get the single element what pushed now or was deleted on selected array ? I need this...

**Comment by brianvoe** [comment]
I have a hard time following what your are trying to say

**Comment by Fruchtgummi** [comment]
With select.selected() you only give me the whole array. I missed the possibility to somehow see which element to add. What I click, what I add to the selected array. An event on a single <option> element.

**Comment by brianvoe** [comment]
the selected() method gives you the current value of the select dropdown. Im still trying to understand your issue but based upon what your saying your trying to get values before and after changes happen, in which you can use beforeOnChange and onChange to get values before and after a new value is added or removed
