### ISSUE TITLE
Can't figure out how to set default value through options in dynamic select

### ISSUE THREAD

**Issue by lwxbr** [brianvoe/slim-select#184]
Hi there, I'm struggling how to add an option to set the default value of my select and I didn't find anything in the docs. My select is virtual (i don't use options, i just use my select and add options with setData):

```html
<select id="my-select></select>
```
```js
 const select = new SlimSelect({
   select: '#my-select',
   valuesUseText: false,
   showSearch: false,       
   selected: true,
});

const myData = [...]; //my options
select.setData(myData);
```
I could use the method ```set``` to set the value but it triggers the ```onChange``` event and I don't want that. There is a better way to achieve it? Thank you!

---

**Edit:** I found a workaround for now reading the code, but it could be simpler: 

```js

//add this after setData
  select.data.setSelected(myDefaultValue, 'value');
  select.select.setValue();
  select.render();
```

**Comment by brianvoe** [comment]
you can do that or in the data array set the one you want to selected: true. Not selected true in the main initiation object
