### ISSUE TITLE
Since version 1.5 current value is incorrect

### ISSUE THREAD

**Issue by konrad-g** [brianvoe/slim-select#19]
I use slim-select with Parsley.js validation library. It used to work great in version 1.4.1.
After an update to latest version 1.5.1, validation doesn't work properly. 

Validation occurs in "change" event. After changing value in slim-select, previous value is taken into account, not the current one, i.e. If I change from "None" to "Something", in "change" event shows that value "None" is selected, I expect that it says "Something".

**Comment by brianvoe** [comment]
Sorry that happened. Let me look into it and see if i can find what happened

**Comment by brianvoe** [comment]
Ok i fixed that issue. version 1.5.2.

Thanks for pointing that out and if you enjoy the package give it a star. It really helps. 😄

**Comment by konrad-g** [comment]
Thank you Brian. I already gave it a star. 
You did a great work by the way!
👍👍👍

**Comment by brianvoe** [comment]
Glad you enjoy it. Thanks.
