### ISSUE TITLE
Multiple instances created on same element causes error

### ISSUE THREAD

**Issue by andoband** [brianvoe/slim-select#191]
First of all, thanks for great project!

I came across an issue after grabbing the latest code.

After the "addToBody" feature was added (#186), creating a new instance of SlimSelect for an element that already has a SlimSelect called on it causes an error "Cannot read property 'addToBody' of undefined"

The error can be recreated simply:
```js
new SlimSelect({ select: "#single" });
new SlimSelect({ select: "#single" });
```
The code is blowing up in the `destroy` method.  I dug into it a bit and I see that the following code was added in that pull request.
```js
// remove the content if it was added to the document body
if (this.config.addToBody) {
  const slimContent = (id ? document.querySelector('.' + id + '.ss-content') : this.slim.content)
  if (!slimContent) { return }
  document.body.removeChild(slimContent)
}
```
As you can see it expects `this.config` to have a value, which it doesn't because `this.config` is created after the call to `destroy()` in the constructor.

I'd like to continue to be able to call the SlimSelect constructor on the same element multiple times and have the previous instance cleaned up correctly.  Thanks!

**Comment by brianvoe** [comment]
This is a good catch. Ill look into and see if i can fix any issues i see

**Comment by dfagan2** [comment]
@brianvoe - any progress on this? seeing the same thing

**Comment by brianvoe** [comment]
Sorry no progress at the moment. The current work around would be to not call the same element. But im assuming your doing that already

Whats the reason you need to call it multiple times?

**Comment by dfagan2** [comment]
Yeah, I was able to work around it by manually destroying before reinitializing. The use case would be a re-render in React-land, when an option property is changed (like multi-select). It'd be nice to not have to manually keep track of the node reference, check to see if it's already been initialized, and destroy it first before rebuilding with the newly changed option. (would just clean up some code that sounds like it's redundant if SlimSelect already attempts to manage this under the hood)

**Comment by andoband** [comment]
I have the same use case where I'm calling during a re-render, except I'm calling from Blazor WebAssembly-land.  And I agree with @dfagan2 that it'd be nice not to have to track the DOM instance.  For now I just rolled back to the previous version of Slim Select.

**Comment by brianvoe** [comment]
Believe me i hear you guys. I have a v2 of this package that im working on but with the other open source packages I also maintain it just get tough trying to tackle everything. Thats why if people want to see things fixed it really would be best to jump in and make a pr.

**Comment by sinoergin** [comment]
I'm using multiple instances but i dont get any error. I'm creating instance at initialize time and i'm creating new instance this dom. Probably, i cant explain. i will explain with code :) 

```
var slimSelector;
$(document).ready(function() {
   slimSelector = new slimSelect({
     select: '#X'
   })
})

$('otherDom').change(function() {
  var selector = new slimSelect({
     select: '#X'
   })
  var selectedVal = selector.selected()
})
```

I hear now. you can say 'you dont need that because use global variable'. Yeah i know but just i want to try and i dont get any error.

**Comment by francesco-loreti** [comment]
Any news?
I have the same error if i want to destroy a slim-select and recreate it.

**Comment by interceptor** [comment]
Problem still persists for me also.

**Comment by brianvoe** [comment]
New version of slim select has been released. If this is still an issue let me know and ill try to take care of it.
