### ISSUE TITLE
Can't get de-selected value

### ISSUE THREAD

**Issue by Mu2tini** [brianvoe/slim-select#192]
When using single select and having the property **allowDeselect** set to true there is no way to get the de-selected value.

OnChange() is called but the info argument has empty fields and beforeOnChange() doesn't get called att all when de-selecting.
Is this a bug, because would really like to have this feature...

**Comment by brianvoe** [comment]
Sounds like a minor oversight. Ill see about adding a beforeOnChange call when deselecting a value. Although right now you should already know the value selected before clicking deselect

**Comment by brianvoe** [comment]
New version of slim select has been released. If this is still an issue let me know and ill try to take care of it.
