### ISSUE TITLE
add multiple selector

### ISSUE THREAD

**Issue by Genexys** [brianvoe/slim-select#193]
please, add multiple selector on once call, example 

`
<select class="selects"></select > 
<select class="selects"></select >
<select class="selects"></select >
<select class="selects"></select >
<select class="selects"></select >
`

`new SlimSelect({
  select: '.elements ',
  // or
  select: document.querySelectorAll('.elements')
})`

**Comment by brianvoe** [comment]
Just use a simple for loop.
