### ISSUE TITLE
How to select default first option while searching??

### ISSUE THREAD

**Issue by patel33hardik** [brianvoe/slim-select#195]
My issue is, Currently, I can searching and I need to use down key in order to select the first option and then click enter. Looking for code or option, that allowed me to default select a first search option while I am searching and when I press enter It can select that option. 

I really appreciate any helps.
thanks

**Comment by brianvoe** [comment]
Their isnt something so specific that you could do what your asking as a direct method that exists in slim select. But you could use the searchFilter method and run a settimeout in there to select the first value and that should replicate what your going for.
