### ISSUE TITLE
Deselect All button

### ISSUE THREAD

**Issue by drzraf** [brianvoe/slim-select#196]
**Describe the bug**
In many cases, `slim-select` is used with lists having many items.
In these cases, a configurable "deselect All" would be helpful.

**Comment by brianvoe** [comment]
Maybe i dont understand but why dont you just loop through your slim select list and deselect? It would be very specific to have a functionality that within one slim select instance look for all instances and perform an action against them.

**Comment by drzraf** [comment]
For anyone interested (and although heavier than initially expected):

```js
/**
  * Dynamically add (or remove) a "Deselect All" pseudo-option
  */
function slimSelectDeselectAll(info) {
   var curData = this.data.data;
   var selected_count = info.length;
   var has_deselect_button = curData.filter(v => v.value === '' || v.value === 'Deselect all').length > 0;
   var wants_deselect = this.selected().includes("Deselect all") || this.selected().includes("");

   if (wants_deselect) {
      this.set([]);
      this.setData(curData.filter(v => v.value !== '' && v.value !== 'Deselect all' ));
      return;
   }

   if (selected_count && !has_deselect_button) {
      curData.unshift({value: "", text: "Deselect all"});
      this.setData(curData);
   }
}
```


`new SlimSelect({select: '#filter-cc', onChange: slimSelectDeselectAll});`

This sample tends to show that the value/text behavior is a bit under-specified : In multiple places I had to test for both text or value.
