### ISSUE TITLE
Placeholder must be the first option when using setData?

### ISSUE THREAD

**Issue by yellow1912** [brianvoe/slim-select#198]
**Describe the bug**
If we setData, the placeholder option must be the very first element on the list. I think the library should be smart enough to scan through the list of options and pick out the placeholder.

Alternatively, I think setData should not even touch placeholder, it should be managed separately via a different api method.

**Comment by brianvoe** [comment]
The reason its the first option is because when i propagate the original select dropdown javascript uses the first option as the default selection. but if you want to do a pr to test your theory im open to looking at it.
