### ISSUE TITLE
Feature Request: Icons from options for existings selects

### ISSUE THREAD

**Issue by NitemareReal** [brianvoe/slim-select#199]
As any non text entered as option text is supressed by HTML, there is no way of adding icons to text (or using just icons) when transforming a common existing select tag into a SlimSelect widget, but, if in any option tag we could use a "data-icon" tag (for example) with value of icon url, so, every time SlimSelect renders text, it could prepend an img tag with the icon. You don't even need to offer left or right justify (insert before or after text node) since using CSS "float:left/float:right" on img tag do it well

For example:

```
<select id='mySelect'>
<option value='1' data-icon='../images/sun.png'>Sun</option>
<option value='2' data-icon='../images/moon.png'>Moon</option>
</select>

```
It could looks like this:

![Imagen1](https://user-images.githubusercontent.com/28754812/77167424-5754f880-6ab6-11ea-943b-62ba9d929727.png)

**Comment by brianvoe** [comment]
you can use data option to set innerHTML

**Comment by NitemareReal** [comment]
But if you  generate a "select" item with PHP, JSP, o whatever and you want to associate an different icon to each "option", can you do it using data option? Is the case where the server doesn't send json/whatever data to build "options", the server just "prints" the "select" HTML code and SlimSelect is initialized on DOM ready...
Maybe I haven't understood the purpose of data option to set innerHTML...

**Comment by brianvoe** [comment]
PHP might add layers of difficulty but slim select can do what you want currently. I unfortunately don't want to add specific features like this to compensate for things like PHP templating. 

If you are using PHP and have the script tag in your template you could just loop through and set your data that way

**Comment by NitemareReal** [comment]
Thank you so much, cheers

**Comment by brianvoe** [comment]
as a side note I used to be a PHP developer and if your developing in PHP and still using templating that way I would suggest moving away from that. start treating your back end like an api and separate your from end from your back and youll be better off for it. just my two cents

**Comment by migliori** [comment]
Hello,

If it can help other users, I too needed to add icons to the options without using Javascript, and data-attributes seemed to me to be the right way to do it.

Here's a simple sample code ; "_slm_" is the _slim-select_ instance.

```
slm.data.data.forEach(d => {
    if (d.data && d.data.icon !== undefined) {
        let iconHtml = '<i class="' + d.data.icon + '"></i>' + d.text;
        d.innerHTML = iconHtml;
    }
});
// call setData() to rebuild
slm.setData(slm.data.data);
