### ISSUE TITLE
Slim Select lags / has poor performance when it contains over 1000 elements

### ISSUE THREAD

**Issue by Zamiell** [brianvoe/slim-select#202]
Greetings and thanks for the excellent library!

* I have a website for a game.
* When the user clicks "Create New Game", I use [Tooltipster](https://iamceege.github.io/tooltipster/), (a tooltip library) to create a new tooltip that contains the various toggle-able game options.
* Inside the tooltip, I have a Slim Select box with over 1000 elements in it. (They are the possible game-modes for my game.)
* The game modes in the Slim Select box are automatically populated from a JSON file that the user has already downloaded as part of the client. Thus, there is no need to use AJAX for this - the user already has all of the data.
* Before Slim Select, I was just using a vanilla [HTML5 input list attribute](https://www.w3schools.com/tags/att_input_list.asp). Even with over 1000 elements in the list, opening the tooltip (e.g. drawing/rendering the new DOM) was instantaneous.
* Now, with Slim Select, whenever the tooltip is drawn/repositioned/updated, the whole client lags for 1-2 seconds, presumably because it has to re-render all of the Slim Select stuff behind the scenes.
* For troubleshooting purposes, I reduce the amounts of element to 50, and I get no lag, so it seems Slim Select can't handle large lists.
* I don't want to hide any options from the user because I want them to be able to see all of the options that are possible for my game.

I have done a little searching and I have seen that in the past, you have recommend to use AJAX calls to increase performance. But as I said, I don't think this is relevant to my problem - the user already has all of the data downloaded.

Are there any other performance tips you can recommend? Is there a workaround to somehow have less "stuff" in the DOM and have Slim Select keep the input options completely in memory, or something?

**Comment by brianvoe** [comment]
Sorry youve tackled all the avenues i would have. It wouldnt be a problem in normal circumstances but in a tool tip situation in which the dom is created on a more on action instead of on a page load situations your work around is pretty limited.

If you figure something out and want to make a pr. Im more than open to suggestions.

**Comment by Zamiell** [comment]
For future readers who are wondering, I am working around the lag problem by using the following disgusting code:

```typescript
    // In the create game tooltip,
    // the user can select a variant in a dropdown that contains all 1000+ variants
    // Unfortunately, having so many div elements causes the DOM to lag every time the tooltip is
    // opened; thus, we show a "fake" variant dropdown by default, and only populate the real one if
    // the fake one is clicked
    // "createTableVariant" is the "fake" element
    // "createTableVariant2" is the Slim Select element
    $('#createTableVariant').click(() => {
        $('#createTableVariant').empty();
        $('#createTableVariant').append($('<option/>', {
            value: null,
            text: 'Loading the variants...',
        }));
        $('#createTableVariant').blur();

        // Put the rest of the code in a callback so that the browser screen will update and show
        // the "Loading the variants..." text
        setTimeout(() => {
            $('#createTableVariant').hide(0);
            $('#createTableVariant2').empty();
            $('#createTableVariant2').show(0, () => {
                // Populate the Slim Select dropdown with the name of every variant
                const line = '──────────────';
                for (const [variantName, variantJSON] of Object.entries(variantsJSON) as any) {
                    $('#createTableVariant2').append($('<option/>', {
                        value: variantName,
                        text: variantName,
                    }));

                    if (variantJSON.spacing) {
                        const spacing = new Option(line);
                        spacing.disabled = true;
                        $('#createTableVariant2').append($(spacing));
                    }
                }

                // Transform the select element into a Slim Select element
                variantDropdown = new SlimSelect({
                    select: '#createTableVariant2',
                    afterClose: () => {
                        // Write the newly chosen variant back to the fake select element
                        const variantChosen = $('#createTableVariant2').val();
                        $('#createTableVariant').empty();
                        $('#createTableVariant').append($('<option/>', {
                            value: variantChosen,
                            text: variantChosen,
                        }));

                        // Hide & destroy the Slim Select dropdown and
                        // re-show the fake select element
                        $('#createTableVariant2').hide(0);
                        $('#createTableVariant').show(0);
                        variantDropdown.destroy();
                        $('#createTableVariant2').empty();
                    },
                });

                // The user expects the dropdown to be open, so manually open it
                variantDropdown.open();
            });
        }, 0);
    });
```
