### ISSUE TITLE
Style the dropdown colours?

### ISSUE THREAD

**Issue by uglyeoin** [brianvoe/slim-select#210]
**Describe the bug**
A clear and concise description of what the issue is.

Sorry to ask another crap question, but how can I change the background colour on the dropdowns?  I have tried styling them but it seems they don't seem to be styled.

**Comment by brianvoe** [comment]
No problem. You can buy me a coffee if you feel guilty enough. :smiley: https://www.buymeacoffee.com/brianvoe

On individual options you can add a class to your option and style that class. On the main select bar background its both .ss-single-selected and .ss-multi-selected and the options dropdown is ss-content.

You can always right click->inspect element to see the element breakdown

**Comment by uglyeoin** [comment]
Happy to buy you a coffee/beer.  Just because I use your code.  with fresher eyes this morning I had less issues.  It turns out it was me being stupid.

**Comment by uglyeoin** [comment]
Thanks for your support

**Comment by brianvoe** [comment]
Glad to help how everything works out for you
