### ISSUE TITLE
Feature Request: selectable optgroup

### ISSUE THREAD

**Issue by lessless** [brianvoe/slim-select#213]
Hi, 

I would like to propose  a feture request: makre optgroup selectible in multiple mode.

For example in a 

```
<select id="multiple-optgroups" multiple>
  <optgroup label="Cars">
    <option value="SUV">SUV</option>
    <option value="sedan">Sedan</option>
    <option value="Minivan">Minivan</option>
  </optgroup>
  <optgroup label="Bikes">
    <option value="sport">Sport</option>
    <option value="Offroad">Offroad</option>
  </optgroup>
</select>
```

use will have ability to select `Cars`  and `Bikes` along with everything specified in an `option` tags. 

and thanks for an awesome library!

**Comment by jledgett** [comment]
I second this request!

**Comment by eat-sleep-code** [comment]
@brianvoe I second this request!

**Comment by brianvoe** [comment]
This feature should be in slim select by now. New version of slim select has been released. If this is still an issue let me know and ill try to take care of it.
