### ISSUE TITLE
First Element is always selected

### ISSUE THREAD

**Issue by realulim** [brianvoe/slim-select#215]
This is not a bug report, but more a request for any and all information that could help me debug this mysterious error.

I have a webapp with a slim-select (version 1.26.0) and it works great locally as well as in production. The only environment where it does not work is on our CI server. However, we do continuous deployment, so it's actually the same artifact that goes through the pipeline. The error is very simple:

No matter which element I select from the popup menu, it's always the first element that comes back as selected like so:

```
<span class="ss-value-text">
<div class="option-1" value="1" data-content="First Option"></div>
</span>
```

What's more, I cannot select any additional elements, even though it is a multi-select. I can remove the selected element and then select another, but that will be the first element again. What could be the reason for such a behavior in one environment only?
Unfortunately I cannot provide an example, because it can only be reproduced on our internal CI network. Obviously, I have already reinstalled and rebuilt everything from scratch.
It may be worth noting that the relevant code has remained untouched for months and went through our CI pipeline and test suite hundreds of times before. The error suddenly appeared in a nightly build right after there was some network maintenance.
This is how the select is created:
```
window.createSelector = function (cssSelector, header, options) {
    let data = new Array(options.length);
    for (let i = 0; i < options.length; i++) {
        let className = 'option-' + options[i];
        data[i] = {innerHTML: '<div class="' + className + '" value="' + options[i] + '"></div>', text: options[i]};
    }
    new SlimSelect({
        select: cssSelector,
        showSearch: false,
        placeholder: header,
        hideSelectedOption: true,
        data: data
    });
};
```

**Comment by rtarnaud** [comment]
You should probably add a value property to data[i] containing your option value as it is required by SlimSelect, afaik. I am not saying it will solve your issue but it is a better practice.

**Comment by realulim** [comment]
In the docs it says:
`value: 'value', // Optional - value will be set by text if not set`

What might help is to insert Debug-Logging in the Slim Select code to see where it falls down.

**Comment by realulim** [comment]
Turns out that re-installing node and npm fixed the error.

**Comment by realulim** [comment]
Turns out that re-installing only fixed the bug, because an older version of SlimSelect was then installed. The bug is still only reproducible on one machine, but it does not occur with versions up to 1.25.0. So I assume something must have changed after that, which triggers the behavior in certain environments.

**Comment by ytya** [comment]
Hi, I had a similar problem. I could solve it by explicitly setting the value property.
It is probably due to the change in select.ts.

[select.ts(v1.25.0)](https://github.com/brianvoe/slim-select/blob/v1.25.0/src/slim-select/select.ts#L136)
```
public createOption(info: any): HTMLOptionElement {
  const optionEl = document.createElement('option')
  optionEl.value = info.value || info.text
  ...
```

[select.ts(v1.26.0+)](https://github.com/brianvoe/slim-select/blob/v1.26.0/src/slim-select/select.ts#L137)
```
public createOption(info: any): HTMLOptionElement {
  const optionEl = document.createElement('option')
  optionEl.value = info.value !== '' ? info.value : info.text
  ...
```

If I don't set the value property then the info.value may be 'undefined' instead of ''.
So in v1.26.0+, unlike the docs, all optionEl.value are 'undefined'.

In [setValue()](https://github.com/brianvoe/slim-select/blob/v1.26.0/src/slim-select/select.ts#L42), the selection states are decided by comparing the value property, so it doesn't work as expected.

**Comment by brianvoe** [comment]
New version of slim select has been released. If this is still an issue let me know and ill try to take care of it.
