### ISSUE TITLE
Multi select not working after searching

### ISSUE THREAD

**Issue by Incognito2517** [brianvoe/slim-select#217]
Hi, when i try to select the second option after searching i get an error 
![Screenshot1](https://user-images.githubusercontent.com/25984970/82339044-e1093f80-99ed-11ea-8713-401926eca0c5.png)

But when I click outside so that the drop down goes closed and start searching again then i can select many options without getting the error.

Here is the code snippet where slimselect is initialized:

`function initDropDowns () {

        $('[slimselect]').each(function (index) {
            var id                 = $(this).attr("id");
            var placeholder        = $(this).data("placeholder");
            var selectByGroup      = true;
            var compareDropDown    = false;
            var dataSelectByGroup  = $(this).data("selectbygroup");
            var dataCmpareDropdown = $(this).data("comparedropdown");

            if (dataSelectByGroup) {
                selectByGroup = dataSelectByGroup === "true";
            }
            if (dataCmpareDropdown) {
                compareDropDown = dataCmpareDropdown === "true";
            }

            var that = this;
            var select = new SlimSelect({
                select:     '#' + id,
                placeholder: placeholder,
                showSearch:  true,
                searchText: settings.texts.noSearchResults,
                searchPlaceholder: settings.texts.searchPlaceholder,
                searchingText: settings.texts.searchingText,
                searchHighlight: true,
                closeOnSelect: false,
                showOptionTooltips: true,
                selectByGroup: selectByGroup,
                hideSelectedOption:true,
                limit: 5,
                beforeOnChange: function (info) {
                    if ($(that).data('singleselect') === true) {
                        dropDowns[that.id].set ([]);
                    }
                },
                onChange: slimSelectOnChange
            });
            dropDowns[id] = select;
        });
    }`
If you need more detailed information, please let me know. Thank you in advance!

**Comment by brianvoe** [comment]
Thanks for trying to be elaborate about your issue. The problem i have is their is a lot of miscellanies other pieces of this that can or could be effecting your situation. In order to rule out your part of the code as the issue I would need to see the issue as a stand alone without any other outside interference. Cause most of the time when i see this the issue normally has to do with outside code.

A js fiddle would help as well.

**Comment by brianvoe** [comment]
New version of slim select has been released. If this is still an issue let me know and ill try to take care of it.
