### ISSUE TITLE
Feature Request: Changing default 'Search' placeholder

### ISSUE THREAD

**Issue by rafaelytakei** [brianvoe/slim-select#219]
Hi,

Is there a way to implement a option to change the default 'Search' and 'No Results' message? From the website example, it would be this 'Search':

https://i.imgur.com/3waqzrw.png

I'd be using it to change the language of these messages basically, which is probably an easier implementation then adding a change language support

**Comment by brianvoe** [comment]
you can use searchingText to change the placeholder text in the search bar. You can reference an example usage in the slimselectjs.com docs under options.
