### ISSUE TITLE
removeEventListener on slim.destroy()

### ISSUE THREAD

**Issue by Woloja** [brianvoe/slim-select#220]
**Problem with destroy method**
I use Vue.js for my site, and have many listeners after traversing. Try destroy slim instance, work well but don`t remove event from document(

**Comment by Woloja** [comment]
http://prntscr.com/stvane example from demo page.
On load have 18 events.

http://prntscr.com/stvc8u after several times re-init

**Comment by brianvoe** [comment]
Sorry i dont fully understand your issue. If you would like to submit a pr for me to look at I would be more than happy to merge it in.

**Comment by Woloja** [comment]
Ok, I’ll try, but I never wrote in typescript.

**Comment by jbanety** [comment]
Hi, I have the same issue.
If I destroy instances, the listeners bound on document still exists. 
So if I recreate them, new listeners are bound. 
Memoy leaks 🙄

**Comment by brianvoe** [comment]
New version of slim select has been released. If this is still an issue let me know and ill try to take care of it.
