### ISSUE TITLE
Feature request: easy form reset functionality

### ISSUE THREAD

**Issue by roelvanmeer** [brianvoe/slim-select#223]
Thanks for writing Slim Select!

Is there an easy way to get Slim Select to reset the selectbox to its original value when a form reset button is pressed?

I figure it is possible to use the selected() method after loading to get the original value, and uset set() to restore that in a function called by the form reset button, but maybe there is an easier way?

Thanks, Roel

**Comment by brianvoe** [comment]
Glad you like it!

You are correct in that the best way is to just set() of the values you would like to use.

Thanks.

**Comment by roelvanmeer** [comment]
I was thinking it would be nice if the default value(s) could be saved to a private property after initialization, which then could be selected by simply calling a reset() method.

**Comment by brianvoe** [comment]
I hear you but I think you would find out that its basically the same amount of code you would have to write that does the same exact thing.

**Comment by amichel86** [comment]
@roelvanmeer I am looking to do the exact same thing. Would you happen to have a code snippet for the set() method?

**Comment by roelvanmeer** [comment]
We're using the code below. It is included once for every SlimSelect object in a form, and the form reset calls the `form_reset` function. You'll probably need to change it for your use case.

```
// Declare the arrays where we keep our SlimSelect objects and their default values.
var ss_list = ss_list || [];
var ss_defaults = ss_defaults || [];

// Init a new SlimSelect object.
ss = new SlimSelect({
  select: '#$id'
});

// Save its default value, and save the object itself.
ss_defaults.push(ss.selected());
ss_list.push(ss);

// Unless already defined, define functions that reset the SlimSelect objects to their
// default values.
if (!(form_reset && typeof(form_reset) == "function")) {
  function form_reset() {
    ss_list.forEach(ss_reset);
    return true;
  }
  function ss_reset(ss_obj, index, array) {
    ss_obj.set(ss_defaults[index]);
  }
}
```

**Comment by raLaaaa** [comment]
Just in case anyone stumbles upon this, this is the way I do it:'

```
        $("#form")[0].reset();
            var event = new Event('change');
            document.getElementById('ss-select').dispatchEvent(event);
        });
```

You reset the form via JS and trigger the rerendering function by dispatching an change event.
