### ISSUE TITLE
mandatory isn't workin

### ISSUE THREAD

**Issue by ChristerE** [brianvoe/slim-select#224]
When I add mandatory I expect that the delete button (x) should disappear, but whatever I try it fails, see code and examples below. Besides the code below I've also tried the other example, but with the same result: 
`<option value="A" data-mandatory="true" selected>A</option>`

I have the following code:
Select element: `<select id="test-mandatory" multiple></select>`
`<script>
    $(document).ready(function () {
        var test_mandatory = new SlimSelect({
            select: 'select#test-mandatory'
        });
        const data = [
            { value: '1', text: 'Mounting', mandatory: true, },
            { value: '2', text: 'Listing', mandatory: false },
            { value: '3', text: 'Painting', mandatory: false },
            { value: '4', text: 'Plating', mandatory: false }
        ];
        test_mandatory.setData(data);
        test_mandatory.set(["1", "2", "4"]);
        console.log('test_mandatory: ' + JSON.stringify(data))
    });
</script>`
The console shows: 
test_mandatory: [{"value":"1","text":"Mounting","mandatory":true},{"value":"2","text":"Listing","mandatory":false},{"value":"3","text":"Painting","mandatory":false},{"value":"4","text":"Plating","mandatory":false}]

I would like to have the "Mounting" option without the delete button.

![test_mandatory_1](https://user-images.githubusercontent.com/15075822/85957743-44dd3b80-b990-11ea-8724-c5f5350acf95.PNG)

**Comment by brianvoe** [comment]
New version of slim select has been released. If this is still an issue let me know and ill try to take care of it.
