### ISSUE TITLE
Replace "X" by custom icon in Multiple Select

### ISSUE THREAD

**Issue by amichel86** [brianvoe/slim-select#225]
Hello, thank you so much for your plugin, real life saver!

Quick question, is there a parameter to replace the "X" text when selecting a choice in the multiple select? I was able with ::after to add my custom icon but i'd like to remove the original one, thanks! :)

![image](https://user-images.githubusercontent.com/5871701/86964235-c329a280-c133-11ea-8d41-972ee3c6f6b9.png)

**Comment by brianvoe** [comment]
Sorry i dont have anything that allows you to change that value

**Comment by amichel86** [comment]
@brianvoe it's not even somewhere in the JS so I can remove it or something? :P

**Comment by amichel86** [comment]
@brianvoe it is possible using the OnChange callback, here's the complete code if someone is looking to do the same thing.

`// Slim Select
new SlimSelect({
	select: '#select-neighborhoods',
	showSearch: false,
	placeholder: 'Sélectionner',
	onChange: (info) => {
		$('.ss-value-delete').html('<i class="icon-close"></i>');
	}		
})`
