### ISSUE TITLE
Can't set value using .val()?

### ISSUE THREAD

**Issue by patel33hardik** [brianvoe/slim-select#228]
Thanks for creating such a beautiful slim-select.
I want to update my select input with slim-select by minimal changes.
But to set the values to select, I have to use select.set() method. 
Is that any way to set value traditionally without changing code?
i.e $('#select').val('value1')

Please check this fiddle 
http://jsfiddle.net/patel33hardik/Lgu87v34/3/

**Comment by brianvoe** [comment]
Thanks for the kind words!

I believe jquery doesnt trigger change events when setting values. So if you need to use jquery you might want to look into that.

You also dont need jquery to do anything anymore so i updated your jsfiddle with just a javascript equivalent example.

http://jsfiddle.net/7goewpbd/1/

Hope that helps.

**Comment by patel33hardik** [comment]
@brianvoe 
Thanks for the quick response. 
Seems, It would be better to Set() method.
Although the following works.

```
var multi = new SlimSelect({
	select: '#multiple'
});
$('#multiple').css('display', 'block');
$('#multiple').val('value 3');

```
