### ISSUE TITLE
How to make "addable" trigger on enter?

### ISSUE THREAD

**Issue by marbuser** [brianvoe/slim-select#229]
I've had a look through the full documentation and I've been unable to find out how to make it so that if I have `addable` enabled, it will trigger if I type something in and then push enter as opposed to clicking the button.

Hopefully someone can help.

**Comment by brianvoe** [comment]
The input field is for searching so if you want it to perform an action on enter you can add your own event listener to the input field and then perform any action you want.

**Comment by marbuser** [comment]
@brianvoe Surely this is a bug? After source diving I found you already have this functionality built in, it just doesn't work.
https://github.com/brianvoe/slim-select/blob/6a992c7ee8ccfb3964f278fc7d42c21658b1e766/src/slim-select/slim.ts#L395-L419

Regardless of that I tried my own method of doing it and doesn't work. I figured we would be able to call the addable function directly but I guess not? Can you please elaborate a bit on your previous comment of how we are expected to do it? Because there is nothing in the docs that really covers this.
```js
            inputEl = select.slim.search.input;
            inputEl.addEventListener('keyup', function (event) {
                if (event.key === 'Enter') {
                    select.addable(event.target.value);
                }
            });
```

**Comment by mtomov** [comment]
It seems to work with `Ctrl + Enter`. 

I'd be interested in a solution with just `Enter` as well.

**Comment by ktunprasert** [comment]
I made it work with a super hacky solution using what @marbuser and @mtomov provided above
```
let ref = customCC.select.main;
ref.search.input.onkeyup = e => {
	if (ref.addable && e.key === "Enter"){
		ref.slim.search.addable.click();
		ref.slim.search.input.value = "";
	}
};
```
Beware that if you have a constraint on the value then you will have to make sure the value passes the constraint before setting it to null.

**Comment by mtomov** [comment]
Nice one! I'll try it myself as well. Thank you!

**Comment by rickychilcott** [comment]
This is still an issue with the latest versions of slim select. I used the above to add the functionality

```js
const widget = new SlimSelect({})
const contentSearch = widget.render.content.search

contentSearch.input.addEventListener("keyup", (event) => {
  if (widget.events.addable && event.key === "Enter") {
    contentSearch.addable.main.click()
    contentSearch.input.value = ""
  }
})
```

**Comment by brianvoe** [comment]
If anyone wants to put a pr in for a fix they think will work that wont effect normal search I would be more than happy to look at it.
