### ISSUE TITLE
How to edit/remove search icon?

### ISSUE THREAD

**Issue by marbuser** [brianvoe/slim-select#231]
**Describe the bug**
How do I remove this blue cross icon? No offense but it's absolutely hideous (especially since it's blurry on newer monitors due to resolution) and after checking the docs for quite a while I can find no reference to it.

On top of that it doesn't appear to be any type of pseudo element on the input, so I can't even hide it with CSS.

Hopefully you can help.

**Screenshots**
![image](https://user-images.githubusercontent.com/34422459/88887401-eb0db100-d26e-11ea-8bf3-21bbc57a0f6c.png)

**Comment by brianvoe** [comment]
its an input field type="search". The browser add that. You would have to google search how to remove that via css
