### ISSUE TITLE
Feature Request: Set an option after SlimSelect is initialized

### ISSUE THREAD

**Issue by rafaelytakei** [brianvoe/slim-select#233]
Hi, I've read the documentation but couldn't find something like this:

I'd like to set the 'showSearch' option to true after initializing the SlimSelect with the option as false, so basically something like a method `element.slim.setOption({showSearch: true})` or `element.slim.setShowSearch(true)` , is it possible?

**Comment by brianvoe** [comment]
Sorry i dont have specific option sets to toggle after slim select has already run.
