### ISSUE TITLE
Slim select ajax doesn't work

### ISSUE THREAD

**Issue by crypcode** [brianvoe/slim-select#236]
**Describe the bug**
Hi I'am using slim select long time but never fetch data from ajax requests the problem is when i get data from ajax request i can't select any options and slim select just selects last value. How to fix problem?

`    new SlimSelect({
        select: '#knygaajax',
		placeholder: 'Pasirinkite knygą',
        searchingText: 'Ieškoma...', // Optional - Will show during ajax request
        ajax: function (search, callback) {
            // Check search value. If you dont like it callback(false) or callback('Message String')
            if (search.length < 0) {
                callback(false)
                return
            }

            // Perform your own ajax request here
            fetch('{{ url('knygos/data') }}')
                .then(function (response) {
                    return response.json()
                })
                .then(function (json) {
                    let data = []
                    for (let i = 0; i < json.length; i++) {
                        data.push({ text: json[i].pavadinimas })
                    }
                    console.log(data);
                    // Upon successful fetch send data to callback function.
                    // Be sure to send data back in the proper format.
                    // Refer to the method setData for examples of proper format.
                    callback(data)
                })
                .catch(function (error) {
                    // If any erros happened send false back through the callback
                    callback(false)
                })
        }
    })`

**Comment by LiamAird** [comment]
Try to add the value: json[i].slug as well - it helped me. 

```js
.then(function (json) {
                            let data = []
                            for (let i = 0; i < json.length; i++) {
                                data.push({text: json[i].name, value: json[i].slug})
                            }

                            // Upon successful fetch send data to callback function.
                            // Be sure to send data back in the proper format.
                            // Refer to the method setData for examples of proper format.
                            callback(data)
                        })
```

**Comment by crypcode** [comment]
Yes it worked, bur now problem is when i generate few selects with relationships. First two works great, but third doesn't it get's dat a from ajax but it selects some value and i can't change it what can be the problem?

**Comment by brianvoe** [comment]
New version of slim select has been released. If this is still an issue let me know and ill try to take care of it.
