### ISSUE TITLE
Multiple Dropdowns on a Page

### ISSUE THREAD

**Issue by jamalnasir** [brianvoe/slim-select#238]
I have many dropdowns on a page. And I need to use slimselect instead. But, slim select allows you only to bind itself in the following code.

            new SlimSelect({
                select: '#myselect'
            });

Which means, I have to loop through each and every dropdown to do that. If I use class instead of element id. It will only apply to the first dropdown. Is there any way to apply slimselect to dorpdowns with the following code?

```$('select').slimSelect();```

Also, that would be great if you implement the following way of getting the selected values from a dropdown.

``` $('select').selected() ```

And for the count

``` $('select').selectedCount(); ```

**Comment by brianvoe** [comment]
Currently because its class based and is used for functional purposes later if you want to call methods afterward it needs to be a single selection. Unfortunately the trade off of work needed to make your request work doesn't trump doing a simple for loop.
