### ISSUE TITLE
Hide disabled options

### ISSUE THREAD

**Issue by LucusWebsites** [brianvoe/slim-select#239]
Is it somehow possible to hide disabled options?

I am writing a filter, and some options may become disabled due to other active filters.

**Comment by LucusWebsites** [comment]
This is what I mean, I disabled SlimSelect here

![filter-options-disabled](https://user-images.githubusercontent.com/3696955/96226367-cd5d0780-0f92-11eb-86d6-b6770924ec21.gif)

**Comment by LucusWebsites** [comment]
Looks like it's more an issue that updating disabled options on the original select doesn't work.
I fixed it (for now) by destroying the instances and re-initializing them after the original selects are updated:

![filters](https://user-images.githubusercontent.com/3696955/96265949-5ccfde00-0fc6-11eb-8b49-d10abf27b97e.gif)

**Comment by brianvoe** [comment]
So their is a couple of ways to do it but what I would do is maintain the values of each selects selected values and use the set function to update the drops downs values with ones you want to show. Hope that helps
