### ISSUE TITLE
onOpen and onClose events

### ISSUE THREAD

**Issue by igorbumba** [brianvoe/slim-select#24]
Can you add onOpen (onBeforeOpen/onAfterOpen) and onClose (onBeforeClose/onAfterClose) events?
Currently, there are only beforeOnChange and onChange.

**Comment by brianvoe** [comment]
Sure. Can you give me some context on the issue you are solving just so i can ensure what i build facilitates that?

**Comment by igorbumba** [comment]
I need to fade some element on the site when opening drop-down (give opacity: 0.5 to elements using TweenMax). After closing, or clicking outside of drop-down elements needs to be shown again.

Also, I want to add a CSS class to the element on opening and closing. I know those child elements have opened class but clicked element doesn't.

Sometimes I need to add higher z-index to the drop-down element (mobile issue). I've attached some screenshots of this one.

Stacked mobile drop-down(s):
![slimselect-db-1](https://user-images.githubusercontent.com/11750417/35051489-a034d566-fba5-11e7-8338-4bd10802c188.png)

An issue with stacked mobile drop-down(s):
![slimselect-db-2](https://user-images.githubusercontent.com/11750417/35051532-bc4378d4-fba5-11e7-821e-681aef57def8.png)

**Comment by brianvoe** [comment]
Ok sounds good. When do you need this by? I can try to get this in today.

**Comment by igorbumba** [comment]
Oh god, no need to rush it. 😂 😂 

Whenever you have time for this one, I would be more than thankful!

**Comment by brianvoe** [comment]
Sounds good. Ill keep you update.

Thanks for submitting the issue

**Comment by brianvoe** [comment]
Om version 1.7.0. I added 

// Optional callbacks
beforeOpen: function () { console.log('beforeOpen')},
afterOpen: function () { console.log('afterOpen')},
beforeClose: function () { console.log('beforeClose')},
afterClose: function () { console.log('afterClose')}
