### ISSUE TITLE
Get selected text

### ISSUE THREAD

**Issue by danielissac** [brianvoe/slim-select#240]
How to get the selected text? Using slim.selected() I can able to get the selected value. I've tried like slim.selected('text') it gives the selected value only. I need to get the selected text.

**Comment by brianvoe** [comment]
If you have the selected value you can look up your own data. Maintain your data set somewhere you can iterate through it and get relative information based upon the selected value

**Comment by Todd1561** [comment]
What about situations where you're using the 'addable' feature?  In that case there would be no record of data elsewhere since it's new.

**Comment by patel33hardik** [comment]
https://stackoverflow.com/questions/3243476/how-to-get-multiple-select-box-values-using-jquery/55929605#55929605
