### ISSUE TITLE
ajax callback does not work without "value"

### ISSUE THREAD

**Issue by scf37** [brianvoe/slim-select#241]
**Describe the bug**
If ajax callback returns "text" without "value", HTML <option> renders with `value="undefined"`

**Screenshots**
![image](https://user-images.githubusercontent.com/1148465/98158666-5610f880-1eec-11eb-88d5-25e805ea45ff.png)

**Comment by brianvoe** [comment]
Not sure why someone would not pass a value. But if you want to submit a pr ill will be more than willing to take a look at a fix you have.

**Comment by scf37** [comment]
It is hard to tell what is the best solution.

slim-select used to work before without `value` field so it is breaking change. I can suggest either filling `value` from `text` or making `value` required by adding check to `validateOption()`.

**Comment by brianvoe** [comment]
New version of slim select has been released. If this is still an issue let me know and ill try to take care of it.
