### ISSUE TITLE
X button does not hide on deselect

### ISSUE THREAD

**Issue by scf37** [brianvoe/slim-select#242]
**Describe the bug**
select with allowDeselect=true does not hide X button on click because `this.main.selected()` returns `undefined` instead of `''`

**Screenshots**
![image](https://user-images.githubusercontent.com/1148465/98158998-e3ece380-1eec-11eb-9610-daf72514fc93.png)

**Comment by brianvoe** [comment]
Not sure i 100% follow. Can you paste a copy of the code your using and a screen shot please.

**Comment by scf37** [comment]
https://jsfiddle.net/uta364yf/15/

`X` button should not appear.

**Comment by scf37** [comment]
I believe the cause is that `value` is kind of required after latest changes but fake placeholder data object does not contain it.

Adding `value: ''` to lines like `var value = { text: '', placeholder: this.main.config.placeholderText};` seems to fix this issue.

**Comment by brianvoe** [comment]
Are you saying that if nothing is selected the X button shouldnt show?

**Comment by scf37** [comment]
Yes, at least that's how it is used to work. Look at the code above - it hides deselect button if nothing selected.

**Comment by scf37** [comment]
Found a fix: https://jsfiddle.net/4yvnupqc/1/
So it is probably documentation issue (or me misreading documentation)

**Comment by brianvoe** [comment]
Ok fair enough. I agree with what your pointing out. If you do a quick pr ill try to get it into the next release

**Comment by brianvoe** [comment]
New version of slim select has been released. If this is still an issue let me know and ill try to take care of it.
