### ISSUE TITLE
Selecting value from AJAX

### ISSUE THREAD

**Issue by dixpac** [brianvoe/slim-select#243]
I have large data set in select, by large I mean around 40k records.
To make it work I have implemented slim-select that behaves simmilar to seach autocomplete. Initially no results are populated when user starts typing I send new http request that returns only 30 results that match value in the search.

Something like this:

```js
 const newSelect = new SlimSelect({
      select: this.element,
      placeholder: this.element.dataset.placeholder,
      allowDeselect: true,
      ajax: function(search, callback) {
        if (search.length < 2) {
          callback('Need 3 characters')
          return
        }

        const searchUrl = `${url}?q=${search}`
        fetch(searchUrl).
          then(function(response) { return response.json() }).
          then(function(json) {
            let data = []
            for (let i = 0; i < json.length; i++) {
              data.push({ value: json[i].value, text: json[i].text })
            }

            callback(data)
          }).
          catch(function(error) {
            callback(false)
          })
```

This work like a charm on a new/create form. But issue I've is with edit form.
When form edit renders I don't have any results preloaded(which is understandable since results are populate thorough AJAX on search).

Did anybody manage to solve this issue? How can I select saved value on the form edit when using this kind of select ajax?

Thanks

**Comment by dixpac** [comment]
I manage to resolve issue but it is a bit hacky.

I have an endpoint for selects for example: `/autocompletable/locations`, that endpoint can be searched in 2 ways:

1.  `/autocompletable/locations?q=[search]` - performs search
2. `/autocompletable/locations?ids=[values]` - search only by `ids`.

When edit form opens and if form field has value assignet ex : `form.location_id  => 1`, I hit 2nd enpoint and populate and select only that value:

```js
  configureLazySelect(url) {
    const newSelect = new SlimSelect({
      select: this.element,
      placeholder: this.element.dataset.placeholder,
      allowDeselect: true,
      ajax: function(search, callback) {
        if (search.length < 2) {
          callback('Need 3 characters')
          return
        }

        const searchUrl = `${url}?q=${search}`
        fetch(searchUrl).
        then(function(response) { return response.json() }).
        then(function(json) {
          let data = []
          for (let i = 0; i < json.length; i++) {
            data.push({ value: json[i].value, text: json[i].text })
          }

          // Upon successful fetch send data to callback function.
          // Be sure to send data back in the proper format.
          // Refer to the method setData for examples of proper format.
          callback(data)
        }).
        catch(function(error) {
          // If any erros happened send false back through the callback
          callback(false)
        })
      }
    })

    if (this.data.has("value")) {
      const initialUrl = `${this.data.get("url")}?id=${this.data.get('value')}`

      fetch(initialUrl).
      then(response => response.json()).
      then(data => {
        if (newSelect.config.isMultiple) {
          newSelect.setData(data)
        } else {
          newSelect.setData(data)
          newSelect.set(data[0].value.toString())
        }
        }
      )
    }
  }
```


👆 not refactored code but it seems to be working.

**Comment by rammanoj** [comment]
Hi @dixpac 

Aren't you loading the values from server if the search results have more than 30 entries ?

**Comment by dixpac** [comment]
Hey @rammanoj
Can you expand a bit, I don't understand your question fully?

**Comment by rammanoj** [comment]
Thanks for reply @dixpac 

Let's suppose 500 out of 40k records matched the substring you searched. From, the comments, I understand that you are only displaying the first 30 of the 500. Aren't you not showing the remaining at all ? or did you implement progressive loading ?

**Comment by dixpac** [comment]
Gotcha!

Yeah I limit responses from the server usually between 5-50. Didn't implement progressive loading since it was not necessary for my use-case, but yeah I can see how that could be an issue for super large result sets where you have similar entries

**Comment by brianvoe** [comment]
New version of slim select has been released. If this is still an issue let me know and ill try to take care of it.
