### ISSUE TITLE
slimselect overwrites style position

### ISSUE THREAD

**Issue by Ian-Ro** [brianvoe/slim-select#245]
I have a complex form with many selects, where all the positions are all defined in the css. When I add slimselect, the original positions are ignored. I cannot alter the css because the it is automatically created by Webbuilder. Is there anyway for slimselect to default to leave the original position as a higher specificity? (Even though I cannot alter the master css, even trying !important does not seem to work)

 A simple code to show the problem is shown below:

    <body onload= "Main()">
    <select id="my_MSD" multiple>
	     <option value="value 1">Value 1</option>
	     <option value="value 2">Value 2</option>
        <option value="value 3">Value 3</option>
    </select>
    <style>
    #my_MSD
    {
       position: absolute;
       left: 76px;
       top: 150px;
       width: 400px;
       height: 33px;
    }
    </style>
    <script>
    function Main (){
	    new SlimSelect({
                    select: '#my_MSD',
                });
    	    }		
    </script>
    </body>

![Screenshot_2020-11-13 Screenshot(1)](https://user-images.githubusercontent.com/74424861/99103476-871db700-25d7-11eb-97fb-05b0a8cd289d.png)
![Screenshot_2020-11-13 Screenshot](https://user-images.githubusercontent.com/74424861/99103495-8e44c500-25d7-11eb-997e-b98b0f8a10ea.png)

**Comment by brianvoe** [comment]
So this doesnt look to be a slim select issue. This looks to be just a css conflict. It could be anything from whether or not to use an id for the css or to use a class to override. It could be a matter of an order of loading the css that could be the issue. and if you have a bunch of other slim selects it could be a hand full of other possibilities. I would suggest trying to better understand how your css is loaded and research the best way to deal with your css situation.

Hope that helps. Thanks.

**Comment by Ian-Ro** [comment]
Thanks for responding

In case anyone else has a similar problem, I have documented a workaround that seems to be needed, because slimselect seems to zero out all the values of offsetTop, offsetHeight etc of the select.

    function slimSelectSet(dropDownObject){
    dropDownObject.style.top = String(dropDownObject.offsetTop)+"px";
    dropDownObject.style.left = String(dropDownObject.offsetLeft)+"px";
    dropDownObject.style.height = String(dropDownObject.offsetHeight)+"px";
    dropDownObject.style.width = String(dropDownObject.offsetWidth)+"px";
    dropDownObject.style.position = 'absolute';
    new SlimSelect({
    select: dropDownObject
    })
