### ISSUE TITLE
Installation page not finding slimselect installation js and css files (file not found)

### ISSUE THREAD

**Issue by Ian-Ro** [brianvoe/slim-select#247]
On slimselectjs.com/install, the Download button does not work and also
https://cdnjs.cloudflare.com/ajax/libs/slim-select/1.26.1/slimselect.min.js  gives “file not found” although it finds 1.26.0

**Comment by brianvoe** [comment]
Sorry for the issue. Sometimes the cdn takes a bit of time to kick in. Ill look into it though. Thanks.

**Comment by Ian-Ro** [comment]
Brian

 

No problem. I was just letting you know. However, the Download button did
not work even before the update to 26.1. (I think that is a different
problem)

 

Thanks for your great work and this plugin.

 

Best Regards

 

Ian Robson

 

 

  _____
