### ISSUE TITLE
in 1.26.2, the ajax not woking.

### ISSUE THREAD

**Issue by krokovicsmate** [brianvoe/slim-select#251]
Always get an error when callback is called with data:
`Uncaught (in promise) TypeError: Cannot read property 'placeholder' of undefined`

I tested with the ajax example code too, same error occured. 

Rollback to 1.26.1 and working fine.

**Comment by brianvoe** [comment]
I need a jsfiddle example to better replicate the error.

**Comment by krokovicsmate** [comment]
`https://jsfiddle.net/t8w7dfsz/1/`

You can see in the console log error.

**Comment by Naumov1889** [comment]
same problem

**Comment by MR-Mostafa** [comment]
Hi
I have the same problem in the latest version (1.27.0)
[https://jsfiddle.net/v7bse6fc/4/](jsfiddle)

To view the error:
- First search for ‍`Leanne` and select the option found.
- Then click `select box' again and search for a new phrase such as `test`.
- An `TypeError: Cannot read property 'placeholder' of undefined` error is displayed on the console

**Comment by gathuku** [comment]
@MR-Mostafa were you able to resolve this, am also getting the same error.

**Comment by aguilera51284** [comment]
this still dont working :(!

**Comment by brianvoe** [comment]
New version of slim select has been released. If this is still an issue let me know and ill try to take care of it.
