### ISSUE TITLE
esm module not importable in browser

### ISSUE THREAD

**Issue by kapouer** [brianvoe/slim-select#252]
Hi, when working in a development environment it's common to
```
import SlimSelect from "/node_modules/slim-select/dist/slimselect.js";
```
(allowing node_modules to be served as static files, or better, using some server like https://github.com/marijnh/esmoduleserve,
that changes paths of sub-imports.

However when doing so:
> Uncaught SyntaxError: The requested module '...' does not provide an export named 'default'

because the current bundling system cannot support both require and imports.
Usually a distinct build for esm is required, and a specific field need to be declared in package.json
(either exports or module).

See also a project like https://github.com/flatpickr/flatpickr where they build specific dist/esm files.

Thanks !

**Comment by brianvoe** [comment]
Submit a pr for the change and ill take a look at it.

**Comment by kapouer** [comment]
I can't ! Internet is bad here and i can't even download webpack.
Anyway webpack doesn't support output to esm format.
Rollup does, though, but that's too much of a change for a PR.

**Comment by brianvoe** [comment]
Maybe in my next major version release ill try rollup and see if that works better for me
