### ISSUE TITLE
valuesUseText=true not working

### ISSUE THREAD

**Issue by Vakaras1** [brianvoe/slim-select#253]
According to the example, lets see the following line:
`{innerHTML: '<i>Slim Select you are awesome</i>', text: 'Slim Select awesome'}`
When the "valuesUseText" is true, I expect to see the selected value "Slim Select awesome", but I see full text without Italic. 

What's the purpose of the "text" value, if it is ignored?

**Comment by brianvoe** [comment]
New version of slim select has been released. If this is still an issue let me know and ill try to take care of it.
