### ISSUE TITLE
Disabled multi-selects can have their options removed

### ISSUE THREAD

**Issue by CoffeeKing68** [brianvoe/slim-select#255]
**Describe the bug**
If you call select.disable() and you have options (multi-seclect) selected, they can be removed still.

**Reproduce the bug**
Go to http://slimselectjs.com 
- methods 
- disable/enable 
- enable the selects 
- add some options to multi select
- disable
- remove options in multi-select

Thanks
CoffeeKing68

**Comment by brianvoe** [comment]
I see the issue. I going to see if i can get a quick fix in

**Comment by brianvoe** [comment]
New version of slim select has been released. If this is still an issue let me know and ill try to take care of it.
