### ISSUE TITLE
3 minor issues: poor accessibility, group+multiselect not working, allowDeselect+multiselect

### ISSUE THREAD

**Issue by netrules** [brianvoe/slim-select#256]
**Describe the bug**
1. **Accesibility**: when using `addable`, (ability to dynamically add options via the search input field), one should be able to proceed with tag+enter, or just pressing enter. For reference, please look at [this other](https://joshuajohnson.co.uk/Choices/) (it is abandoned for 1 year almost) effort with the same purpose as this project, and look at the behavior when adding a new chip/term/tag:
![add new choice in other library](https://user-images.githubusercontent.com/48886164/105786498-f3178680-5f5b-11eb-81b1-c3cf5c136e51.png)
2. **Group + MultiSelect present buggy behavior**: can't use both groups and multiselect, when adding one of the options from a group, it will take the first group option and not any of the options. 
![image](https://user-images.githubusercontent.com/48886164/105786605-29ed9c80-5f5c-11eb-9ce5-6626b3760f4f.png)
However, it does work in your website but not when I tried it with the latest cdn version (1.27.0)
![example of group and multiselect](https://user-images.githubusercontent.com/48886164/105786642-3d006c80-5f5c-11eb-813d-ae2707c285be.png)
It just doesn't work the way it should with groups.
3. **allowDeselect + MultiSelect doesn't work at all**: as per described, should be able to mix both of these as a "`reset`" all incurring selections, or a remove all choices, but I have to delete them one by one. That is not very efficient-- I could, however, add a button to do it programatically.
![delete search button](https://user-images.githubusercontent.com/48886164/105786786-7f29ae00-5f5c-11eb-8790-154091182b54.png)
![search ui instead](https://user-images.githubusercontent.com/48886164/105786900-abddc580-5f5c-11eb-9baa-8df66c260da5.png)

**Screenshots**
Add screenshots to help explain your issue. If you do not submit at least an image or animated gif I most likely wont look into it.

**my website**:
https://sgonzalez.tech/portfolio/

**edit**
4. **integrity check for cloudflare symlink**?
![image](https://user-images.githubusercontent.com/48886164/105789313-f82b0480-5f60-11eb-80a6-94253397e10c.png)
`<script src="https://cdnjs.cloudflare.com/ajax/libs/slim-select/1.27.0/slimselect.min.js" integrity="sha384-/hEMVznvyx6pEFW94sh/jbsWKK7m9yrpAb00Lzd8LnNOdHkNRDMpdItAMjUHX/rF" crossorigin="anonymous"></script>`

**Comment by brianvoe** [comment]
I appreciate the issues submission. I am currently working the next version of slim select and have decided to put my efforts in that direction. So unfortunately i wont be updating this current version.

**Comment by netrules** [comment]
@brianvoe That is ok. Let me know if I may be of any further help, should you need any future maintainers or contributors.
