### ISSUE TITLE
A way to give a name to hidden select so we can submit it from a form

### ISSUE THREAD

**Issue by DelahayJoann** [brianvoe/slim-select#257]
I did not find how to add a name attribute to the hidden select created (by new SlimSelect) to be part of a form submit. I tried everything possible but i don't want to use JQuery. Is there a parameter to add next to select: to set a name?
![image](https://user-images.githubusercontent.com/70022234/106272659-ad93db80-6231-11eb-9b0c-25debcf7647d.png)
![image](https://user-images.githubusercontent.com/70022234/106272763-dc11b680-6231-11eb-879d-ddc4735656b6.png)

**Comment by brianvoe** [comment]
Thats a good question. Are you not able to just add the name to your select itself? Why do you need slim select to do it?
