### ISSUE TITLE
Multiselect with 'hideSelectedOption: true' can be opened, when all options are selected

### ISSUE THREAD

**Issue by chofmann98** [brianvoe/slim-select#258]
**Describe the bug**
With the config `hideSelectedOption: true` and `showSearch: false` the dropdown can still be opened, when all options are already selected. The dropdown then is empty, but it still shows a small part of the dropdown box.
A similar issue appears if you use that config together with `closeOnSelect: false`. Then the dropdown stays open, even if all options are hidden.

**Screenshots**
When the dropdown is closed:
![image](https://user-images.githubusercontent.com/22192529/108381092-c4619880-7207-11eb-83ad-c3d62fd01dee.png)

When the dropdown is opened, but all options are selected and therefore hidden (see the small bit of the dropdown box at the bottom):
![image](https://user-images.githubusercontent.com/22192529/108381168-d80cff00-7207-11eb-9c76-557ab756be5d.png)

**Comment by brianvoe** [comment]
Thanks for you issue submission. I am not currently making any additional updates to this version of slim select because I am working on the next major version. If you are able to create a pr to fix your issue I would be willing to merge that in. Thanks.
