### ISSUE TITLE
Getting a selected value

### ISSUE THREAD

**Issue by suethedeveloper** [brianvoe/slim-select#26]
Hello there,

I'd like to use slim select for my dropdown component. 
Is there any way to get selected value(s) for single/multiple dropdown? I don't see have method that I can call to get the values. 
How can I get selected values?

**Comment by brianvoe** [comment]
Oh thats interesting. So i use Vue for most of my projects and i normally bind the original select to get the values. Should be really easy to add. Ill add a method you can call to get the value(s). Ill let you know when its done.

If you like the package could you star it? It really helps get the word out about it.

Thanks!

**Comment by suethedeveloper** [comment]
Do you mind giving a simple example how you use it with vue?

**Comment by Vineetpal468** [comment]
Hey brianvoe, is there any way to show pre selected value in Slim-select (like on a edit page)  ?????

**Comment by brianvoe** [comment]
@Vineetpal468 Can you help me understand a little better what you are talking about? Not sure what you mean by preselected value.

I have a callback that will give will give you the selected value before it is set. beforeOnChange http://slimselectjs.com/options

**Comment by brianvoe** [comment]
@suethedeveloper 

```
<script>
  import SlimSelect from 'slim-select'

  export default {
    data () {
      selectValue: ''
    }
  }
</script>
<template>
  <div>
    <select id="mainSelect" v-model="selectValue">
      <option value="value 1">Value 1</option>
      <option value="value 2">Value 2</option>
      <option value="value 3">Value 3</option>
    </select>
  </div>
</template>
```

**Comment by brianvoe** [comment]
You can also use the onChange callback to get the values when the select has changed.

**Comment by brianvoe** [comment]
Ill still add the selected value as well.

**Comment by brianvoe** [comment]
I added a method called selected() and that will return either a string or an array of string of the currently selected values http://slimselectjs.com/methods. v1.9.0

Let me know if that works for you.

Thanks for pointing this out!

P.S. @Vineetpal468  Give it a star! 😄
