### ISSUE TITLE
Prevent default closing action

### ISSUE THREAD

**Issue by jmarsh24** [brianvoe/slim-select#262]
Currently slim -select offers the ability to run actions on before-close, before-open, after-close and after-open. I would like to propose a feature that it provided by the select2 library which would allow the user to prevent the default actions of Closing. So by default the select2 would be open by default. This would be useful for scenarios where the developer would like to have a multi select column browser.

I have an example here tangotube.tv

if you click on the filters section you will see the functionality built with slim-select.

However if you look in the console logs, the functionality is achieved by raising an exception before close by calling a preventDefault() on a non existing event. 

This causing the select not to close the dropdown, but does so in a broken way. I’m proposing that an event option be giving to the developer to prevent it.

**Comment by brianvoe** [comment]
Thanks for submitting something I think is a good catch. Right now I am working on v2 of this package and am not putting anymore work on this version at the moment. If you have a pr for your fix I am more than willing to merge it in.

Thanks and nice job on the site so far.

**Comment by jmarsh24** [comment]
I would love to, unfortunately I don't know JavaScript. This is my first website so far.
