### ISSUE TITLE
Is npm-check correctly a dependency?

### ISSUE THREAD

**Issue by grk** [brianvoe/slim-select#263]
It looks like perhaps it was added to dependencies instead of devDependencies. Because of that, slim-select is pulling behind a ton of dependencies when added to a project.

**Comment by Neunerlei** [comment]
I was thinking the same, while installing the script. 172 dependencies is a lot for a select box :D

**Comment by Neunerlei** [comment]
@grk If you downgrade to version: "1.26.2" you should still get the current features, without having to install npm-check :)

**Comment by brianvoe** [comment]
New version of slim select has been released. If this is still an issue let me know and ill try to take care of it.
