### ISSUE TITLE
How to access option to change value ?

### ISSUE THREAD

**Issue by TheoSrz69** [brianvoe/slim-select#266]
**Describe the bug**
In documentation, I see this for instanciate the slim-select object : 
```
// If you already have a created slim select you can select your div
// and continue to use slim select off of the element using the .slim data value
let el = document.querySelector('.element .you #want')
el.slim.open() // Or any other options/methods
```

It's ok with methods, but options are mentioned. For some of my select elements , I would like to change the "showSearch" value. Is it possible ? If yes, how ?

I tried 
`el.slim.showSearch = false;`
and
`el.showSearch = false;`
with no success.

Thanks for your help (and sorry for my broken english).
Regards,

Sylvain

**Comment by brianvoe** [comment]
New version of slim select has been released. If this is still an issue let me know and ill try to take care of it.
