### ISSUE TITLE
Can't set data if the select is AJAX and selected

### ISSUE THREAD

**Issue by jbiancat** [brianvoe/slim-select#267]
Sometimes, I need to set the options of my single select without using the search. If my select has selected option and it is an AJAX SlimSelect, i can't use setData to put my fetched options.

I've got an error : TypeError: t[s] is undefined
In slimselect.js (l. 738-763)

**Comment by brianvoe** [comment]
New version of slim select has been released. If this is still an issue let me know and ill try to take care of it.
