### ISSUE TITLE
 Package path ./dist/slimselect.css is not exported from package "\node_modules\slim-select\package.json""

### ISSUE THREAD

**Issue by paradoxe35** [brianvoe/slim-select#269]

**Comment by stefan-lacatus** [comment]
Are you using Webpack 5? This seems to be the root cause: https://github.com/webpack/webpack/issues/9509

A new release is needed where the package.json also exposes the css files as "exported"

**Comment by paradoxe35** [comment]
except using copy-webpack-plugin i couldn't find any other way around it

**Comment by bachy** [comment]
i have this problem to, css are not loaded with js, the slim select are not styled.
and if i try to import slim-select's css via ```import 'slim-select/dist/slimselect.min.css'``` on my main.js i have the same error
```
Module not found: Error: Package path ./dist/slimselect.min.css is not exported from package /app/node_modules/slim-select (see exports field in /app/node_modules/slim-select/package.json)
```
no way neither to import the scss from my sass files ```@import '~slim-select/slimselect.css';```
```
SassError: File to import not found or unreadable: ~slim-select/src/slim-select/slimselect.scss.
```

i tried to modify the slim-select package.json without success so far 
```json
"exports": {
    ".":{
      "require": "./dist/slimselect.min.js",
      "import": "./dist/slimselect.min.mjs"
    },
    "style": "./dist/slimselect.min.css",
    "sass": "./src/slim-select/slimselect.scss",
    "./src/": "./src/",
    "./dist/": "./dist/"
  }
```

**Comment by bachy** [comment]
> except using copy-webpack-plugin i couldn't find any other way around it

could you elaborate on your solution with copy-webpack-plugin please ?

**Comment by bachy** [comment]
with 
```json
"exports": {
    ".":{
      "require": "./dist/slimselect.min.js",
      "import": "./dist/slimselect.min.mjs"
    },
    "./slimselect.min.css": {
      "require": "./dist/slimselect.min.css",
      "import": "./dist/slimselect.min.css"
    }
  }
```
i can import css
made a PR #271

**Comment by paradoxe35** [comment]
I removed exports key from slim-select package.json, and it works

**Comment by paradoxe35** [comment]
> > except using copy-webpack-plugin i couldn't find any other way around it
> 
> could you elaborate on your solution with copy-webpack-plugin please ?

remove exports section from slim-select package.json

**Comment by timdk** [comment]
@brianvoe can you comment on why https://github.com/brianvoe/slim-select/pull/271 was rejected? 

Is it because target branch was master instead of develop, or another reason?

**Comment by timdk** [comment]
I have been testing a global export from `dist` in addition to the current values

```
  "exports": {
    ".": {
      "require": "./dist/slimselect.min.js",
      "import": "./dist/slimselect.min.mjs"
    },
    "./dist/": "./dist/"
  },
```

This seems to fix the broken imports from scss files

```
@import '~slim-select/dist/slimselect.min.css';
```

I can open a PR if this is an acceptable fix.

**Comment by brianvoe** [comment]
I suppose i dont fully follow the issue. Why do most other people not have this issue? Do you have an example comparison of another package that i can look at for reference?

**Comment by timdk** [comment]
I encountered the issue only when I upgraded my toolchain to webpack 5 and upgraded Slim Select to 1.27.0 from 1.26.0.

It's mentioned in the issue on webpack's repo (linked above in stepha-lacatus's comment) https://github.com/webpack/webpack/issues/9509#issuecomment-592612932
> An important note here: once the exports field is specified, it should be impossible to import any subpath that is not explicitly specified in the field.

So the combination of adding the exports field in v1.27 and upgrading webpack caused it for me. I downgraded to v1.26 until I had time to look closer.

For what it's worth bachy's solution didn't work for my use case. Based on the docs here https://webpack.js.org/guides/package-exports/#reference-syntax maybe it would have worked if I added `sass` and `css` keys in addition to `require` and `import`, but given the `dist` directory is for the bundles I think it's OK to add that to exports.

I had a look around at a few open source repos and I'm struggling to find any that have `exports` defined in `package.json`.

**Comment by dpilafian** [comment]
@brianvoe While trying to resolve a **webpack** build issue in an unrelated package, I encountered the same CSS **_"is not exported from package"_** error.

In case it's helpful, here's the background:
https://github.com/center-key/pretty-print-json/issues/53

I ended up going with:
```json
"./": "./dist/"
```
because the resulting `@import` statement is cleaner.

@timdk Thanks for the code!

**Comment by Epskampie** [comment]
I just made a symlink: `ln -s ../node_modules/vendor/slim-select/slimselect.min.css' .`.

After that you can `import './slimselect.min.css'`.

**Comment by brianvoe** [comment]
New update coming soon. Not sure if this is still an issue but if it pops up again after the update we can reopen this.

**Comment by glaszig** [comment]
yes. still an issue. specifically with webpack 5. without proper `exports` config in package.json it'll not find any module and complain about missing exports.

see https://webpack.js.org/guides/package-exports/

**Comment by brianvoe** [comment]
All the build process stuff is the most frustrating thing in the world. Please submit a pr and ill merge it in if you think you have an update that will help "fix" this

**Comment by glaszig** [comment]
> the most frustrating thing

indeed it is.

i'll see what i can do. for everybody else i guess it's something similar to hotwired/stimulus#569. only need to figure out how to treat all the other exports...

**Comment by AdiDD** [comment]
I found a workaround for this, by doing the import in a `css` file that I was using, with `@import url('/node_modules/slim-select/dist/slimselect.css');` instead of doing it in the `js` file.

**Comment by marko-hologram** [comment]
In case someone else lands here with this issue while migrating from some older version to this or from lack of documentation on this particular part. Code I added here seems to have been added in v2.5.1 so make sure to have at least that version https://github.com/brianvoe/slim-select/commit/6dbd0b5d88ed7251864dc8e9ba553695e0554e93

I'm using latest (as of now) v2.6.0 and I managed to import styles using this import statement:

```js
import "slim-select/styles";
```

Discovered this by checking out the package.json for this project and exports field declares this:

```json
"exports": {
  ".": {
    "require": "./dist/slimselect.umd.js",
    "import": "./dist/slimselect.es.js"
  },
  "./styles": "./dist/slimselect.css"
},
```

So doing `/styles` import will actually import `/dist/slimselect.css`.

**Comment by glassum** [comment]
Today I met some nested .ts modules and internal `import "slim-select/styles";` didn't compile. But
`require("slim-select/styles");`

did well.
