### ISSUE TITLE
On Load callback

### ISSUE THREAD

**Issue by rctneil** [brianvoe/slim-select#272]
Hey,

Is there an event that can be called when Slim Select has loaded and initialised.   I am hitting an issue where people are interacting with the multi select before Slim Select has initialised on it and taken it over.

I'm hoping to hide the native box and then show it when slim select has loaded fully.

Neil

**Comment by brianvoe** [comment]
New version of slim select has been released. If this is still an issue let me know and ill try to take care of it.
