### ISSUE TITLE
Making Select Field Required

### ISSUE THREAD

**Issue by ATOPBIO** [brianvoe/slim-select#273]
Hello, when using slim-select with a required <select> attribute no error will display in the browser and the form will not submit without showing any message.

Is there a workaround for this?

**Comment by ChipRyan** [comment]
Having the same issue

**Comment by demmmmios** [comment]
Try this one

```
select[data-ssid] {
  pointer-events: none;
  opacity: 0;
  display: flex !important;
  position: absolute;
}
```

**Comment by columbian-chris** [comment]
This should be added to the core stylesheet.

**Comment by bennpham** [comment]
To add on top of this:

Is it possible for `slim-select` to just use `opacity: 0` on the select input field rather than set `style=display:none`? I notice I'd have to set 

```
.ss-main {
  display: flex !important;
};
```

on top of @demmmmios solution here in the case where I call an AJAX request (using HTMX) to change the content inside of the select options so the `ss-main` doesn't disappear after loading the new DOM content.

**Comment by demmmmios** [comment]
I think this project is no longer in development, or maybe i am wrong, but look on issues and last release tag :(

**Comment by brianvoe** [comment]
Hey everyone. Sorry for not replying on this. I released a new version of slim select. As for this issue. Slim select does add display none to the original select. I cant say that just setting the opacity to 0 would be a better option. That being said, once you initiate SlimSelect there is a function couple layers deep you can call. 

```
var slim = new SlimSelect({})
slim.render.showUI()

// Then you can add whatever style you want to it.
```

Hope this helps. Check out the new version and let me know your thoughts.

**Comment by dkniffin** [comment]
In the updated version of slim-select, the workaround doesn't work anymore, so I updated it. This version seems to work now:

```
select[data-id^="ss-"] {
  pointer-events: none;
  opacity: 0;
  display: flex !important;
  position: absolute;
  bottom: 0;
  height: 0px;
}
```

That said, @brianvoe it would be nice if slim-select had built-in validation support. Maybe you could leverage the JS Validity API for that? 🤷‍♂

**Comment by brianvoe** [comment]
Always open to pr's if you have an idea of improvements.

**Comment by reformed** [comment]
See my answer [here](https://github.com/brianvoe/slim-select/issues/578#issuecomment-4639953009) for a possible solution.

**Comment by brianvoe** [comment]
this feature has already been added. you can use requireds
