### ISSUE TITLE
Result values from ajax display selected values on page load

### ISSUE THREAD

**Issue by alicankablan** [brianvoe/slim-select#274]
I am loading data via ajax I use autocomplete.I have selected data in my uri in codebehind too. But how can I show selected values I try but not working.

I think selected is missing like mandatory or display..

Try to use this code 
displaySelect.set(['A', 'C'])

`slim = new SlimSelect({
                select: '#multiple',
                closeOnSelect: false,
                searchText: 'Aradığın Bölüm Mecut Değil!',
                searchPlaceholder: 'Arama Yap',
                placeholder: 'Tıp,Hukuk,Mühendislik vb..',
                placeholderText: 'Tıp,Hukuk,Mühendislik vb..',
                searchingText: 'Aranıyor...', // Optional - Will show during ajax request
                ajax: function (search, callback) {
                    // Check search value. If you dont like it callback(false) or callback('Message String')
                    if (search.length < 3) {
                        callback('En Az 3 Karakter Girilmeli');
                        return;
                    }
                    $.ajax({
                        type: 'POST',
                        cache: false,
                        async: true,
                        url: '@FrSettings.Settings.AppVirtualPath' +'Universite/SearchUniByYuksekVeLisansAjax',
                        data: SetAjaxModel(search),
                        headers: {
                            '__RequestVerificationToken': GetAntiForgeryToken()
                        },
                        success: function (data) {
                            var datas = [];
                            for (var i = 0; i < data.length; i++) {
                                datas.push({ value: data[i].Val ,text: data[i].Val + '(' + data[i].Count+')' });
                            }
                            callback(datas);
                        },
                        error: function (xhr, ajaxOptions, thrownError) {
                            callback(false);
                        }
                    });`

**Comment by brianvoe** [comment]
Not sure if this is still an issue for you. The new version of slim select came out and maybe it may have tackled your issue. Check it out and let me know.
