### ISSUE TITLE
How to make `addable` wait?

### ISSUE THREAD

**Issue by heraldofsolace** [brianvoe/slim-select#277]
I have a slim-select field for adding categories to a post. When the user click on the add button, I want to display a modal where they can add a new category which will then be added to the select.  Here is what I have so far - 

```javascript
addable: function(value) {
    modal.show()
    // Form is a form inside the modal to add the new category
    form.addEventListener("submit", function(e){
        Rails.ajax({
            ...,
            success: function(response) {
                 // Want to return from here
                 return { value: response.id, text: response.name }
            }
        })
    })
} 
```
Clearly it doesn't work as I have to return from the `addable` function. Any idea what should be done?

**Comment by ontelo** [comment]
Did you ever solve this? I'm facing the same issue.

**Comment by brianvoe** [comment]
New version of slim select was just released. Not sure if this is still an issue for you. If the new version doesnt fix your issue, let me know and ill see what i can do to help. Thanks.
