### ISSUE TITLE
Preserve selection when back button is used after submitting form with SlimSelect

### ISSUE THREAD

**Issue by tomekit** [brianvoe/slim-select#278]
I am using SlimSelect in the HTML form that users submit to end up on a different filtered page. Now if I click back button I will end up again on page where SlimSelect is present, however all of the selections are gone. 
Is there any way to preserve the selections?

**Comment by brianvoe** [comment]
Not 100% sure your issue. But the new version of slim select came out and maybe it fixed that issue for you. Check it out and let me know.
