### ISSUE TITLE
Check if the select will open above or below

### ISSUE THREAD

**Issue by mikem33** [brianvoe/slim-select#279]
Hi. I wonder if there is a way to check if the select will open above or below to add a CSS class to an upper container in the beforeOpen config. 
I have a problem with a fixed header on the site I am developing. There is a select at the beginning of the page that is close to the header when I haven't scrolled yet. If you open the select when you haven't scrolled, the content appears above. I thought of set a CSS class when you open the select but if you scroll then a little bit and the select opens below, the container overlaps the fixed header.

![screenshot](https://user-images.githubusercontent.com/2436815/116420193-0cbbb900-a83e-11eb-8c7f-1f635af81f23.png)

**Comment by brianvoe** [comment]
New version of slim select is out. Sorry for the delay on your question. In the new slim select version you can update the class .ss-open-below and .ss-open-above. those are the classes that get applied when it opens in certain directions.

Let me know if you can check out the new version and see if it does everything you need. Thanks!
