### ISSUE TITLE
List does not scroll to set value

### ISSUE THREAD

**Issue by macfire** [brianvoe/slim-select#28]
The list of select options does not scroll to new value when using `myselect.set(value)` or when using option `allowDeselect=true`.

My use case has about 40 options.  The first option is a default which has an empty string value. 
When I reset my form, I call `myselect.set("")` to reset the slimselect, as well.   

The result is that the visible part of slimselect shows the first item correctly, but when opening the dropdown, the scroll position remains at previously selected value ... which could be at bottom of list.

**Comment by brianvoe** [comment]
That is an interesting issue. Ill look into that and get it fixed asap.

Thanks for reporting this!

**Comment by brianvoe** [comment]
Hey so i updated the dropdown to auto scroll to the location of the selected option when opening the dropdown list. v.1.11.0

Let me know if this works for you.

Thanks.

**Comment by macfire** [comment]
Yes, the update works. Thanks for fixing.

**Comment by brianvoe** [comment]
No problem. Let me know if there is anything else i can do.
