### ISSUE TITLE
innerHTML combined with ajax display no results

### ISSUE THREAD

**Issue by tomekit** [brianvoe/slim-select#283]
I use AJAX searching:
```
new SlimSelect({
    select: '#multiple',
    searchingText: 'Searching...',
    ajax: function (search, callback) {
  
        if (search.length < 3) {
            callback('Need 3 characters')
            return
        }
        fetch('/substance/search?search='+search)
            .then(function (response) {
                return response.json()
            })
            .then(function (json) {
                let data = []
                let substances = json.results.substances;
                for (let i = 0; i < substances.length; i++) {
                    data.push({value: substances[i].id, text: substances[i].name})
                }
                callback(data)
            })
            .catch(function (error) {
                callback(false)
            })
    }
})
```
it works fine, but once I try to add the `innerHTML` (to render custom rows format) like this:
`data.push({value: substances[i].id, text: substances[i].name, innerHTML: '<div style="border: solid 1px #666666;">Border</div>'})`

any time when I search I get `No Results`, despite there are plenty. Is there any reason that once `innerHTML` gets added there it breaks the SlimSelect?

![Screenshot from 2021-05-09 21-45-29](https://user-images.githubusercontent.com/7759113/117584918-f4864c80-b10f-11eb-8569-93e0005faaed.png)

**Comment by brianvoe** [comment]
New version released today! Check it out and if you still have an issue let me know.
