### ISSUE TITLE
Ajax with minimal search length

### ISSUE THREAD

**Issue by tomvanlamoen-bookerz** [brianvoe/slim-select#287]
In the ajax option, also on the demo page (https://slimselectjs.com/options) in the search field 'Search "Graham"':

1. When you search for 'gra' > You get results
2. Remove the 'a' > You get 'Need 3 characters'
3. Add the 'a' again > You don't get any results

I dug into the code and I believe that this was caused by the following code
```
SlimSelect.prototype.search = function (value) {
if (this.data.searchValue === value) {
    return;
}
```
This is because the this.data.searchValue value still is 'gra'.

**Comment by Pathologic** [comment]
I've fixed this quickly:
```
SlimSelect.prototype.search = function (value) {
this.data.searchValue = ''; //fix
if (this.data.searchValue === value) {
    return;
}
```

**Comment by brianvoe** [comment]
New version released today! Check it out and if you still have an issue let me know.
