### ISSUE TITLE
Text input field does not displayed if user double click on the dropdown.

### ISSUE THREAD

**Issue by igormazurenko** [brianvoe/slim-select#29]
This issue happens for the IE11 and MS Edge users.
STR:
- double click on the dropdown 
- pay attention that cursor started blinking under the dropdown
- type some text, cursor will be moving, but text is not visible
- click on the dropdown and you will see text that you entered

**Comment by brianvoe** [comment]
Hey Igor,

Thanks for noticing this. This was a bit of a weird ie bug. I tackled it by blurring the input field when the content is closed and disallowing searching when the content is closed. This should fix your issue.
v1.11.1

Thanks for pointing this out!
