### ISSUE TITLE
Cannot unselect using keyboard

### ISSUE THREAD

**Issue by claudiu-cristea** [brianvoe/slim-select#290]
**Describe the bug**

I can use only the keyboard to select options but I cannot unselect them with the keyboard.

**Comment by brianvoe** [comment]
New version released today! Check it out and if you still have an issue let me know.

**Comment by tibi2303** [comment]
it's still not working

**Comment by tibi2303** [comment]
I did some custom plain javascript for it.
It work as expected
`
      if (document.querySelector(".multi-select")) {
        function setAccesibilty(el, selectedVal) {
          el.setAttribute('tabindex', '0')
          el.addEventListener("keyup", function(event) {
              event.preventDefault();
              if (event.keyCode === 13) {
                document.querySelector("[data-id='" + selectedVal.id + "']").remove();
                let values = select.getSelected();
                var newValues = values.filter(value => value != selectedVal.value);
                select.setSelected(newValues);
              }
          });
        }
        var select = new SlimSelect({
          select: ".multi-select",
          selectByGroup: true,
          placeholder: "Please select a value",
          events: {
            afterChange: (values) => {
              if(values.length) {
                let lastVal = values[values.length - 1]
                let el = document.querySelector("[data-id='" + lastVal.id + "'] .ss-value-delete");
                setAccesibilty(el, lastVal)
              }
            }
          }
        });
        const selectedValues = select.store.data.filter(value => value.selected);
        console.log(selectedValues)
        selectedValues.forEach(selectedVal => {
          let el = document.querySelector("[data-id='" + selectedVal.id + "'] .ss-value-delete");
          setAccesibilty(el, selectedVal)
        });
      }`

**Comment by brianvoe** [comment]
I can see how that would happen given that we skip highlighting options that are already selected. If you want to figure out a pr for it please give it a shot. Otherwise well see when i can get to this.

**Comment by tibi2303** [comment]
I have a solution for this but i can't push the branch
![image](https://user-images.githubusercontent.com/36895476/207421477-f26784db-cf64-464b-93fe-494120e3b2ae.png)

**Comment by arthurstomp** [comment]
I was able to navigate, select and deselect options with the keyboard by setting `settings: { allowDeselect: true }`

Is this still an issue? If yes, could you provide more context. I would love to help :)

Sample

```
// src/docs/pages/home.vue
    this.single = new SlimSelect({
      select: this.$refs.slimSingle as HTMLSelectElement,
      settings: {
        allowDeselect: true
      }
    })
    this.multiple = new SlimSelect({
      select: this.$refs.slimMulti as HTMLSelectElement,
      settings: {
        allowDeselect: true
      }
    })
```
