### ISSUE TITLE
Empty string value is replaced with option text

### ISSUE THREAD

**Issue by timdk** [brianvoe/slim-select#293]
**Describe the bug**
When explicitly setting an option with a value of empty string, the value is replaced with the text when the options are rendered.

```
<option value="" data-placeholder="true">Brand</option>
```

Becomes 

```
<option value="Brand" data-placeholder="true">Brand</option>
```
 
Having an empty value is valid HTML so I think it should be supported. I'm not suggesting that we introduce a breaking change by removing the fallback to text as value, but instead to only do when the value is actually `undefined` instead of empty as it is now.

We could do this by changing the condition in select.ts `createOption()`

```
optionEl.value = info.value !== '' ? info.value : info.text
```

**Comment by brianvoe** [comment]
New version released today! Check it out and if you still have an issue let me know.
