### ISSUE TITLE
Uncaught TypeError: Cannot set property 'selected' of null at HTMLDivElement.<anonymous> 

### ISSUE THREAD

**Issue by enochtamulonis** [brianvoe/slim-select#297]
Im using stimulusjs inside rails to add options from the text inputted but am getting an error This is happening when a user trys to click on an option Im loading new options when the user types in the search box like this. The slim select gets rerendered every time content is loaded usually it works after u keep typing and it rerenders a few times or you close the slim select and go back in that case I keep the options and it still works.
```

const slimSelect = new slimSelect({
  select: "#my-element",
  ... more options
})

slimSelect.slim.input.addEventListener("input", this.addOptions.bind(this))

async addOptions(event) {
  let target = event.target.closest("input")
  if (target.value.length > 0) {
    let url = "localhost:/3000/api/v1/posts?q= + target.value
    const response = get(url)

    if (response.ok) {
      const json = await response.json
      this.options = this.createOptions(json) // my function to create options from json filling out text and value attributes
      this.slimSelect.setData(this.options)
    }
  }
}
```
**Screenshots**
Add screenshots to help explain your issue. If you do not submit at least an image or animated gif I most likely wont look into it.

**Comment by brianvoe** [comment]
New version released today! Check it out and if you still have an issue let me know.
