### ISSUE TITLE
Ajax doesn't work when same character is typed after clearing

### ISSUE THREAD

**Issue by Taka571** [brianvoe/slim-select#298]
Hi. It's a minor thing.

1. type characters
2. clear (click x)
3. type same characters
4. ajax is not called

It doesn't seem to happen with different characters.

https://user-images.githubusercontent.com/46995981/127088186-2468156a-6fc7-4294-abcc-ad7c27a2f4a3.mov

https://user-images.githubusercontent.com/46995981/127088279-c52ac7fe-6a0e-4e76-8af5-359ee5abb8f0.mov

**Comment by Kreyshin** [comment]
The same thing happens to me, I hope a solution is found.

**Comment by LukMas** [comment]
I've just seen this library, and checked the issues list and see this one. For how it works, it looks that the AJAX call is cached, hence, maybe, changing this in the AJAX config would solve the problem.

**Comment by Andrea-gli** [comment]
same issue happened to me as well

**Comment by brianvoe** [comment]
New version released today!

Sorry for the delay on this. I completely reworked searching. You can make a simple promise return and resolve with your own data. See https://slimselectjs.com/events#search

Check it out and let me know what you think
