### ISSUE TITLE
Error on rendering multiple select element with many elements selected

### ISSUE THREAD

**Issue by konrad-g** [brianvoe/slim-select#30]
When I try to apply slim-select to multiple select element with many preselected items, it throws following error:

Error: Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node. (logical-mutation.js:34)

**It happens in Firefox and Edge desktop browsers.**

Example select element that I'm talking about:

```
<select id="property" name="property" multiple>
  <option value="office">Office</option>
  <option value="retail" selected="selected">Retail</option>
  <option value="liquidStores" selected="selected">Liquid Store</option>
  <option value="restaurant">Restaurant / Cafe space</option>
  <option value="sportFacility" selected="selected">Sport facility</option>
  <option value="industrial">Industrial / Warehouse</option>
  <option value="gas">Gas/Service Stations</option>
  <option value="showrooms">Showrooms / Bulky Goods</option>
  <option value="hotel">Hotel / Leisure</option>
  <option value="medical">Medical</option>
  <option value="hospitals">Hospitals</option>
  <option value="liveWork">Live/Work</option>
  <option value="religious">Religious Facilities</option>
  <option value="schools">Schools</option>
  <option value="college">Colleges and Univiersities</option>
  <option value="entertainment">Entertainment Uses</option>
  <option value="driveThrough">Drive-Through Facilities</option>
  <option value="garage">Garage</option>
  <option value="land">Vacant Land</option>
  <option value="other">Other</option>
</select>
```

It doesn't always occur, but when it does, you can still open slim select and when you select an additional item, initially selected options appear.

It looks like an interference with WebComponents library that I also use https://github.com/webcomponents/webcomponentsjs

**Comment by konrad-g** [comment]
It doesn't always occur, but when it does, you can still open slim select and when you select an additional item, initially selected options appears.

**Comment by konrad-g** [comment]
Delaying slim-select set up by 100ms solves this problem on both Firefox and Edge.
I guess issue can be closed.

**Comment by konrad-g** [comment]
Or maybe it would be possible to solve it so we could avoid hacks. Sorry for the trouble.

**Comment by brianvoe** [comment]
Haha I woke up this morning to see you open and close this at 3am in the morning. Well because i find this so interesting I suppose ill look into this.

Jk ill figure out this problem and let you know asap.

Thanks! No Thanks! Thanks! No Thanks! Thanks!

**Comment by konrad-g** [comment]
Hehe sorry for the confusion. I'm trying to iron out this bug and it's more complicated than it seems to be.

**Comment by brianvoe** [comment]
Are you able to replicate this on the actual slimselectjs.com website? I wasnt able to recreate this.

**Comment by konrad-g** [comment]
I pinned it down. The values in multiple select are disappearing whenever I change "class" attribute in the original select element. Then I get this error.

**Comment by brianvoe** [comment]
hmm seems like something outside of slim select is effecting it. I believe just updating the class value on the original slim select would trigger the mutation observer and just essentially rerender slim select.

**Comment by brianvoe** [comment]
lets say you did this outside the webcomponents package you are using. Does it still happen?

**Comment by konrad-g** [comment]
Let me check

**Comment by konrad-g** [comment]
This issue is related with WebComponents package. It's outside of slim-select. I'm closing it. Sorry to waste your time.

**Comment by brianvoe** [comment]
No problem. Glad you figured it out.

Thanks for using my package. Let me know if there is anything i can do to improve it.
