### ISSUE TITLE
addable: add new item to existing optgroup

### ISSUE THREAD

**Issue by columbian-chris** [brianvoe/slim-select#300]
Is there a way to add a new item via the _addable_ option to an existing `<optgroup>` instead of just being added to the end independently?

**Comment by brianvoe** [comment]
New version released today! If this is still an issue let me know. Check out the addable section in the docs.

**Comment by Samiam519** [comment]
I'm having this issue still, addable looks like this

`
addable: function(value) {
      // return false or null if you do not want to allow value to be submitted
      // when value already exists in list
      if (userSearches.includes(value) || systemSearches.includes(value)) {
        return false
      }

      // Optional - Return a valid data object.
      // See methods/setData for list of valid options
      return {
        label: 'User Searches',
        options: {
          text: value,
          value: (Math.floor(1000 + Math.random() * 9000)).toString() + '-user'
        }
      }
    }
`

I've also tried wrapping the return object and the text value object in square brackets

Adding works fine when it's just the text,value pair, but that doesn't add to the optgroup
