### ISSUE TITLE
add a single new item

### ISSUE THREAD

**Issue by columbian-chris** [brianvoe/slim-select#301]
Is there a way I can add a single new item?  The _set_ method only allows me to select an already defined item and the _setData_ method will replace all existing items with a new data set.

Maybe this feature should be added (in the form of a new method)?

**Comment by columbian-chris** [comment]
I have discovered an undocumented method named `addData()` that appears to do the trick.

```js
var select = new SlimSelect({
  select: '#select'
});
select.addData({ text: "hello world", value: "new_item" });
select.set('new_item');
```

It looks like there's actually several undocumented methods available.  The documentation at https://slimselectjs.com/methods should be updated.

**Comment by brianvoe** [comment]
New version released today! If this is still an issue let me know.
