### ISSUE TITLE
setData is updating the select but not SlimSelect

### ISSUE THREAD

**Issue by ShellWillCode** [brianvoe/slim-select#306]
Hi,

Firstly, great plugin.  I'm not sure if I am using the setData correctly. I am dynamically creating the options for the select via an API. I am setting the data like so on a existing slim select:

`select.slim.setData(displayData);`

The select element is updating as expected but I get "No results" showing in the SlimSelect  i.e. typing Bac in the search:

![image](https://user-images.githubusercontent.com/20902005/130801659-043f6eac-a7a6-4e2d-8858-d46874e1966f.png)

If I then use backspace, I then get the desired result:

![image](https://user-images.githubusercontent.com/20902005/130797941-bf9dca44-1cd2-40e1-aa2c-8c9897fdf00d.png)

It's almost like it doesn't register the first input when initially using the plugin but then click off or search again it works fine.  

I did try using the ajax approach but kept getting an error when initializing a new SlimSelect:  Cannot read property 'showContent' of undefined

_Plugin installed via Npm and _import SlimSelect from 'slim-select'_ is at the top of js file._

Would appreciate if you could advise?

**Comment by EstevamPonte** [comment]
Hello, I had the same issue with slimSelec
What I did to fix is call the `render` function from slimSelect.
Lik this:
`select.slim.render()`
Or
`select.slimSelect.render()`

I don't know if will work for you, but works for me.

**Comment by brianvoe** [comment]
New version released today! If this is still an issue let me know.
