### ISSUE TITLE
Slim Select Project Status

### ISSUE THREAD

**Issue by thatmattlove** [brianvoe/slim-select#308]
Hello,

First, great project!

Second, will this project be actively maintained in the future? I can't help but notice lots of issues piling up and simple PRs going unreviewed. Before I sink too much more time into using the library, it'd be great to know if the project has a future.

Lastly, if the intent is to keep Slim Select active and maintained, are you looking for any help? I don't have an over abundance of free time I can commit, but I may be able to help knock out some low hanging fruit.

Thanks!

**Comment by brianvoe** [comment]
Thanks for the kind words. I understand your concern for the issues piling up. I am currently working on a second version of this project and to not stop my ability to complete it I have been putting my time into that. Hope you understand.

**Comment by thatmattlove** [comment]
Great to hear! And yes, completely understood.
