### ISSUE TITLE
SlimSelect using keyboard

### ISSUE THREAD

**Issue by Manhetn** [brianvoe/slim-select#314]
Thank you for a great project.

The plugin works well when switching between options (using the tab key) and selecting a value using the ↓ and ↑ buttons. But I ran into nuances:

1. When I use the "tab" button to switch between slim-select, after the selection, the dropdown is closed, but it is not clear which slim-select has focus.
Can you add class (ex.: "ss-main--focus"), when is a user using a "tab" to switch between slim-select (and if slim-select has ss-main-focus class, when user clicks down arrow button or "Enter", slim-select will opening)?

2. is it possible to make it so that the option with data-placeholder = "true" does not get the class "ss-highlighted" when the option is selected by the keyboard?

3. If select contains a structure like this: 
```
<option value="first value">first option</option>
  <optgroup label="label optgroup 1">
    <option value="value">first option in optgroup 1</option>
    <option value="value">second option in optgroup 1</option>
    <option value="value">third option in optgroup 1</option>
 </optgroup>
 <optgroup label="label optgroup 2">
    <option value="value">first option in optgroup 2</option>
    <option value="value">second option in optgroup 2</option>
    <option value="value">third option in optgroup 2</option>
 </optgroup>
```

If user using keybord. first option and any optgroup can get class ss-highlighted. But option in optgroup can't get class ss-highlighted.

is it possible to fix this problem?

**Comment by vielhuber** [comment]
I support this (especially 1.).

**Comment by brianvoe** [comment]
New version released today! If this is still an issue let me know.
