### ISSUE TITLE
Null Value Errors

### ISSUE THREAD

**Issue by benplum** [brianvoe/slim-select#32]
If no selected value can be found, errors are thrown:

https://github.com/brianvoe/slim-select/blob/master/dist/slimselect.js#L306
https://github.com/brianvoe/slim-select/blob/master/dist/slimselect.js#L398

Seems like these lines are being compiled incorrectly:

https://github.com/brianvoe/slim-select/blob/master/src/slim-select/index.ts#L134
https://github.com/brianvoe/slim-select/blob/master/src/slim-select/index.ts#L215

**Comment by brianvoe** [comment]
Thanks for pointing this out. I did notice this and will be fixed in the next update i am doing.

**Comment by benplum** [comment]
Thanks so much!

**Comment by brianvoe** [comment]
No thank you!!!
