### ISSUE TITLE
Search on async data removes selected elements

### ISSUE THREAD

**Issue by rottmann** [brianvoe/slim-select#323]
**Describe the bug**

Search values on async loaded data removes previous selected values.

REPL: https://svelte.dev/repl/421b3798d22a47458a575cc5ecad3d93?version=3.46.3

Type "asy" and it removes the current selected value.
Press "ESC" to close without select leaves everything empty.

Version: 1.27.1

**Screenshots**

![chips](https://user-images.githubusercontent.com/381201/151545674-f90ced3b-ec14-4c89-b435-10dc3e4d5494.png)

**Comment by rottmann** [comment]
Another problem is the cached result. Search for "asy" select an item. Search again for "asy" it did not trigger the ajax loader.

**Comment by coolibry** [comment]
hello,
i store previous search and result to avoid some request,
when callback got  previous result, 
and search the same text = ajax request is not made.
 
like this request, 
solution need to be found.

**Comment by brianvoe** [comment]
New version released today! If this is still an issue let me know.
