### ISSUE TITLE
addable no options work apart from text and value.

### ISSUE THREAD

**Issue by Misha327** [brianvoe/slim-select#327]
I am attempting to add a data attribute called data-label to a new option using the addable method/listener. However it does not add it to the new option. I also tried then adding a class and a style to the new option with no luck.

The returned option only shows change in text and value (tested by using toUpperCase()).

`
 
        addable: function (value) {
  
          let newOption = {
            data: {
              label: 2
            },
            class: 'bob',
            text: value,
            value: value.toUpperCase(),
          }
  
          return newOption;

      }
`

**Comment by brianvoe** [comment]
New version released today! If this is still an issue let me know.
