### ISSUE TITLE
Not updating option css style

### ISSUE THREAD

**Issue by rbrzezinski** [brianvoe/slim-select#330]
Consider this select:
```html
<select>
<option value="1">First</option>
<option value="2">Second</option>
</select>
```
Slim-select correctly parse this code and generate widget.

After changing css of one option, eq:
```javascript
optionEl.style.display = 'none';
```
Slim-select not hide option, unless I wil change something in `<select>` element:

```javascript
select.disabled = true;
optionEl.style.display = 'none';
select.disabled = false;
```

**Comment by brianvoe** [comment]
New version released today! If this is still an issue let me know.
