### ISSUE TITLE
onChange when deselected

### ISSUE THREAD

**Issue by flynryan692** [brianvoe/slim-select#331]
**Describe the bug**
I am using the onChange option to loop through the selected options and then add .hide() to a corresponding html element in order to hide items on my page, and I write a little note in the console for my own reference. This works great, however if I deselect an option it seems nothing in my code under the onChange option happens. I don't even get a message in the console. Is there a way to run onChange when you deselect an option?

**Screenshots**
![image](https://user-images.githubusercontent.com/4295577/158885841-c39025f5-2726-4f62-816e-ad5a12cf6c20.png)

**Comment by brianvoe** [comment]
New version release today! This should be fixed in the new version

**Comment by typo3ua** [comment]
> New version release today! This should be fixed in the new version

it does not work in new version `https://unpkg.com/slim-select@2.6.0/dist/slimselect.min.js`

it works only in this version `https://unpkg.com/slim-select@1.18.8/dist/slimselect.min.js`
