### ISSUE TITLE
Add exports "style" in package.json for using [@import "slim-select"] in sass.

### ISSUE THREAD

**Issue by VQH-cmd** [brianvoe/slim-select#332]
**Improvement suggestion**:

`@import "slim-select"` for sass/scss

```.json
// package.json
...
"exports": {
    "require": "./dist/slimselect.min.js",
    "import": "./dist/slimselect.min.mjs",
    // ⬇ This line ⬇
    "style": "./dist/slimselect.min.css"
},
...
```

**Comment by christian-sa** [comment]
+1

**Comment by leonrustmeier** [comment]
+1

**Comment by brianvoe** [comment]
New version released today! Check it out and let me know your thoughts. I have a sass field in the package json. Hopefully that fixes this for you. If not let me know and Ill try to get a fix in.
