### ISSUE TITLE
hideSelectedOption on multiple select with optgroups

### ISSUE THREAD

**Issue by zakandaiev** [brianvoe/slim-select#333]
Hi!

Is this a bug or my bad? I have an multiple select with _optgroups_ and set _hideSelectedOption: true_. So it allow to select only 4 values then it isn't opening

[Created a demo for this](https://codepen.io/zakandaiev/pen/PoEQdLY)

Thanks for this cool library!

**Comment by brianvoe** [comment]
New update to slim select coming soon. Hopefully the work I put into the update fixes this issue for you. I just ran a local test and seems to be working the way you would expect it to. Once its released I would love if you could test it out and give me feedback.
