### ISSUE TITLE
Netbox Slim-select form not disabling in JS

### ISSUE THREAD

**Issue by leerobertsprojects** [brianvoe/slim-select#335]
**Describe the bug**
Im using Netbox v3 which uses Slim-Select for its dynamic forms but im trying to disable a form when a checkbox is ticked using javascript, but although the DOM changes and adds the disabled attribute it dosent disable on the page.
the JS code im using is 

const vlan = document.querySelector('#id_vlan');
const physical_facing = document.querySelector('#id_physical_facing');
const service_type = document.querySelector('#id_service_type');
const bd_function = document.querySelector('#id_function');

function vlan_enable(){
    vlan.disabled = false;
};
function vlan_disable(){
    vlan.disabled = true;
};
function service_function_enable() {
service_type.disabled = false;
bd_function.disabled = false;
};
function service_function_disable() {
    service_type.disabled = true;
    bd_function.disabled = true;
};
(function() {
    service_function_enable();
    vlan_enable();

    if(physical_facing.checked){
    service_function_disable();

    } else {
        vlan_disable();
    }
})();

function pf_event() {
    if(physical_facing.checked) {
    vlan_enable();
    service_function_disable();

} else {
    vlan_disable();
    service_function_enable();
}

};

physical_facing.addEventListener('change', pf_event)

can you advise if this is a bug or if there is another way i should be disabling the form due to an event?

**Comment by brianvoe** [comment]
New version coming soon. I put a decent amount of work into making sure updated values from the original select trigger and update in the store and the rendered output. Once it is released i would love to see if you still come across the same issue. Thanks for submitting this and sorry for the delay. Hopefully this new update will help you out.

**Comment by brianvoe** [comment]
New version of slim select has been released. If this is still an issue let me know and ill try to take care of it.
