### ISSUE TITLE
Option to arrange search results so the ones that start with the typed phrase at the top

### ISSUE THREAD

**Issue by ClintCWC** [brianvoe/slim-select#338]
Hi, I'm looking for an option (if it exists) where the results in the drop-down are arranged with the results that start with the search phrase at the topmost.

Currently i think results are only showing in the original order, 

i.e. in the case of searching for zyx

results
abc zyx
axyz
bxyz
cxyz
zyx 123
xyz 234

would rather show 

xyz 123
xyz 234
abc zyx
abc zyx
axyz
bxyz
cxyz

Is this possible?

**Comment by brianvoe** [comment]
New version coming soon. The new implementation will be through the events search function where you can specify the list of options you want to return.
