### ISSUE TITLE
Fix importing css file from webpack 5 package (Package path ./dist/slimselect.min.css is not exported from package)

### ISSUE THREAD

**Issue by ybart** [brianvoe/slim-select#342]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `slim-select@1.27.1` for the project I'm working on.

After upgrading to Webpack 5, I got the following error while creating my JS bundle :

```
Module not found: Error: Package path ./dist/slimselect.min.css is not exported from package ./node_modules/slim-select (see exports field in ./node_modules/slim-select/package.json)
```

It's caused by the following import :

```js
require('slim-select/dist/slimselect.min.css')
```

I have deleted the export section and that fixed the issue for me. However, we should probably write the export section properly so the import works with webpack 5.

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/slim-select/package.json b/node_modules/slim-select/package.json
index c7a2d3c..8c4c5d8 100644
--- a/node_modules/slim-select/package.json
+++ b/node_modules/slim-select/package.json
@@ -12,10 +12,6 @@
     "node": ">=8"
   },
   "main": "dist/slimselect.min.js",
-  "exports": {
-    "require": "./dist/slimselect.min.js",
-    "import": "./dist/slimselect.min.mjs"
-  },
   "style": "dist/slimselect.min.css",
   "sass": "src/slim-select/slimselect.scss",
   "types": "dist/index.d.ts",
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by brianvoe** [comment]
New release coming soon. Not sure if this is still an issue but if it is we can reopen this again.

**Comment by rickychilcott** [comment]
As an FYI `import "slim-select/dist/slimselect.css"` works for me on Slim Select 2
