### ISSUE TITLE
Change "search" text in search input

### ISSUE THREAD

**Issue by Lukaum** [brianvoe/slim-select#347]
i looked in documentation but i didn't find how to change the "search" text inside the input.

![slim-search](https://user-images.githubusercontent.com/21267353/181034092-a9d695b2-c493-4422-9e3a-7bb6b954b29b.png)

**Comment by iztokinvest** [comment]
this works for me

```
window.addEventListener("DOMContentLoaded", () => {
  const slimSelectInputs = document.querySelectorAll("[type='search']");
  for (const inp of slimSelectInputs) {
	  inp.placeholder="New Text";
  }
});
```

**Comment by mvmrik** [comment]
This works for me
```
window.addEventListener("DOMContentLoaded", () => {
  const slimSelectInputs = document.querySelectorAll("[type='search']");
  for (const inp of slimSelectInputs) {
	  inp.placeholder="Търсене";
  }
});
```

**Comment by boki69** [comment]
This works for me:

`searchPlaceholder: 'New Text'`

**Comment by brianvoe** [comment]
New version releasing soon @boki69 is correct. the only difference is it will be under settings.

settings: {
    searchPlaceholder: 'New Text'
}
