### ISSUE TITLE
Templates with <optgroup>

### ISSUE THREAD

**Issue by macfire** [brianvoe/slim-select#35]
Is it it possible to use item templates with `<optgroup>` ?

**Comment by brianvoe** [comment]
Hey Macfire, Sorry for the delayed response, i just saw this message in my inbox. When you say templates with optgroup can you elaborate a little more about what you mean?

**Comment by macfire** [comment]
When building the SS with dynamic data, it is very convenient to apply a template to the options.
For example:

```javascript

/* I loop through my original data and prep each option with innerHTML template */
{
    text:  'item-name',
    value: 'value',
    innerHTML: '<span>' + item_number + '</span><span>' + item_name + '</span>'
}

```

I also would like to include an `<optgroup>` to separate the products, while also setting the innerHTML for each option.

```
Widgets <- possible to use innerHTML on <optgroup> ??
    item_01   Widget 1
    item_02   Widget 2
Gadgets
    Item 03    Gadget 1
    Item 04    Gadget 2
```

**Comment by brianvoe** [comment]
oh i got ya. ya for the label wouldnt be a bad idea. I can see if i can get it in there.

**Comment by macfire** [comment]
Thanks.  I'm no hurry, but was curious if possible.

**Comment by brianvoe** [comment]
shouldnt be to crazy. Im implementing ajax ability right now. ill try to get to it after.

**Comment by Samiam519** [comment]
hey just wondering if this ever got added? if so, is there documentation for it somewhere?
