### ISSUE TITLE
Dealing with typescript when I already have a created slim select

### ISSUE THREAD

**Issue by ImKubass** [brianvoe/slim-select#352]
``` ts

const select = document.querySelector('.my-already-created-select')
const { slim } = select

// Error:  Property 'slim' does not exist on type 'HTMLSelectElement'.
```

[Screenshot](https://prnt.sc/TRNX6zod0X_m)

How can I deal with typescript when getting already created select? Also how can I import interface for slim object?

**Comment by albertogonzalez-es** [comment]
I also have that problem. If I test with this code:

`const select = document.getElementById('my-already-created-select');
setTimeout(() => {
	console.log(select.slim);
}, 0);`

With this code, the property slim is ok, but timeout 0 generate a delay and is a problem for easy task.

**Comment by ImKubass** [comment]
Okay maybe I partialy figured it out.

``` ts
import SlimSelect from "slim-select";

interface SlimInstance extends HTMLSelectElement {
  slim: SlimSelect
}

const select = document.querySelector<SlimInstance>('.my-already-created-select')
const { slim } = select

slim.set(myValueToSet)

```
<img width="728" alt="Screenshot at Sep 22 19-19-09" src="https://user-images.githubusercontent.com/22158893/191811418-7ca70226-aefc-43c8-9bbe-bb5e29862c00.png">


And also I am getting type hinting, wich is cool.

But sadly I have to import whole SlimSelect again, is there posibility to import just interface for SlimSelect?

**Comment by ImKubass** [comment]
> I also have that problem. If I test with this code:
> 
> ![image](https://user-images.githubusercontent.com/114160346/191753812-5aefc04f-7b49-4362-a073-6a30da1c25d0.png)
> 
> With this code, the property slim is ok, but timeout 0 generate a delay and is a problem for easy task.

I dont have exacly problem like this. My code working as should, and there is slim object in this select. But vscode is not satisfied :D

**Comment by brianvoe** [comment]
I briefly skimmed these comments. New version of slim select uses typescript exclusively, but the only thing i couldn't force typescript to do is act like slim select was part of the HTMLSelect Element. You can see this at the end of the constructor where i basically say 

// Add SlimSelect to select element
(this.selectEl as any).slim = this

New update coming soon. By the end of next week.
