### ISSUE TITLE
Set min number for multiple select

### ISSUE THREAD

**Issue by francesco-loreti** [brianvoe/slim-select#353]
Is there a way to set a minimum number of selections from the multiple select?

Thanks

**Comment by vasaf** [comment]
> Is there a way to set a minimum number of selections from the multiple select?
> 
> Thanks

Did you end up finding a solution to this? I currently need this and am thinking of the best approach..

**Comment by brianvoe** [comment]
I am currently working on the next version of slim select. I did add minSelected and maxSelected. They should be going out in the next major version. You can check out the process in the develop branch.

**Comment by francesco-loreti** [comment]
Hi, I don't have a solution for min selection. So, I wait the new major release. Do you know when you can release It? Thanks for your job.

**Comment by brianvoe** [comment]
I dont have a timeline per say but am actively working on it on nights and weekends. So well see. But if it helps im 90% there and then i want to go through issues and make sure everything works the way people need it too.

**Comment by brianvoe** [comment]
New version of slim select has been released. If this is still an issue let me know and ill try to take care of it.
