### ISSUE TITLE
Displaying `N items selected` instead of the actual items

### ISSUE THREAD

**Issue by saleyn** [brianvoe/slim-select#354]
Presently the selected items are automatically added to the visually displayed combo box field.
Is there a way to have one of the following behaviors of the selected items:
- Instead of adding them to the displayed field to have a custom HTML rendered, such as `3 items selected`
- Alternatively, add items as currently done, but if the width of the added item doesn't fit the width of the combo box, instead of wrapping the items and expanding the height of the combo box, display `N items selected`

My use case is that the user may select up to 50 values, and in the current implementation the UI with the filled combo-box becomes too distorted by the auto adjustment of the component's size with selected values.

**Comment by MilenFrom** [comment]
Any update on this?

**Comment by brianvoe** [comment]
Currently working on version 2. You can see the progress in the develop branch. Im going to leave this comment open for now cause i do like this idea. I just need to finish the rework first.

**Comment by brianvoe** [comment]
New version of slim select has been released. I still want to add this feature. but if anyone wants to try to add it to the new version. Ill get that merged in asap. In the meantime I have to add the vue integration first.

**Comment by MilenFrom** [comment]
I'll add it as soon it is live

**Comment by brianvoe** [comment]
It's live. Go for it. Let's see if I made it easy enough to work with!

**Comment by MilenFrom** [comment]
Ok
I'll update the library and will see if everything else works correctly

**Comment by brianvoe** [comment]
Hopefully this helps. But to lessen the number of settings. I would add something like 

```
settings: {
        valuesThreshold: 5 // if it exceeds 5 then it shows "N selected" default 999.
}
```

**Comment by MilenFrom** [comment]
I've updated to v2 using the download and simply replace the minified file, however throws an error:
`Uncaught SyntaxError: Unexpected token 'export'`

**Comment by brianvoe** [comment]
I probably have to update the cdn as well. if you pull it down via get. run npm install and then npm run dev. youll have a fully working docs where you can test everything out. You may need to know a little vue to work with it.

**Comment by brianvoe** [comment]
Let me know if your still having issues.

**Comment by brianvoe** [comment]
@MilenFrom I was able to fix the build output stuff(v2.0.2). You shouldnt be getting that issue anymore. See https://slimselectjs.com/install#cdn

**Comment by MilenFrom** [comment]
I'll try soon and share more details on this

**Comment by saleyn** [comment]
@brianvoe , is the setting you mentioned implemented?
> ```
> settings: {
>         valuesThreshold: 5 // if it exceeds 5 then it shows "N selected" default 999.
> }
> ```

I can't get that to work: https://jsfiddle.net/rhxjbvuk/

**Comment by brianvoe** [comment]
That part is not implemented yet.

**Comment by brianvoe** [comment]
This will go in the next release today

**Comment by saleyn** [comment]
Thank you very much! This is exactly what I was looking for!  Excellent work!

**Comment by brianvoe** [comment]
Thanks for everyone help on this
