### ISSUE TITLE
Deselect doesn't get hidden when using setData()

### ISSUE THREAD

**Issue by Flexxkii** [brianvoe/slim-select#355]
**Describe the bug**
When using setData(array) and also pushing a placeholder into that placeholder it seems to show the deselect label while there is nothing selected.

**Screenshots**
https://i.imgur.com/zlMFtk9.png

**Comment by Flexxkii** [comment]
Alright, it seems that I fixed it.
Besides setting placeholder to true and adding the required text. Besides an empty string of text, you should also add an empty value.

So:
{'placeholder': true, 'text': '', 'value': ''}

Hopefully this can be updated in the documentation.

**Comment by brianvoe** [comment]
Fixed in new update coming soon. Week or so.
