### ISSUE TITLE
React integration

### ISSUE THREAD

**Issue by brianvoe** [brianvoe/slim-select#357]
Need to add a react integration. If anyone is up for it let me know and ill assign you to it.

**Comment by brianvoe** [comment]
If anyone wants to tackle this one you can reference how I did the vue integration

**Comment by shuvro111** [comment]
@brianvoe I'm interested to contribute to the React integration.

**Comment by brianvoe** [comment]
@shuvro111 Go for it! Lets see if what I built is easy enough to add another integration.

So I idea is being able to run a react component in the vue docs to showcase the integration. The other part is I havent been able to fully do it yet but jest is installed in the repo and i want to get more tests in.

Let me know if you have any questions.

**Comment by brianvoe** [comment]
Hey @shuvro111 do you have any update on this?

**Comment by brianvoe** [comment]
This issue is now back up for grabs if anyone wants to tackle it.

**Comment by sahil-ansari01** [comment]
I want to integrate

**Comment by dminkovski** [comment]
@brianvoe I'd like to try this one out :)

**Comment by brianvoe** [comment]
That would be awesome! Let me know if you need anything.
