### ISSUE TITLE
Problems using 2.0.0

### ISSUE THREAD

**Issue by FabianKoestring** [brianvoe/slim-select#358]
**Describe the bug**
We have problems using the new `2.0.0` version? In version `1.27.1` we used the unminified version.

**Screenshots**
Add screenshots to help explain your issue. If you do not submit at least an image or animated gif I most likely wont look into it.

**Comment by brianvoe** [comment]
I can add an unminified version to rollups build. I guess my question is what is your use case?

**Comment by FabianKoestring** [comment]
Previously we used `dist/slimselect.js`. Actually we cant use Slim-Select in Version `2.0.0`. I´m no JS expert. Which file do we have to use?

**Comment by brianvoe** [comment]
So yesterday i updated to 2.0.1 to make the dist/slimselect.js use umd like the old version did. So you should be able to use that. If not let me know what happens when you try. You also can use any of the cdn to pull javascript down too. https://slimselectjs.com/install its really your preference.

**Comment by coolibry** [comment]
hello,
with the example of documentation:
- missing / at line 10 </script>
-  we got this error at load :
`Uncaught TypeError: SlimSelect is not a constructor`

with SlimSelect 1.27 all is ok.

**Comment by brianvoe** [comment]
I finally got this working again. See the cdn install page. https://slimselectjs.com/install#cdn

I also added an minified and unminified version for UMD for now.

Here is a codepen example
https://codepen.io/brianvoe/pen/gOKvNxV

Hopefully this fixes the issue your everyone. Thanks for the help on this.

**Comment by FabianKoestring** [comment]
Works! 👌✌️
