### ISSUE TITLE
Get Slim object dynamically

### ISSUE THREAD

**Issue by ARORoele** [brianvoe/slim-select#36]
Let's say that i have 10+ slim selects on my page.
I don't want to store them in a var but i want to get the slim object dynamically.

For example : ".find('select[name="blabla"])"
How do i get the slimselect object so i can use ".set()" to change the selected option?

I don't want to re-create the slim select to change the data: 
var select = new SlimSelect({
               select: .....find('select[name="blabla"])
})
select.set(newVal);

**Comment by brianvoe** [comment]
Thats a good point. Let me put some thought into binding a pointer to the slim select class on the slim dropdown element. P.S. open to suggestions

**Comment by brianvoe** [comment]
This has been implemented in version 1.14.0

```javascript
// If you already have a created slim select you can select your div
// and continue to use slim select off of the element using the .slim data value
let el = document.querySelector('.element .you #want')
el.slim.open() // Or any other options/methods
```

Thanks

**Comment by jnschrag** [comment]
Sorry to bump an old conversation, but @brianvoe could you provide a more detailed example of how using .slim is supposed to work? We're supposed to select the div created by slim-select, not the original <select> element, correct?

If so, calling `el.slim.set(value)` triggers the onChange event, but it results in an error because the event information isn't defined. It also doesn't update the value of the select box, but instead changes it to the default "Select value" text.

**Comment by brianvoe** [comment]
your correct in your findings. I have some more updates that need to happen to make sure all events are set on the original select dropdown so you can call the events properly. Right now it looks to attach some stuff but not everything i need. Ill try to get to this soon. 

Let me know if you have a deadline you need to hit or if this is holding you up right now.

Thanks.

**Comment by jnschrag** [comment]
Thanks for the super quick reply! Unfortunately I need to get the project I'm working on wrapped up in the next two or three days, so I'll probably need to look for another library that accomplishes what I need. But I've got this repo starred, so I'll keep an eye out on those changes, but no need to rush them on my account. :)

**Comment by brianvoe** [comment]
Ill get this finished up tonight and update you when its done.

Thanks.

**Comment by brianvoe** [comment]
Finished this fix. You should now be able to select the original select dropdown and run .slim.(whatever method you want)

Ex: document.querySelector("#my-select").slim.open()

**Comment by jnschrag** [comment]
Awesome, thank you very much!

**Comment by brianvoe** [comment]
👍 Your welcome! Enjoy

**Comment by AdamReece-WebBox** [comment]
Can we do this if we already have an instance of the select? E.g.

```
var $towns = $form.find('select[name="filter[towns]"]');
if ($towns.length != 1) {
    return;
}
var $townsSS = $towns.next('.ss-main');
```

Assuming `$townsSS.length` is 1, can I get `.slim` from `$townsSS`?

**Comment by brianvoe** [comment]
```
var slim = new SlimSelect({
  select: '#single'
})

slim.dowhateveryouneedtodo()
```

**Comment by brianvoe** [comment]
Also break the chains of jQuery. You dont need it anymore. :)

**Comment by erichstark** [comment]
Hello, I have an issue with adding options/properties/functions dynamically. Am I doing something wrong?


const instance = document.querySelector('select');
instance.slim.searchFilter = (option, search) => {
      return option.text.substr(0, search.length) === search;
    };
