### ISSUE TITLE
Unexpected token 'export' 

### ISSUE THREAD

**Issue by tinect** [brianvoe/slim-select#361]
**Describe the bug**
load `https://cdnjs.cloudflare.com/ajax/libs/slim-select/2.0.0/slimselect.js`
seeing error: Uncaught SyntaxError: Unexpected token 'export' (at slimselect.js:1:29592)

from docs:
```
<script src="https://cdnjs.cloudflare.com/ajax/libs/slim-select/2.0.0/slimselect.js"></script>
```

**Comment by brianvoe** [comment]
Ok i updated the base export type to umd like it was in the last version. Should be good now in v2.0.1. Might need to give the cdn some time to cache the new version. Thanks for pointing this out.

**Comment by tinect** [comment]
Hey @brianvoe,

Thank you.

But using `https://cdnjs.cloudflare.com/ajax/libs/slim-select/2.0.0/slimselect.umd.js` meanwhile doesn't work because SlimSelect has no constructor.

![image](https://user-images.githubusercontent.com/135993/203158191-048485ab-f8ff-411d-9a42-edf4bc443bdf.png)

**Comment by brianvoe** [comment]
Ill have to test this further. I switched to rollup so Im not 100% a different in how they output compared to webpack. If you have any insight let me know and ill make updates accordingly. Thanks.

**Comment by tinect** [comment]
Sadly, I don't know about rollup.js. Should I open a new issue?

**Comment by brianvoe** [comment]
https://cdnjs.com/libraries/slim-select
Can you try just the https://cdnjs.cloudflare.com/ajax/libs/slim-select/2.0.1/slimselect.js which uses umd and let me know if you still get the same issue?

**Comment by tinect** [comment]
```html
<script src="https://cdnjs.cloudflare.com/ajax/libs/slim-select/2.0.1/slimselect.js"></script>
<link rel="stylesheet" type="text/css"href="https://cdnjs.cloudflare.com/ajax/libs/slim-select/2.0.1/slimselect.css" />

<select id="slim-select"><option value="" data-placeholder="true"></option><option value="best">Best</option><option value="select">Select</option><option value="ever">Ever</option></select>

<script>
new SlimSelect({
  select: '#slim-select',
})
</script>
```

throws: `Uncaught TypeError: SlimSelect is not a constructor at slimselect-text.html:7:1`

**Comment by brianvoe** [comment]
haha sorry i guess i could have just run it myself. Ill try to look into rollup umd for export default constructor

**Comment by brianvoe** [comment]
ok I hate all of this!!! but i finally got it. https://codepen.io/brianvoe/pen/gOKvNxV

I updated the cdn install page. https://slimselectjs.com/install#cdn

Let me know if this fixes your issue. Thanks for the help on this

**Comment by tinect** [comment]
Thank you, @brianvoe ! :-)
