### ISSUE TITLE
Addable value issue

### ISSUE THREAD

**Issue by gmq** [brianvoe/slim-select#362]
**Describe the bug**

Adding an option through `addable` _visually_ replaces any other value already selected (I'd expect it to be added) and it doesn't seem to actually change the selected values (it doesn't trigger `afterChange`) until something else gets selected.

**Comment by brianvoe** [comment]
Ok so looking and addable using a single select it works correctly. For multiple your right it does replace all selected values with the a single selected. Ill fix that.

In terms of triggering after change ill have to add that as well.

Good catches on these! Thanks!

**Comment by brianvoe** [comment]
This is fixed and will go out in the next release v2.1.0
