### ISSUE TITLE
Cannot force JS version over native select

### ISSUE THREAD

**Issue by pavel-mazhuga** [brianvoe/slim-select#364]
Hi! How do I force to use JS version over the native one on mobile? Something like `useNative: false`.

**Comment by brianvoe** [comment]
i dont think i follow

**Comment by pavel-mazhuga** [comment]
My bad. On Chrome mobile a native select takes precedence over custom solution by the library. I want to override this behavior and use the custom solution (divs). Is there any option to achieve this?

**Comment by brianvoe** [comment]
Sorry I am trying to understand you but its not clear your issue. SlimSelect hides the original select and renders its own style. Im not sure what part you want to override.
