### ISSUE TITLE
Classes applied to ss-content

### ISSUE THREAD

**Issue by tinect** [brianvoe/slim-select#365]
**Describe the bug**
Introduced with v2, all classes of the select-field are also applied onto the opened select-list.
This makes it really hard to control the style.

How can we prevent this?

**Screenshots**
![image](https://user-images.githubusercontent.com/135993/203519558-8b2a4ce1-cdfb-40c5-8a60-8769d11dfd2c.png)

**Comment by brianvoe** [comment]
I understand your issue. The counter issue I have is if i dont apply the class to the content then i get people on the other side saying they are trying to add classes to the content and they arent showing up.

Unfortunately I think this is just one of those things you'll have to up date to reflect your own needs.

Im open to discussion on this but I think ill close this issue for now.
