### ISSUE TITLE
No event is called when an item is deselected by the cross button

### ISSUE THREAD

**Issue by goryllaz** [brianvoe/slim-select#366]
Hi, I tried to upgrade to the new version but I can't get over the problem that Slim Select doesn't call any event (beforeChange, afterChange) when I try to deselect a single type of select by using the cross button. Is there another way how to catch this event?

**Comment by brianvoe** [comment]
Great catch! Ill fix that shortly and try to get a release out

**Comment by brianvoe** [comment]
Ok i fixed this and added allowDeselect to the before and after change docs so you can see that it works with deselects as well. This will go out in the next release. v2.1.0

**Comment by goryllaz** [comment]
Tank you 😊
