### ISSUE TITLE
No event when using setSelected

### ISSUE THREAD

**Issue by gmq** [brianvoe/slim-select#367]
**Describe the bug**

I'm not sure if this is actually a bug or not but I'd expect `afterChange` to trigger if I use `setSelected`.

I could use something like
``` 
if (select.slim.events.afterChange) {
  select.slim.events.afterChange();
}
```
but I'm not sure if it's the intended behavior or not.

**Comment by brianvoe** [comment]
I think i understand where you head is on this but the before and after changes are to let you know when something changed. If you run your own script to change the selected then I would just be triggering something you already know.

Im open to discussion on this but I think ill close this issue for now. Thanks!

**Comment by gmq** [comment]
Makes sense, thanks for the quick reply!

**Comment by brianvoe** [comment]
After using SlimSelect more and doing a vue integration I have concluded you were right to begin with. I needed afterChange to trigger for when even internal callbacks needed to make data or selected value changes. This will go up in the next release. Let me know if this improves your experience.
