### ISSUE TITLE
Dropdown keeps focus after closing, opens automatically after revisit of page

### ISSUE THREAD

**Issue by cappadaan** [brianvoe/slim-select#368]
Version 2.0.2

- open dropdown
- close dropdown, dropdown keeps its focus (= blue outline)
- open other browser tab
- return to original browser tab
- last closed dropdown (with focus active) is opened automatically again

expected: dropdown is not opened automatically again

The demo on https://slimselectjs.com/ also has this issue

**Comment by Admin-VO** [comment]
This seems to be fixed in 2.1

**Comment by cappadaan** [comment]
This seems to be fixed in 2.1

**Comment by brianvoe** [comment]
I know the issue you are talking about. but i dont know how to tell an on focus event not to trigger focus when returning back to the website again. Let me know if you ever find out. Better yet make a pr please.
