### ISSUE TITLE
Double select of same item after search

### ISSUE THREAD

**Issue by CozminM** [brianvoe/slim-select#369]
This happens when the widget is configured for multiselect on the search event. After searching for an item, selecting and removing it and searching again for the same item, it gets added twice to the selected items and cannot be removed. 

Tested it on the website and same things happen there (https://slimselectjs.com/events#search).
![image](https://user-images.githubusercontent.com/22344883/203979049-1ab37eee-d7a3-4742-9b99-b805870a5610.png)

**Comment by brianvoe** [comment]
I understand where your coming from. The two values that are passed in the search is the value of the search box and the currentData of what your options data is, which will tell you whats currently selected.

When you search and return the options you want you may include whats already selected. SlimSelect wont exclude options you give it.  Cause it doesnt know your intension. So if someone doesnt want an already selected value being sent back in the resolve then they should do a lookup and exclude any that exist in current data. I just didnt do that part in the docs example. I was trying not put too much in there. But looks like I should to help explain this situation.

I'll try to update the docs with more description on this. Thanks.
