### ISSUE TITLE
Multi Slim Select based on ajax result

### ISSUE THREAD

**Issue by ARORoele** [brianvoe/slim-select#37]
Also related to #31 
It would be nice if ajax requests can be used for the multi select since i do this aswell :) .
At the moment i fix it with 

- .find('option:not(:selected)').remove();   -- remove all none-selected values
- .append(options)                                   -- add new options to the select

Would be nice to replace all none selected values with the ajax results for the multi select so the selected options don't get removed.

**Comment by brianvoe** [comment]
Hey sorry for not responding. Not sure why but didnt get an email about it. Just to let you know im already ahead of you. :) that will be part of ajax in both single and multiple.
