### ISSUE TITLE
Docs For Version 1.x ?

### ISSUE THREAD

**Issue by MysterDru** [brianvoe/slim-select#372]
**Describe the bug**
It looks like SlimSelect got update to version 2 over the last week or so (8 days ago). As a result, the main docs site for [slimselect](https://slimselectjs.com/) now only shows content for version 2 of the library. 

While I intend to update my project to use version 2 soon, I am still on version 1. How can I access documentation for usage of version 1.x of the library?

**Comment by brianvoe** [comment]
This is understandable, unfortunately I really didn't want to keep maintaining an old version of the docs.

Although it may be a little more work you can always pull down version 1 and run the docs locally. npm install, npm run dev and it will run a local docs version.
