### ISSUE TITLE
2.0 Access from original select element

### ISSUE THREAD

**Issue by Lycain** [brianvoe/slim-select#373]
In the documentation we can found this [here](https://slimselectjs.com/settings#select) : 
```js
new SlimSelect({
  select: '#selectElement',
  // or
  select: document.querySelector('#selectElement')
})

// If you already have a currenlty running SlimSelect but lost the reference to it.
// You can access from the original select element.
let el = document.querySelector('#selectElement')
el.slim.open() // Or any other options/methods
```

But as of 2.0 this no longer works due to the fact that the ID on the origianl Select element is overrided by slim-select.
I would like to know if it is a bug or is intended in 2.0 ?
And if is intented, is there a way to keep the original select element ID ?

**Comment by coolibry** [comment]
hello, 
we allready find solution :
in slimselect.js at line 1369
```
if (id) {
     this.select.dataset.ssid = id;
} 
```

**Comment by Lycain** [comment]
Okay thank you :)

**Comment by brianvoe** [comment]
This fix will go in the next release. Slim Select will no longer replace the id on the original select. Lets hope this makes the most sense.

**Comment by brianvoe** [comment]
v2.3.1

**Comment by brianvoe** [comment]
Let me know if this fixes everything for you. Sorry i didnt fully understand the issue.

**Comment by coolibry** [comment]
solution is ok, 
id is not anymore replaced.

**Comment by brianvoe** [comment]
Glad to hear. Nice job!
