### ISSUE TITLE
Position of options gets stuck when searching

### ISSUE THREAD

**Issue by MysterDru** [brianvoe/slim-select#376]
**Describe the bug**
When `openPosition` is `auto` or `up` and search is enabled, once results are filtered the dropdown appears to be "floating", or stuck in its original position. 

The search input and top position of the content stays in its position, even though the size of the list/options is smaller.

To reproduce:

- Force the options list to appear above the select, either using `up` for openPosition or shrinking the viewport.
- Perform a search on the list to filter results
- Note the position of the search input & options list. Depending on the size of the option list, the gap or "floating" space is significant.

**Screenshots**

Screenshots provided from both the documentation site, and within my application

![image](https://user-images.githubusercontent.com/455639/204917457-53d31997-4628-46cd-a986-82718ad2371d.png)

![image](https://user-images.githubusercontent.com/455639/204918278-bf8ef856-a146-4c54-afff-eba281b4281d.png)

![image](https://user-images.githubusercontent.com/455639/204918315-7e16089b-09e6-4a9c-bbdc-6b68d20019bd.png)

**Comment by brianvoe** [comment]
Ya this is a good catch. I think i have a simple fix for it. Basically if its shown above reverse order of the search and options. So search shows at bottom when options are show above.

**Comment by MysterDru** [comment]
I think that would be a good fix and work well!

**Comment by brianvoe** [comment]
I fixed this and will go out with the new release hopefully today

**Comment by brianvoe** [comment]
It may jump back and fourth depending on its available size it can fit into but I think this works a little better than before.

released 2.3.0
