### ISSUE TITLE
Scrolling while focused on search input causes endless flicker

### ISSUE THREAD

**Issue by MysterDru** [brianvoe/slim-select#377]
**Describe the bug**

- Enable search
- Set the openPosition to `auto`
- Change the viewport of the browser window to force the options & search to appear above the select. This is most easily done by having the dropdown visible just above the bottom of the viewport. There needs to be content below the viewport that can be accessed by scrolling
- Focus on the search input. 
- Scroll the the page while the options list is open
- Note the options list drops to the down position on the select
- Now scroll the page to put the select back just above the bottom of the view port.
- The page now starts to go crazy but appearing to position the open dropdown correctly.

**Screenshots**
![Nov-30-2022 16-12-08](https://user-images.githubusercontent.com/455639/204919405-10b637ac-d862-4c4f-8dda-8322594aa25c.gif)

**Comment by brianvoe** [comment]
Another good catch! Ill see if i can understand how this is happening.

**Comment by brianvoe** [comment]
I found a fix for this. Basically better calculation to determine the available space between where you put the content.

This will go out in the next release. Thanks for helping find this issue!!!

**Comment by brianvoe** [comment]
released 2.3.0
