### ISSUE TITLE
Include_blank option bug

### ISSUE THREAD

**Issue by mateuszbialowas** [brianvoe/slim-select#378]
**Describe the bug**
I set an empty value for one option. Then I select volvo option and I get volvo. Correct!
Then I choose all option(which I set empty string for this) and I get in return string "All"
I expect to return empty string as I set in value. 
**Screenshots** and example code
https://jsfiddle.net/hq9dwcjf/48/
![image](https://user-images.githubusercontent.com/58574619/204943857-03a163c3-3704-4515-9a65-f600523c67d3.png)
![image](https://user-images.githubusercontent.com/58574619/204943906-4bac8830-b13e-4098-80e0-c17df191f4de.png)
![image](https://user-images.githubusercontent.com/58574619/204943998-b9f5b16c-c642-405f-b92d-ed39c2a365ee.png)
![image](https://user-images.githubusercontent.com/58574619/204944168-18557b46-bc62-4496-b4ae-f326a5faced2.png)

**Comment by mateuszbialowas** [comment]
I found what I need to change 
![image](https://user-images.githubusercontent.com/58574619/204949494-7e482ad5-728f-4684-abef-5fb358f63bff.png)

**Comment by brianvoe** [comment]
You are 100% right!!! Nice catch!

Do you want to do a simple pr and take the credit or do you just want me to tackle it?

**Comment by mateuszbialowas** [comment]
I can do a simple PR. Thank you :)

**Comment by brianvoe** [comment]
released 2.3.0
