### ISSUE TITLE
Multi-select doesn't accept disable()

### ISSUE THREAD

**Issue by goryllaz** [brianvoe/slim-select#379]
When I tried to disable slim select, I was still able to select items.
![Záznam obrazovky 2022-12-01 v 12 58 02](https://user-images.githubusercontent.com/7353665/205049485-de31b125-b4ef-4bb9-88d4-e933dda04dc6.gif)

**Comment by brianvoe** [comment]
You are right on this! I already have a fix for it. It will be released in the next update.

P.S. I also added the ability to set disabled on your select and it will disable automatically instead of just method calls.

**Comment by brianvoe** [comment]
released 2.3.0
