### ISSUE TITLE
How to count select tag 

### ISSUE THREAD

**Issue by khoapercy** [brianvoe/slim-select#38]
Hi author ,
How to I can count select tag after click more 30 option .
It's very long string tag 
Can I display sum of number select tag like : (30 selected) on input
Thank and best regards

**Comment by brianvoe** [comment]
Oh that is an interesting idea. I could add the ability to have show a numerical value if value length is more than 30. That being said i feel like there might be more of an issue if someone is selecting more than 20 items. can you send a screen shot of the issue you are having?

**Comment by khoapercy** [comment]
Hi author ,
I send for you 2 image 
In the first image  I want slim-select have select all button and show result counted on input 
In the  second image I understand why slim-select can not select more 6 option

![btselect](https://user-images.githubusercontent.com/23382299/37759616-b4b8292a-2de6-11e8-983f-0a3a621c2b37.png)
![slimselect](https://user-images.githubusercontent.com/23382299/37759617-b4effa8a-2de6-11e8-8a65-3e02bcfa98ef.png)

**Comment by brianvoe** [comment]
I see what you are going for. What i would suggest is that you can still have your all option and just let that be the value you use. Its doesnt seem necessary to have to select all the options with it. However you use that value is up to you. If you are submitting a form and want/need to send all the values individually you can do that before you submit.

```javascript
function formSubmit() {
    if (select === 'all') {
        // Get all the values you need
    }

    // Submit form here
}
```
