### ISSUE TITLE
Unable to deselect value when maxSelected and allowDeselect provided

### ISSUE THREAD

**Issue by bolinkd** [brianvoe/slim-select#380]
**Describe the bug**
I have a SlimSelect with a maxSelected value of 3 and allow deselect turned on, it all works great until I reach the max selected at which point deselecting from the list items doesnt work and you have to use the items in the input to remove one before continuing

**Screenshots**
![Dec-01-2022 08-18-49](https://user-images.githubusercontent.com/4382804/205104725-397be3c4-e2d9-42d8-8f93-2c9f3e6c5789.gif)

**Comment by brianvoe** [comment]
Good catch! Ill get this fix in today.

**Comment by brianvoe** [comment]
Fixed it. Will go in the next release.

**Comment by brianvoe** [comment]
released 2.3.0
