### ISSUE TITLE
closeOnSelect: false drops search selection

### ISSUE THREAD

**Issue by orlando-labs** [brianvoe/slim-select#384]
Hi, first of all, thanks for your work. I highly appreciate it!

Steps to reproduce:
1. setup the component
```javascript
settings: {
  closeOnSelect: false
}
```
<img width="402" alt="Screenshot 2022-12-02 at 17 14 33" src="https://user-images.githubusercontent.com/73169645/205312458-840c0463-fddf-4915-8dff-1111c0fe7ff4.png">

2. filter options
<img width="410" alt="Screenshot 2022-12-02 at 17 14 40" src="https://user-images.githubusercontent.com/73169645/205312502-f68a3459-bd83-4d11-8f15-bd1a00ab2462.png">

3. select something you want
<img width="392" alt="Screenshot 2022-12-02 at 17 14 47" src="https://user-images.githubusercontent.com/73169645/205312549-c187ac9c-e095-4345-a4e6-58aff36a2b47.png">

Here it is! The filtered options became unfiltered. This is especially frustrated with huge lists of options when I want to choose several previously filtered options (this is the while point of the usage of closeOnSelect setting)

**Comment by brianvoe** [comment]
released 2.3.0
