### ISSUE TITLE
Button/Link inside disabled option

### ISSUE THREAD

**Issue by mkuItra** [brianvoe/slim-select#385]
Hello, any ideas what can I do to make a button clickable inside an option. I've created button as `html` key inside option setted by `setData` method

**Comment by brianvoe** [comment]
I dont think that would work as the rendered options constantly get destroyed and recreated.

**Comment by mkuItra** [comment]
Well, then I will try to fork and do it on my own. Are you willing to take a look and add it if I will succeed? In my case I need to put a link that fires product availability notification modal, I think such option would be helpful

**Comment by mkuItra** [comment]
Okey, so basically I think I've achieved my goal, but I've got question - should this funcionality be described by some setting? For now I did this that way but I think if someone put something in  `data-html`, it's intended and should be handled by default. Please let me know what you think

**Comment by brianvoe** [comment]
the more I thought about it. I realized you can just trigger whatever function call you want in the afterChange function and that should do the same functionality your looking for.

**Comment by mkuItra** [comment]
I don't understand tbh, I want to click button which is inside option, doing so I don't want this option be selected

**Comment by brianvoe** [comment]
At a certain point do you still need slim select? If clicking an option doesn't select it and instead run a separate function, is that still in the spirit of a select dropdown?

**Comment by mkuItra** [comment]
Would this thing mess up something? Like, it's really small thing. I don't understand why u make big deal about it. If there are shops with such functionality why not make this available to recreate with slimselect, I just ask for a way to handle a click event on option my way or just handling this by default - which I did.

I really kindly ask you to consider it, Im using your library really long and like it. I don't want to search for another solution.

I can provide some demo, maybe you get me wrong at some point. Please as well keep in mind that Im not a native english so if I wrote something mean it wasn't on purpose.

Thanks in advance

**Comment by mkuItra** [comment]
If clicking an option doesn't select it and instead run a separate function - I just want to make elements such as `a, buttom` inside `div option` clickable, if u click exactly at them, if they are not clicked everything works as always.

So there is dropdown with product sizes, we expand dropdown and if option is disabled it has a button inside, u can't select this option but button remains clickable

**Comment by brianvoe** [comment]
I am here to help with any select needs you have. Unfortunately if you are trying to add a click event callback to a disabled option then I would suggest you might need to rethink how you are setting up your application. But once again if you need help adding functionality that would enhance the select dropdown experience then ill all ears. But this one doesnt seem to be it.
