### ISSUE TITLE
Vue dynamic options

### ISSUE THREAD

**Issue by brianvoe** [brianvoe/slim-select#386]
Slim select handles the underlying select option alterations for you. But the issue is that if you allow Vue to also handle the select option alterations then you will have two things trying to alter the select options and that will cause Vue to error out. 

I am looking for some help on this part. If anyone can help solve this issue an a reasonable way please submit a pr.

**Comment by brianvoe** [comment]
If you can come up with something you would make a lot of people happy!!!

P.S. I have a good amount of people who want the react version as well.

**Comment by blakepell** [comment]
Maybe I'm missing a piece of the problem (or I'm not using a feature where this is an issue).  I got something working for my use case.  I render my SlimSelect using a `v-for` that is looking at an array that's on the `data()`.

```
  <select multiple id="tags" name="Tags" v-model="formData.Tags">
      <option v-for="opt in opts">{{opt}}</option>
  </select>
```

Anytime I push new items into `opts` it re-runs that `v-for` and SlimSelect is seeing it and allowing it to them be selected.  I was using the `addable` function to be able to add tags on the fly and I hooked into that to sync the slim select and Vue.  In Vue3 list I did this:

```
data() {
    opts: ['vue', 'c#', 'react']
},
mounted() {
    let options = this.opts;

    this.slimSelect = new SlimSelect({
        select: '#tags',
        addable: function(value) {
            options.push(value);
            return value;
        }
    });
}
```

**Comment by brianvoe** [comment]
Ya their are a few things that need to be figured out in order to make reactive and the virtual dom work with slim select. I have it working in other projects but it does have a few html based limitations.

**Comment by brianvoe** [comment]
The issue is when slim select tries to update the original select dropdown and then vue tries to updates what elements it thought were there and panics/errors.
