### ISSUE TITLE
Allow dynamic entries on beforeOpen

### ISSUE THREAD

**Issue by rottmann** [brianvoe/slim-select#39]
If beforeOpen returns an array/promise, it should be added dynamically to the list.

I have selects that load the content lists when i open a select.
Currenly i found only your search option to load entries via ajax.

Not all text fields could be changed (e.g. for translation), can you add them to the options?

**Comment by brianvoe** [comment]
I havent tried this yet but you might want to try to use setData(newValues) in the beforeOpen callback with the values you want to display.

**Comment by rottmann** [comment]
Perfect, thank you!
