### ISSUE TITLE
Empty placeholder is replaced with default placeholder text

### ISSUE THREAD

**Issue by nothrem** [brianvoe/slim-select#396]
**Describe the bug**
When I want to display normal select or Slim Select with no (empty) placeholder (e.g. for use of Floating labels such as https://www.w3schools.com/bootstrap5/bootstrap_form_floating_labels.php ), I create first option with empty value and empty text. However after conversion to Slim Select default placeholder "Select Value" is displayed.

Possibility to have empty placeholder is even mentioned in the [documentation](https://slimselectjs.com/settings#placeholder) (or at least I expect that to be since there is missing verb in the sentense), but there is no demo for that.

**Screenshots**
![Expected no placeholder](https://user-images.githubusercontent.com/1538047/206120426-8e490a15-da22-4b6f-b7d4-3b18adc2ab1f.png)

**Live demo:**
[JS Fiddle](https://jsfiddle.net/nothrem/o912rgdy/9/)

**Example code:**

```
<link href="//unpkg.com/slim-select@2.3.0/dist/slimselect.css" rel="stylesheet">
<script src="//unpkg.com/slim-select@2.3.0/dist/slimselect.min.js"></script>
<label for=agree>I have read the T&amp;C...</label>
<select id=empty_placeholder_demo name=agree required=required>
  <option data-placeholder=true></option><!-- no placeholder -->
  <option value=1>Yes</option>
  <option value=2>No</option>
</select>
  
<button id=convert>Convert to Slim Select</button>
```

```
document.getElementById('convert').addEventListener('click', () => new SlimSelect({
    select: '#empty_placeholder_demo',
    settings: {
        placeholderText: '' //no placeholder
    }
}));
```

(Floating label handler not included in the demo to make the unwanted placeholder visible. Convert button used to show how native label works without placeholder.)

**Hint:**
I expect somewhere in the code something like this:
```
if (!$('option[data-placeholder]').val() && !this.settings.placeholder) {
    //use default placeholder
}
```
... which incorrectly evaluates empty placeholder as non-existing placeholder. But I did not study the code yet (since I'm not familiar with TypeScript).

**Workaround:**
Set the placeholder option's text to hard empty space or other non-empty but invisible text:
```
<option data-placeholder=true>&nbsp;</option><!-- no placeholder -->
```

**Comment by nothrem** [comment]
Works with empty placeholder in settings: https://jsfiddle.net/nothrem/o912rgdy/13/

Does **not** work with empty value in option (without settings): https://jsfiddle.net/nothrem/o912rgdy/16/

**Comment by nothrem** [comment]
Another related problem (though not directly caused by SlimSelect):
When I want to style the select for a framework (e.g. Bootstrap) and set `font-size` and `padding` to element `ss-placeholder`, it does not correctly size when the element is empty (i.e. `placeholderText` is empty string) and changes layout of the select.
In that case, it would be better to fill `&nbsp;` instead of empty string to allow the browser to correctly apply `font-size` and `padding` to the select - either do it automatically in SlimSelect or at least mention that in documentation.

**Comment by brianvoe** [comment]
If the option value is empty then it uses default. You should be able to set it to '  ' empty string with some space and it should empty it out them cause its not value === ''

the font sizes and stuff are maintained by global css variables. change the css variable and you should be good. You are correct that it needs documentation.
