### ISSUE TITLE
Select dropdown gets stuck on Android browsers

### ISSUE THREAD

**Issue by nothrem** [brianvoe/slim-select#397]
**Describe the bug**
When opening the Slim Select on android device with software keyboard (keyboard app), when Search field has focus and keyboard is opened, after selecting a value or losing focus, the select's dropdown closes, then immediatelly reopens and stays opened. Then another select can be opened and the same happens. The opened dropdown still works and selects values into the select. When value is deleted from multi-select, the dropdown is also updated (value is deselected). When clicking the select again, it's search field gets focus again and opens the keyboard again.

This does not happen when hardware (physical) keyboard is attached and the software keyboard does not open! Also does not happen when other way of text input is available (e.g. when using S Pen on Samsung devices that support handwriting into inputs). Does not happen with Slim Select without Search field. -> problem is caused by something that happens when SW keyboard is opened or closed.

Reproduced on demo selects in [documentation](https://slimselectjs.com/settings#placeholder) on devices:
* Samsung Fold 3, Android 13, Chrome 107 / Firefox 107, preinstalled Samsung keyboard
* Samsung Tab S8, Android 13, Chrome 107 / Firefox 107, preinstalled Samsung keyboard
* Xiaomi Mi 9 SE, Android 10, Chrome 108, preinstalled keyboard

**Screenshots**
As you can see, the focus is on selected word "placeholder", but both selects are still opened:

![Screen_Recording_20221207_111250_Chrome_slimselect mp4_snapshot_00 28 182](https://user-images.githubusercontent.com/1538047/206156242-955276f8-cd2a-4211-9831-c7946714b78a.jpg)

https://user-images.githubusercontent.com/1538047/206156271-4e6c914e-b6a8-491d-9381-417e05001e45.mp4

**Workaround**
In afterClose event, search for the related dropdown and close it again.
```
let 
    mySelect = document.getElementById('#mySelect'),
    mySelectId = $(mySelect).attr('id')
;
new SlimSelect({
    select: mySelect,
    events: { 
        //when the Slim Select is supposed to close itself...
        afterClose: () => setTimeout(() => 
            //... search dropdown with same id as the original select...
            $('.ss-content[data-id="' + mySelectId + '"]')
                //...and remove the classes that makes it display as opened
                .removeClass('ss-open-below ss-open-above'),
            1) //use asynchronous handler to solve the execution order problem
    }
});
```
Workaround is not nice, because the dropdown will close, open and close again, but it at least does not block other fields below the select.

**Comment by brianvoe** [comment]
This is an interesting one. I havent tested too crazy on actual phone devices. Ill try to think of a game plan for this. If you have any suggestions please either point out as best as possible or submit a pr.

**Comment by timersys** [comment]
I can confirm this. On my iphone it works great. My friends with Samsung cannot close the dropdown when clicking on any element of the list. Attached is a video demonstrating the issue

https://user-images.githubusercontent.com/1206915/208268466-c5d1dadd-ea25-41ce-8c5d-2d6961583ffb.mp4

**Comment by brianvoe** [comment]
I suppose it could be. Ill try to keep looking into this

**Comment by AzA-95** [comment]
This pr https://github.com/brianvoe/slim-select/pull/424 fix this

**Comment by brianvoe** [comment]
released v2.4.0 let me know if this fixes it for you.

**Comment by AzA-95** [comment]
This is not fixed.

See video https://www.veed.io/view/9e2f1fbb-92a7-44c0-882e-bda2ff791f5b?sharingWidget=true&panel=share
The second link to the video https://www.uploadlite.com/d/FjwkJretyIH1XX If the video on the www.veed.io service has been deleted. On the veed.io service, the video is stored for only a day if upload a video without registration
I can't attach this video to github because the video is over ten megabytes

**This PR [#424](https://github.com/brianvoe/slim-select/pull/424) fix it but he hasn't been merge yet**

**Comment by brianvoe** [comment]
I did another release this morning. let me know if it worked for you.

**Comment by AzA-95** [comment]
Yes it's correct work now. Thanks.

short-video.mp4…

**Comment by brianvoe** [comment]
Glad to hear! Nice job!
