### ISSUE TITLE
Unable to determine if dropdown is part of another div

### ISSUE THREAD

**Issue by bolinkd** [brianvoe/slim-select#398]
**Describe the bug**

I am currently having an issue where we are unable to determine if a slim-select dropdown being clicked is part of another div.

Given the image below, we have a slim-select dropdown inside a flyout menu (uses stimulus and tailwind for the other components)

On the flyout we have a listener that checks for click events and then sees if the clicked target is a child of the "open" flyout, if it is not then the flyout will close. 

Seeing as the "ss-content" section of a slim-select dropdown is attached to the body element, we are unable to determine if the content clicked is a "child" of the flyout.

we currently have this hack in place to prevent this from happening
```js
  _addDropdownEventListener() {
    // Prevent external flyouts/dropdowns from closing when clicking on the search area or list content
    const dropdownElement = this.slim.render.content.main;

    dropdownElement.addEventListener('click', (event) => {
      event.stopPropagation();
    });
  }
```
but I was wondering if you would be willing the move the "ss-content" elements to be adjacent to their respective selects

**Screenshots**
![Screen Shot 2022-12-07 at 19 12 08](https://user-images.githubusercontent.com/4382804/206347050-b6086f96-25cd-4c02-a2d6-9efa24e9f438.png)

If the issue is a visual issue and doesnt have a screenshot that will make me sad.

**Comment by brianvoe** [comment]
https://slimselectjs.com/settings#contentPosition

**Comment by bolinkd** [comment]
missed that part, thanks for the link!
