### ISSUE TITLE
Provide demos

### ISSUE THREAD

**Issue by mburakerman** [brianvoe/slim-select#4]
Hi.
I really liked  slim-select. It's light and clean but didn't fully understand how to use it.
If you provide us jsfiddle or codepen demos, it would be better to play with it.

Also, why [this ](https://jsfiddle.net/q4v2Lhmx/) does't work?

**Comment by brianvoe** [comment]
Looks like jsfiddle doesnt like direct links to files in github. I updated it. I can update docs to show different ways of installing.

https://jsfiddle.net/q4v2Lhmx/3/
