### ISSUE TITLE
Arrow is missing if placeholder is larger than field size

### ISSUE THREAD

**Issue by diderich** [brianvoe/slim-select#404]
**Describe the bug**
_Actual output_
If the placeholder plus the arrow of a field is larger than the field size, the arrow (to the right), indicating that this is a select box, is missing/hidden.

_Expected output_
An arrow (eventually with 10% transparency) is shown on top of the placeholder data to indicate this is a select box.

_Code excerpt_
```html
<select name="rtc-name-support-language" id="rtc-id-sel-support-language">
    <option data-placeholder="true"></option>
    <option name="en-US">English (United States</option>
</select>
```

```javascript
var langSel = new SlimSelect({ select: '#rtc-id-sel-support-language', settings: { placeholderText: 'Select your preferred language' } });
```

**Screenshots**
Screen shot when there is sufficient space to display the full placeholder:
![ok](https://user-images.githubusercontent.com/10230144/207288188-dd2e3e25-3c0e-42d6-9833-e5f501c62eb0.png)

Screenshot when there is not enough space to display the full placeholder:
![ko](https://user-images.githubusercontent.com/10230144/207288293-e67aa253-7ba4-4fae-bc5a-549181a5ea69.png)

**Comment by brianvoe** [comment]
I noticed this too. I have a fix for it. Ill try to get it out in the next release
