### ISSUE TITLE
[Feature Request] Define separate color for :focus attribute

### ISSUE THREAD

**Issue by diderich** [brianvoe/slim-select#405]
Currently the color of the `box-shadow` used to signal that a selector is in `:focus` is identical to the primary color configured, ie., `--ss-primary-color`.

It would be great if there would be a separate color, eg., `--ss-focus-color` for styling the focus box shadow. 

My **use case** is that I prefer to style the focus shadow using the color of the border color, rather than the hover/primary color. Having an additional color to configure would allow the user to select either your (primary color) or my (border color) or any other color approach.

_Complexity_: This should be easy to implement and would not materially increase the number of color constants configured.

**Comment by brianvoe** [comment]
I agree with this. Ill try to get this in the next release.

**Comment by brianvoe** [comment]
added - will go out in next release
