### ISSUE TITLE
[Bug] Wrong focus when moving between two SlimSelects

### ISSUE THREAD

**Issue by diderich** [brianvoe/slim-select#408]
**Describe the bug**
I have two SlimSelect selectors next to each other. When I select the first one, it goes in `:focus`. But when I click on the second one, the focus selector stays on the first one, as shown in the figure, rather than switching to the search box of the second selector (as I would expect).

I have seen this issue in: Windows Firefox, Windows Edge, iOS Safari

**Screenshots**
![wrong-focus](https://user-images.githubusercontent.com/10230144/207556958-5ad726d0-f533-4837-8600-1f3fdfe32c98.png)

**Comment by brianvoe** [comment]
hmm not sure about this one. Ill have to set it up and test is. if you could setup a codepen with this template that would help. https://codepen.io/brianvoe/pen/MWXqXXV

**Comment by diderich** [comment]
You can see the issue on your page.

![image](https://user-images.githubusercontent.com/10230144/207692742-a8cbc912-c911-45a7-af27-5a9a04224bcb.jpeg)

**Comment by brianvoe** [comment]
Ya i see it clearly now. I get this on the list of todo. Please feel free to contribute with a pr if you are able to.

**Comment by AzA-95** [comment]
This pr https://github.com/brianvoe/slim-select/pull/420 should fix this issue

**Comment by AzA-95** [comment]
@brianvoe This is fixed after merge this pr [#420](https://github.com/brianvoe/slim-select/pull/420)

Can you close this issue
