### ISSUE TITLE
[Bug] First selector does not always close when opening second one

### ISSUE THREAD

**Issue by diderich** [brianvoe/slim-select#409]
**Describe the bug**
I have two SlimSelect selectors next to each other. Sometimes (I have not been able to reproduce it systematically, but it happened more than once), the two selectors remain open.

Seen in browser: Windows Firefox.

_**Note:** I am reporting this (although I cannot systematically reproduce the issue) for the case that you may have an idea, where this can come from. If I get more information to systematically reproduce what I have observed, I will add to the issue._

**Screenshots**

![two-popups](https://user-images.githubusercontent.com/10230144/207557877-c10333f8-81c8-4547-9774-ba4f9e745aee.png)

**Comment by brianvoe** [comment]
Ok i think i can see how that would happen. Looks like it might be a propagation issue. Basically there are click handlers that I believe prevent default and prevent propagation. and because of that it doesnt propagate to the document which has a click handler that if clicked would close SlimSelect

**Comment by AzA-95** [comment]
This pr https://github.com/brianvoe/slim-select/pull/420 also may be fix this issue. I also had this strange behavior. After change code this strange behavior disappeared.

**Comment by AzA-95** [comment]
@brianvoe This is also was fixed

Can you close this issue
