### ISSUE TITLE
Vue - loosing selection on options update

### ISSUE THREAD

**Issue by BlackDrakex** [brianvoe/slim-select#410]
When options list, passed as data prop, changes in any way, even is it's just a new array of the same items, SlimSelect component triggers `update:modelValue` with value of the first option(or empty array, if multiple), be it placeholder or not. This leads to v-model updating the variable with incorrect value.

**Comment by brianvoe** [comment]
I think i believe you cause it sounds plausible. But please help me out and give me something i can recreate codepen or jsfiddle would be nice.

**Comment by BlackDrakex** [comment]
There is a problem with providing an example. `modelValue` prop validation has an incorrect type(undefined) which causes example to crash if using v-model before described behavior can be seen. Anyway here is an example: [https://codesandbox.io/s/withered-rgb-0fq257?file=/src/App.vue](Пример)

**Comment by brianvoe** [comment]
The link didnt work for me

**Comment by BlackDrakex** [comment]
> The link didnt work for me

Fixed the link now. Also fixed an example with `v-model`. It fails if `modelValue` is anything other than a string or an array.

**Comment by brianvoe** [comment]
So correct me if im wrong. Even if the options are the "same" which as soon as you select something the options wont be the same anymore cause one of the options will be selected="true". Then if you set the data with options and none of them are selected then it will default to the first option for single select cause that's how the original select works. So to me this works as expected. But help me understand if im missing something

**Comment by BlackDrakex** [comment]
You are absolutely correct if you think in terms of default browser implementation. But! Here we are working with Vue and it's own reactivity system. From the component user perspective options is an array passed to `data` prop and it changes after some event triggers. While selected option is `modelValue` prop value and it does not change. 
In my opinion `selected` attribute not being synched with `modelValue` prop on options change is an error.
So, expected behavior for me is to update options with a new array, then find option, if any exists, with value equal to `modelValue` and set it as selected.

**Comment by brianvoe** [comment]
I dont disagree with you. That being said a decent amount of work is to mimic the actions like the original select does.

See example https://codepen.io/brianvoe/pen/GRGVYOJ?editors=1010

With that being said if you can put together a vue demo that shows it keeping the value even when the options change(granted it has that value in one of the options) then I will update the vue integration to mimic how vue works. I think thats a fair tradeoff.

**Comment by BlackDrakex** [comment]
> I dont disagree with you. That being said a decent amount of work is to mimic the actions like the original select does.
> 
> See example https://codepen.io/brianvoe/pen/GRGVYOJ?editors=1010
> 
> With that being said if you can put together a vue demo that shows it keeping the value even when the options change(granted it has that value in one of the options) then I will update the vue integration to mimic how vue works. I think thats a fair tradeoff.

I will try to, but at a later date.
