### ISSUE TITLE
When clicked by tapping the trackpad, slim-select opens and immediatly closes again.

### ISSUE THREAD

**Issue by Shoplifter** [brianvoe/slim-select#411]
When clicked by tapping the trackpad, slim-select opens and immediatly closes again. (with one tap only)
This does not happen when I use the mouse button to click.
It also does not happen, when slim-select is already focussed before.

This occurred on both of my laptops (Asus, Dell, both with Windows 11)

**Comment by brianvoe** [comment]
I dont know if this is a slim select issue unless you can provide better reproducible evidence i can see for myself. I have a few different laptops and this isnt happening to me.

**Comment by esedic** [comment]
I can confirm the issue, see example here: https://jsfiddle.net/esedic/Lbcrjphn

Win 10 on Chrome

**Comment by esedic** [comment]
It seems that this is happening, if you click on the slim-select dropdown as the first action after page load, so there is no focus elsewhere.

If you first click on some other element (in my example body background) and after that you click slim-select dropdown, it works normally.

**Comment by Shoplifter** [comment]
@esedic Thank you for the jsfiddle
I experienced it in Chrome, Edge and Firefox and reliably redproucable.
It works, if slim-select is already focussed, otherwise it does not.
for what its worth: If I quickly hover the option list before the initial openening animation is finished, it's also working (does not close again)
@brianvoe If you cannot reproduce: It looks nexactly like in the video posted [here](https://github.com/brianvoe/slim-select/issues/359).

**Comment by brianvoe** [comment]
Ok I will try to see if i can wrap the open state in a debounce or something. Might need to do a reverse debounce considering we want to the action to call right away and not again for 100 ms or something.

**Comment by AzA-95** [comment]
This pr should fix this https://github.com/brianvoe/slim-select/pull/424

**Comment by brianvoe** [comment]
Ill be doing a release today.

**Comment by brianvoe** [comment]
released v2.4.0 let me know if this fixes it for you.

**Comment by Shoplifter** [comment]
Thank you @brianvoe  and @AzA-95 for fixing this.

**Comment by brianvoe** [comment]
It was all @AzA-95!!! He has been doing great tackling some of the things even I had issues with.
