### ISSUE TITLE
Select inline styles

### ISSUE THREAD

**Issue by gmq** [brianvoe/slim-select#412]
**Describe the bug**
The inheritance of the inline styles of the `select` seems to be broken. 

**Screenshots**
From the docs:
![image](https://user-images.githubusercontent.com/472791/208525513-1bd6b8cf-94dc-4247-9198-4c9a8b663d0d.png)

**Comment by brianvoe** [comment]
Thanks ill look into it

**Comment by jczanfona** [comment]
Is this the reason i can't put it in the same line?

![image](https://user-images.githubusercontent.com/46503049/211530533-5266fe7c-0c8b-426e-bfcb-6d90998b8879.png)

**Comment by jczanfona** [comment]
Oh, excuse me....`display: inline-flex;` is my solution.

TX a lot in any case 😊
