### ISSUE TITLE
Question: Why does setting the data using the 'data:' option trigger a change event

### ISSUE THREAD

**Issue by diderich** [brianvoe/slim-select#413]
I am creating a `new SlimSelect` using the `data:` option to pass html formatted data.
I am tracking the `change` event to find out whether or nor the user has changed any input on my form.
When I create the `new SlimSelect` objects using `<select> <option>xxx</option> ... </select>`, no change event is triggered.
But when creating a `new SlimSelect`object passing the data through Javascript / `data:`, rather than through html / `<option>`, a change event is triggered.
Is there a reason for triggering that event? Is there a way to prevent it?

**Comment by brianvoe** [comment]
I think you bring up a good point. I think this would be easy enough to setup a non no change call.
