### ISSUE TITLE
No close "x" button on multiple select

### ISSUE THREAD

**Issue by Boorrito15** [brianvoe/slim-select#415]
**Describe the bug**
There isn't a close or "x" button next to the selected options to deselect them. The functionality works and I am able to deselect the options I selected, it's just a visual issue.

**Screenshots**
![image](https://user-images.githubusercontent.com/114331474/210181237-a33333f6-2de2-4da3-a407-da13c5e85ab8.png)

If the issue is a visual issue and doesn't have a screenshot that will make me sad.

**Comment by brianvoe** [comment]
Ive seen this once before on an older version. I thought i fixed it. But i feel like I am missing something cause it looks like you have other css issue with your down arrow on the far right.

**Comment by Boorrito15** [comment]
@brianvoe I'm adding this onto a simple form. Could that be why the close button isn't showing?

**Comment by brianvoe** [comment]
just from first glance it seems like some other css is effecting it.
