### ISSUE TITLE
[Mobile] The keyboard always show up on mobile even with {showSearch: false}

### ISSUE THREAD

**Issue by sidati** [brianvoe/slim-select#42]
Hi @brianvoe , 
If you open http://slimselectjs.com/options on your phone and open the `showSearch:false` example, the keyboard shows up which is unpredictable behavior. it seems you just hide the search field without disabling the focus event 😄.

Thanks for the great plugin and i hope you fix this issue ;)
Have a great day

**Comment by brianvoe** [comment]
Great catch! Ill look into this tonight and see if i can get mobile to not tigger keyboard. If you happen to know im all ears otherwise ill have to dig into this.

Thanks

P.S. If you really like it please give it a star. It really helps get it noticed more

**Comment by sidati** [comment]
Just curious 🤔, why not ignore search when is disabled ?
https://github.com/brianvoe/slim-select/blob/master/src/slim-select/slim.ts#L308
``` js
searchDiv (): search {
   if (!this.main.config.showSearch) {
      return;
   }
    var container = document.createElement('div')
    container.classList.add(this.main.config.search)
    ...
}
```

**Comment by brianvoe** [comment]
So the reason is because i use that input field to add key event listeners so you can still us the up and down arrows to search through the options list

**Comment by brianvoe** [comment]
yes

**Comment by sidati** [comment]
Mmmh then this is a funny situation 😀 
Why not changing your approach and instead of listening to the field you can listen to the window/document and navigate throw the **OPENED** SlimSelect, in this case we will need a global variable contains the opened SlimSelect object ??

**Comment by brianvoe** [comment]
I understand where your coming from but unfortunately that doesnt work.

**Comment by brianvoe** [comment]
Added this and will be available in the next release

**Comment by sidati** [comment]
Thanks 💯
