### ISSUE TITLE
Don't distinguish between accented vowels or not

### ISSUE THREAD

**Issue by jczanfona** [brianvoe/slim-select#421]
Excuse me, I have a doubt, in the same way the search engine does not differentiate between upper and lower case letters, how can I set do not distinguish between accented vowels or not, so that when writing `a` it finds the occurrences like `Á á A a`

Thanks in advance.

**Comment by brianvoe** [comment]
https://slimselectjs.com/events#searchFilter

**Comment by jczanfona** [comment]
Thank you very much for the reply !!
I have looked into it and this works although now it is case sensitive.
```
				<script>
					new SlimSelect({
						select: '#selectElement',
						events: {
							searchFilter: (option, search) => {
							  return option.text.normalize("NFD").replace(/[\u0300-\u036f]/g, "").indexOf(search.normalize("NFD").replace(/[\u0300-\u036f]/g, "")) !== -1
							}
						}
					})
				</script>
```

**Comment by jczanfona** [comment]
Solved adding `.toLowerCase()`

`return option.text.normalize("NFD").replace(/[\u0300-\u036f]/g, "").toLowerCase().indexOf(search.normalize("NFD").replace(/[\u0300-\u036f]/g, "").toLowerCase()) !== -1`

Thanks a lot fot your sw @brianvoe

**Comment by brianvoe** [comment]
Glad that helped
