### ISSUE TITLE
Deselect with keyboard

### ISSUE THREAD

**Issue by jczanfona** [brianvoe/slim-select#422]
Excuse me, I don't know how to deselect items with the keyboard. I can go through the list with the arrows and with `Enter` select items... What do I have to do to remove that selection with the keyboard?

Thanks in advance!

**Comment by brianvoe** [comment]
Just hit enter again

https://slimselectjs.com/settings#allowDeselect

**Comment by jczanfona** [comment]
Perfect! Really great, thanks a lot.

And how can I accept the values (if it's not already displayed) with `Enter` instead of putting a `Submit` button?

**Comment by brianvoe** [comment]
Im not sure i follow. Please just look throughout all the docs and try work things out. I believe in you.

**Comment by jczanfona** [comment]
Sorry to bother you again, but I've read everything and I don't see anything that could be related to this.

The problem is that with `SlimSelect` the form does NOT take the values when pressing `Enter` , as it does with any classic listbox or inputbox, without needing to hit the `Submit` button.

Have I explained myself well now?

**Comment by brianvoe** [comment]
I think i see your issue. the issue for you might be that because SlimSelect sets the original select dropdown to display none.  Normal html forms I believe wont send hidden fields. If that is the case then just update the original select to visibility:hidden and position:absolute instead.

If anything just test first that thats the issue.

**Comment by jczanfona** [comment]
I've tested it.

You can do it also if you want.
Here is a very simple file `a.php`

```
<html>
	<head>
		<script src="slimselect.min.js"></script>
		<link href="slimselect.css" rel="stylesheet"></link>
	</head>
	<body>
		<?php 
		if (!$_POST){ 
		?> 
			<form action="a.php" method="POST"> 
				A.- Options standard: <br> 
			    <select name="selec" size ="2"> 
			       <option value="1">One</option> 
			       <option value="2">Two</option> 
			    </select><br> 
			    <input type="submit" value="Send" > 
			</form> 
			<hr>
			<form action="a.php" method="POST"> 
				B.- Options slimselect: <br> 
				<select name="selec" size ="2" id="selectElement"> 
				   <option value="1">One</option> 
				   <option value="2">Two</option> 
				</select><br>
				<script> new SlimSelect({select: '#selectElement'})</script> 
				<input type="submit" value="Send" > 
			</form> 
		<?php 
		}else{ 
			echo "Option value: " . $_POST["selec"]; 
			echo "<br><a href='a.php'>Repeat</a>"; 
   		}
		?>
	</body>
</html>
```
With **A option** you can select and hit `Enter` but with **B option** you can't. Since you do not press the `Send` button, it does not send.

**Comment by jczanfona** [comment]
Have you tried it @brianvoe?
