### ISSUE TITLE
Bootstrap Modal - MainContentDIV no focus

### ISSUE THREAD

**Issue by pieewiee** [brianvoe/slim-select#425]
when placing the Slimselect in a [bootstrap Modal](https://getbootstrap.com/docs/5.0/components/modal/) the mainContentDiv is not focusable due to the fact that it gets appended to the Body.

--> this.contentLocation = settings.contentLocation || document.body;

fixed that by appending it in same hierarchy (main.main / combobox)

Are there any side effects which i am not Aware of?

**Comment by brianvoe** [comment]
nope

**Comment by pieewiee** [comment]
cool - thank you for the quick repsonse :-)

**Comment by jerryclinesmith** [comment]
@pieewiee Can I get more details on your setup that fixed the issue?  I'm still having a problem with Bootstrap Modals.  If I set the contentLocation to '.modal-body', '.modal-dialog', or even 'form' then the slim-select is focusable, but the contents show up misaligned (either well below the select, or also off to the right).  If I don't set contentLocation, then the control is not focusable.
