### ISSUE TITLE
Space key is not registered while searching .

### ISSUE THREAD

**Issue by gospodinpopara** [brianvoe/slim-select#426]
There is a bug in SlimSelect (v.2.4.1) search field, space key is not registered while searching .
It only happends on desktop, mobile works perfectly fine.

**Comment by brianvoe** [comment]
Slim Select trims the search string before searching and if its empty it wont do anything. Unless im missing something this is intentional.

**Comment by gospodinpopara** [comment]
@brianvoe It's my bad i didn't explane it in details. 
When you have select and dropdown list with search field ( so u can search through the list), when i'm searching for list values space on keyborad is not registered. (i tested it on multiple laptops and it doens't work) . [https://ibb.co/YfNfTnZ](url)

**Comment by brianvoe** [comment]
https://github.com/brianvoe/slim-select/issues/427

Lets continue this conversation here please
