### ISSUE TITLE
Unable to type a space in the search field

### ISSUE THREAD

**Issue by StrutTower** [brianvoe/slim-select#427]
Unable to type a space in the search field on Firefox 108 and Edge 109. I've run into this on the documentation examples and when using Slim Select on my own site. Pasting in text with a space works and the filtering works properly. Is there a setting I'm missing that allows spaces?

**Comment by StrutTower** [comment]
Based on the comments in #426 it sounds like the trailing space is getting removed right after typing it. It seems like the space should be ignored in the filtering but the text in the search field shouldn't be updated to remove the space so something can be typed after it.

**Comment by brianvoe** [comment]
@AzA-95 Looks like a recent pr possibly caused this issue. Can you take a look at it and let me know if any changes of the switch statement effected this?

**Comment by AzA-95** [comment]
This bug was added by this pr https://github.com/brianvoe/slim-select/pull/418

**Comment by AzA-95** [comment]
For fix this bug remove this line https://github.com/brianvoe/slim-select/blob/master/src/slim-select/render.ts#L697 on code

**Comment by AzA-95** [comment]
This bug in this line https://github.com/brianvoe/slim-select/pull/418/commits/75ae7a41816d32a3deb01faacae640c59d6afd78#diff-2409e2db6343b1e6fa9b0c658a204af3c542be5fceae7cacee8c916b1a3312c9R697

**Comment by AzA-95** [comment]
This pr [https://github.com/brianvoe/slim-select/pull/428](428) fix this. I don't include build files. You need run npm run build for build :)
