### ISSUE TITLE
[ERROR] No matching export in "../../node_modules/slim-select/dist/slimselect.umd.js" for import "default"

### ISSUE THREAD

**Issue by francesco-loreti** [brianvoe/slim-select#429]
I have problem with SlimSelect version: ^2.4.0
Not have problem with version 2.3.3

```
[ERROR] No matching export in "../../node_modules/slim-select/dist/slimselect.umd.js" for import "default"

      4 │ import SlimSelect from 'slim-select';
        ╵        ~~~~~~~~~~
```

Thanks and regards
Francesco

**Comment by francesco-loreti** [comment]
Why was it closed? I continue to have the problem. 

If I'm doing something wrong I'd like to know.
Thanks

**Comment by brianvoe** [comment]
v2.4.2

**Comment by felixfischer** [comment]
I have this issue with v2.4.2

**Comment by francesco-loreti** [comment]
me too. the problem isn't solved.

**Comment by brianvoe** [comment]
Ok this build stuff is such a pain. I just merged in a pr for the package json to have browser use a different value. I am open to a pr but i need to proof these merges actually fix it. Ill look at your pr but please give me something I can know is actually going to fix this once in for all. 

Thanks!!!

**Comment by francesco-loreti** [comment]
Unfortunately I'm not an expert in compiling from .ts to .js so I can only change the version in "dist" then how this can be reported within the "src" I don't know, sorry. Maybe I'll learn something :-)

**Comment by felixfischer** [comment]
What worked for me was importing the ES build like so:
`import SlimSelect from 'slim-select/dist/slimselect.es'`

I am importing SlimSelect in a .js file that's bundled with esbuild.

**Comment by francesco-loreti** [comment]
ok, this fix is correct: https://github.com/francesco-loreti/slim-select/commit/761f8dbce17d0316eb3591d82aec3dd514c91425

**Comment by francesco-loreti** [comment]
any news?

**Comment by Shoplifter** [comment]
> What worked for me was importing the ES build like so: `import SlimSelect from 'slim-select/dist/slimselect.es'`
> 
> I am importing SlimSelect in a .js file that's bundled with esbuild.

I am using this workaround with webpack 5 and slim-select 2.4.2
it works, but when I have 
```
"events": {
    "searchFilter": (option, search) => {
        ....
    }
}
````
the searchFilter callback function is ignored

**Comment by francesco-loreti** [comment]
> > What worked for me was importing the ES build like so: `import SlimSelect from 'slim-select/dist/slimselect.es'`

And if you use my solution, have same problem?
`"slim-select": "https://github.com/francesco-loreti/slim-select#fix-429",`

**Comment by Shoplifter** [comment]
> > > What worked for me was importing the ES build like so: `import SlimSelect from 'slim-select/dist/slimselect.es'`
> 
> And if you use my solution, have same problem? `"slim-select": "https://github.com/francesco-loreti/slim-select#fix-429",`

same problem with your solution, except i can build with `import SlimSelect from "slim-select";`

**Comment by ntcherechansky** [comment]
Experiencing same error here:
v2.4.2

[ERROR] No matching export in "../../node_modules/slim-select/dist/slimselect.umd.js" for import "default"

**Comment by francesco-loreti** [comment]
> [ERROR] No matching export in "../../node_modules/slim-select/dist/slimselect.umd.js" for import "default"
You can try my bugfix waiting for the merge
`"slim-select": "https://github.com/francesco-loreti/slim-select#fix-429"`

**Comment by francesco-loreti** [comment]
> ```
> "events": {
>     "searchFilter": (option, search) => {
>         ....
>     }
> }
> ```
> 
> the searchFilter callback function is ignored

Probably, this is a new bug.

**Comment by hww** [comment]
I see the same problem. Could anybody fix it?

```
$ rails assets:precompile 
warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
✘ [ERROR] No matching export in "node_modules/slim-select/dist/slimselect.umd.js" for import "default"

    app/javascript/controllers/slim_controller.js:6:7:
      6 │ import SlimSelect from 'slim-select'
        ╵        ~~~~~~~~~~

1 error
node:child_process:924
    throw err;
    ^

Error: Command failed: /home/valery/projects/veda/tc-tech-server/node_modules/@esbuild/linux-x64/bin/esbuild app/javascript/application.js app/javascript/jquery.js --bundle --sourcemap --outdir=app/assets/builds --public-path=assets
    at checkExecSyncError (node:child_process:885:11)
    at Object.execFileSync (node:child_process:921:15)
    at Object.<anonymous> (/home/valery/projects/veda/tc-tech-server/node_modules/esbuild/bin/esbuild:220:28)
    at Module._compile (node:internal/modules/cjs/loader:1246:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1300:10)
    at Module.load (node:internal/modules/cjs/loader:1103:32)
    at Module._load (node:internal/modules/cjs/loader:942:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:83:12)
    at node:internal/main/run_main_module:23:47 {
  status: 1,
  signal: null,
  output: [ null, null, null ],
```

**Comment by francesco-loreti** [comment]
> I see the same problem. Could anybody help me to workaround it?
> 
> ```
> $ rails assets:precompile 
> warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
> ✘ [ERROR] No matching export in "node_modules/slim-select/dist/slimselect.umd.js" for import "default"
> 
>     app/javascript/controllers/slim_controller.js:6:7:
>       6 │ import SlimSelect from 'slim-select'
>         ╵        ~~~~~~~~~~
> 
> 1 error
> node:child_process:924
>     throw err;
>     ^
> 
> Error: Command failed: /home/valery/projects/veda/tc-tech-server/node_modules/@esbuild/linux-x64/bin/esbuild app/javascript/application.js app/javascript/jquery.js --bundle --sourcemap --outdir=app/assets/builds --public-path=assets
>     at checkExecSyncError (node:child_process:885:11)
>     at Object.execFileSync (node:child_process:921:15)
>     at Object.<anonymous> (/home/valery/projects/veda/tc-tech-server/node_modules/esbuild/bin/esbuild:220:28)
>     at Module._compile (node:internal/modules/cjs/loader:1246:14)
>     at Module._extensions..js (node:internal/modules/cjs/loader:1300:10)
>     at Module.load (node:internal/modules/cjs/loader:1103:32)
>     at Module._load (node:internal/modules/cjs/loader:942:12)
>     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:83:12)
>     at node:internal/main/run_main_module:23:47 {
>   status: 1,
>   signal: null,
>   output: [ null, null, null ],
> ```

You can try my bugfix waiting for the merge
"slim-select": "https://github.com/francesco-loreti/slim-select#fix-429"

**Comment by hww** [comment]
> You can try my bugfix waiting for the merge "slim-select": "https://github.com/francesco-loreti/slim-select#fix-429"

Great, but I am not sure where to place/modify this expression. Can You give a bit more details?

**Comment by hww** [comment]
Oh I see what you mean. Add this line to the package.json

 "slim-select":"https://github.com/francesco-loreti/slim-select#fix-429",
