### ISSUE TITLE
Addable should accept an object as return.

### ISSUE THREAD

**Issue by avaz** [brianvoe/slim-select#43]
Hi,

Shouldn't the 'addable' function accept an object as return? 
A common use case is that the value of the option usually is different from its text. Like case where we load data from database and the value is a numeric filed and the text, well, is text (string)?

Currently, the addable function is expected to return a text or a boolean, there is a workaround for the case which a new entry on the database on addable and then its id needs to be associated to the new option create?

**Comment by brianvoe** [comment]
I hear what your saying. When i originally added it someone needed it real quick so i didnt have time to add an object based return.

Ill get that in soon and let you know when its done. Do you have a deadline you need to meet?

**Comment by avaz** [comment]
Hi @brianvoe, thanks for the promptly answer.

I do have a deadline but to keep me moving forward I cloned the repo and made the changes on my local workspace. I can submit a PR if you want otherwise I think I can wait for the official release.

Regards!

**Comment by brianvoe** [comment]
Sorry already beat you to it. :smile: 
v1.13.0
also updated docs

**Comment by brianvoe** [comment]
Hit the github star if you like the package. :1st_place_medal: It really helps
