### ISSUE TITLE
'SlimSelect is not a constructor' when imported

### ISSUE THREAD

**Issue by scudderk** [brianvoe/slim-select#435]
**Describe the bug**
The CDN works fine for v2.4.1, but when I try to use `import { SlimSelect } from 'slim-select'` I am always given `SlimSelect is not a constructor` error. 

I have the following scenario:

```
import { SlimSelect } from 'slim-select'

export const ddlClientInitialise = () => {
  const slimSelectArray = document.querySelectorAll('.ddlClientID') as NodeListOf<HTMLSelectElement>
  slimSelectArray.forEach((element: HTMLSelectElement) => {
    if (element.dataset.ssid === undefined && element.localName === 'select') {
      new SlimSelect({
        select: element,
        events: {
          afterChange: () => {
            contactLoad(element.value)
          }
        }
      })
    }
  })
}
```

<img width="271" alt="image" src="https://user-images.githubusercontent.com/28690606/215780134-eeef0e43-027a-4957-83b9-de78c01c0c32.png">

Would a code pen help or is this related to #358?

**Comment by AzA-95** [comment]
Sent pr https://github.com/brianvoe/slim-select/pull/446 for fix this.
Before **this pr will be merged** you can use import so **import SlimSelect from 'slim-select/dist/slimselect.es.js';**

**Comment by AzA-95** [comment]
@scudderk Your the code **import** incorect

> In your code **import { SlimSelect } from 'slim-select'** should be **import SlimSelect from 'slim-select'**

**Comment by brianvoe** [comment]
v2.4.3 let me know if it worked
