### ISSUE TITLE
"select all" functionality does not work with the "search" function

### ISSUE THREAD

**Issue by kalel1500** [brianvoe/slim-select#436]
When using the "search" function to get the values, each time a value is clicked the function is executed again and the values in the list are updated again.

This does not allow the selected values to be marked in the list (as it is done when the values are static) and it does not allow selecting all the values of a group either, since clicking on the "select all" button reruns the search function and the searched values are not added.

**Comment by brianvoe** [comment]
please submit a codepen or jsfiddle example

**Comment by kalel1500** [comment]
here is the example:

https://jsfiddle.net/mqLg2yhv/1/

**Comment by brianvoe** [comment]
Ok i think i see the issue. I need to look at this one for awhile and thing about how i want it to function.

**Comment by VictorAndrade11** [comment]
> Ok, acho que entendi o problema. Eu preciso olhar para este por algum tempo e pensar sobre como eu quero que ele funcione.

Gostaria de saber se conseguiu resolver o problema, pois estou enfrentando o mesmo =[

**Comment by VictorAndrade11** [comment]
> Ok i think i see the issue. I need to look at this one for awhile and thing about how i want it to function.

I would like to know if I managed to solve the problem, because I am facing the same =[

**Comment by mendoma** [comment]
Hi, I am having this same issue. Any update on a fix?

Thanks

**Comment by brianvoe** [comment]
working on it. should be out this week.

**Comment by brianvoe** [comment]
v2.6.0
