### ISSUE TITLE
Delete icon not displaying for multi-select without modifying CSS

### ISSUE THREAD

**Issue by joelcahalan** [brianvoe/slim-select#438]
**Describe the bug**
Specifying the width on ```.ss-value-delete``` caused the "x" not to display. When i removed: ```width:var(--ss-spacing-l);``` this issue goes away. Not sure why this is as I am not an expert on CSS

**Screenshots**
Please add screenshots to help explain your issue.
without removal:

<img width="628" alt="Screenshot 2023-02-10 at 4 12 05 PM" src="https://user-images.githubusercontent.com/55459818/218198457-82a57984-9aaf-4e90-9d59-9e3cc4fd827d.png">

with removal:

<img width="628" alt="Screenshot 2023-02-10 at 4 13 47 PM" src="https://user-images.githubusercontent.com/55459818/218198646-fe55f767-9bac-4824-a4cb-75209fa69bdc.png">

**Comment by brianvoe** [comment]
Ya this is just a css thing. you need to give it a proper width otherwise flex is going to use up as much space as it can.
