### ISSUE TITLE
getSelected is undefined

### ISSUE THREAD

**Issue by ZeeshanZulfiqarAli** [brianvoe/slim-select#439]
Following the example for `getSelected` in the docs, I get the error `Uncaught TypeError: select.getSelected is not a function`

Upon further inspection, I found this function to be accessible as `select.data.getSelected`. I am not sure if this is the intended behavior, if yes, then please update the documentation on the website.

**Comment by brianvoe** [comment]
https://slimselectjs.com/methods#getSelected. Not sure what you mean.

**Comment by ZeeshanZulfiqarAli** [comment]
My bad. While trying to create a reproducible example I realized that `npm update` hadn't actually updated the package to the latest version and I was effectively on a prior one hence the error.
