### ISSUE TITLE
Allow to customise the search placeholder text.

### ISSUE THREAD

**Issue by avaz** [brianvoe/slim-select#44]
Currently is possible to customise the ```searchText``` which is actually the text for when the search doesn't return any information but the search placeholder text (in the image the text ```Search```) is not customisable. 

Would be nice if was possible to customise it for a better I18n adherence.

![image](https://user-images.githubusercontent.com/29484/38814796-aac628bc-4192-11e8-9ff3-86d6a107e116.png)

**Comment by brianvoe** [comment]
Ok i added an option called searchPlaceholder. This will allow you to set the placeholder text on the input search field. Just released to v1.15.0

Thanks for bringing this up!
