### ISSUE TITLE
Extend selectAll to not be restricted to optgroup

### ISSUE THREAD

**Issue by ZeeshanZulfiqarAli** [brianvoe/slim-select#440]
Currently, selectAll functionality supports optgroup only but it should work for options without optgroup as well for eg:
```html
<select ref="selectAll" multiple>
    <option value="value1">Value 1</option>
    <option value="value2">Value 2</option>
    <option value="value3">Value 3</option>
</select>
```

**Comment by jokerisgod** [comment]
@brianvoe Since this is marked as completed, can you please point, how this would work?

I tried adding selectall directly in settings, didn't work.

**Comment by brianvoe** [comment]
Select all only works in optgroups at the moment. SelectAll normal options can programmably done by just setting all the values when you want. or what most people do is put an "All" option at the top.
