### ISSUE TITLE
Keep search results after the selection

### ISSUE THREAD

**Issue by egemen-dev** [brianvoe/slim-select#442]
What happens is that when searching something and selecting an option from newly populated options, the option gets selected but results disappear. In this case `closeOnSelect` doesn't work even though it is set to `false`.

I am considering this a bug or an edge case, because selecting an option when not searching, results are not disappearing after a selection, only selected option gets removed from the dropdown. This behavior is not present when selecting after searching.

Is there a way to keep the relevant search results after selecting an option from the dropdown?

**Comment by brianvoe** [comment]
Please submit a video example or codepen link of the issue.
