### ISSUE TITLE
export 'SlimSelect' (imported as 'SlimSelect') was not found in 'slim-select' (module has no exports)

### ISSUE THREAD

**Issue by aliceni81** [brianvoe/slim-select#443]
I update the slim-select version to 2.4.2 and import it **import SlimSelect from 'slim-select';** in index js file, but it gives me the error **"export 'SlimSelect' (imported as 'SlimSelect') was not found in 'slim-select' (module has no exports)"** while I am building the bundle js file.

The error is gone if I downgrade the version to 2.3.3.

Webpack version: 5.75.0

**Comment by DmitryTar1** [comment]
Have the same issue

**Comment by francesco-loreti** [comment]
Duplicate #429 

You can try my bugfix
`"slim-select": "https://github.com/francesco-loreti/slim-select#fix-429"`

**Comment by garrywilliams** [comment]
Thanks, I get the same issue and I have also reverted to 2.3.3

**Comment by AzA-95** [comment]
Sent pr https://github.com/brianvoe/slim-select/pull/446 for fix this.
Before this pr will be merged you can use import so import SlimSelect from 'slim-select/dist/slimselect.es.js';

**Comment by brianvoe** [comment]
v2.4.3 let me know if it worked
