### ISSUE TITLE
Problem in Select All when adding dynamically in the search.

### ISSUE THREAD

**Issue by VictorAndrade11** [brianvoe/slim-select#444]
**Describe the bug**
I'm trying to implement selectAll in my search bar, that is, when searching, make the options appear and selectAll with them. This I got, however when clicking on selectAll it assigns a refresh and does not select all.
I have another question not mentioned in the documentation: Is it possible to customize select all? Change the text of it and even the icon?

And another question: Is it possible to change the color of the text added to the options label?
Link: 
https://i.imgur.com/GoJLXbf.png
https://i.imgur.com/DcOKuIz.png

**Screenshots**
Link gif
https://i.imgur.com/EhPX1gm.gif

**Comment by brianvoe** [comment]
Sorry i didnt respond to this. Looks like this one is old. Let me know if newer version are still giving you issues.
