### ISSUE TITLE
Set max number for multiple select

### ISSUE THREAD

**Issue by chrisehlee** [brianvoe/slim-select#45]
Is there a way to limit the number of selections from the multiple select?

**Comment by brianvoe** [comment]
Oh thats interesting! I could add something to make it easier but for right now you could get the values from onBeforeChange and onChange and if the value number goes over use the values in onBeforeChange function to set it back.

But if your up for waiting give me a couple days and ill implement an easier integration.

Thanks.

P.S. If you find this package useful give it a star. It really helps!

**Comment by brianvoe** [comment]
👍

**Comment by brianvoe** [comment]
I added this feature and will be out with the next release
