### ISSUE TITLE
Event 'addable' not working as intented

### ISSUE THREAD

**Issue by Lycain** [brianvoe/slim-select#450]
While trying to use the addable callback I found out that returning null or false inside it don't work as the intended in the doc : 
"return false or null if you do not want to allow value to be submitted"
https://slimselectjs.com/events#addable

By checking the source code of render.ts there is no trace of a return statement if the option we are trying to create is undefined / false or null 
A check for that would maybe be implemented right before the option creation in the runFinish function here :
https://github.com/brianvoe/slim-select/blob/master/src/slim-select/render.ts#L748

**Comment by brianvoe** [comment]
Good catch ill get this fixed

**Comment by brianvoe** [comment]
v2.4.4
