### ISSUE TITLE
Bug after 2.4.5 for rendering custom selected option's HTML

### ISSUE THREAD

**Issue by Lycain** [brianvoe/slim-select#453]
After trying the latest version, I don't know if it is intended or a bug but,
By changing this line : 
https://github.com/brianvoe/slim-select/blob/master/src/slim-select/render.ts#L529
from 'text.innerHTML' using custom HTML to render selected options don't work anymore. instead the raw outer html of the element is shown as plain text.

**Comment by brianvoe** [comment]
Thanks for pointing this out. I didnt see any issues in the dev docs. A recent pr went in to fix someone elses issue. Looks like it may have had some alternative issue.

https://github.com/brianvoe/slim-select/issues/451
