### ISSUE TITLE
Add tests

### ISSUE THREAD

**Issue by brianvoe** [brianvoe/slim-select#460]
Using jest add more tests for primary scenarios.

**Comment by dminkovski** [comment]
@brianvoe will gladly help you with that 😊

**Comment by brianvoe** [comment]
Got some in. Its a good start

**Comment by Data5tream** [comment]
I'm writing a bunch of unit tests, I would like to see the vanilla `slim-select` at >90% coverage 😄

**Comment by brianvoe** [comment]
I like hearing that. just to make sure your in the right direction i would suggest showing me something so i can see how your doing tests. in case we need to head in a different direction.

**Comment by Data5tream** [comment]
I've started with some tests for the `helpers.ts` [here](https://github.com/Data5tream/slim-select/commit/825fed01c0f799ae41065b53298fc2b48c1d2fa9).

Let me know what you think about them.

**Comment by brianvoe** [comment]
looks good to me. carry on sir.
