### ISSUE TITLE
Incomplete "exports" field in packgae.json (missing types)

### ISSUE THREAD

**Issue by LubomirFedor** [brianvoe/slim-select#462]
**Describe the bug**
According to [Typescript documentation](https://www.typescriptlang.org/docs/handbook/esm-node.html#packagejson-exports-imports-and-self-referencing), each export in "exports" field in package.json should contain a separate "types"  if the "*.d.ts" file isn't colocated:

> It’s important to note that the CommonJS entrypoint and the ES module entrypoint each needs its own declaration file, even if the contents are the same between them.

```json
...
"exports": {
        ".": {
            // Entry-point for `import "my-package"` in ESM
            "import": {
                // Where TypeScript will look.
                "types": "./types/esm/index.d.ts",
                // Where Node.js will look.
                "default": "./esm/index.js"
            },
            // Entry-point for `require("my-package") in CJS
            "require": {
                // Where TypeScript will look.
                "types": "./types/commonjs/index.d.cts",
                // Where Node.js will look.
                "default": "./commonjs/index.cjs"
            },
        }
    },
...
```
Right now, my TypeScript reports the following error:

> There are types at '(...)/node_modules/slim-select/dist/index.d.ts', but this result could not be resolved when respecting package.json "exports". The 'slim-select' library may need to update its package.json or typings.

Compiler options in my tsconfig.json:
```json
	"compilerOptions": {
		"allowSyntheticDefaultImports": true,
		"esModuleInterop": true,
		"sourceMap": true,
		"outDir": "./tmp/",
		"noImplicitAny": true,
		"module": "ES2020",
		"target": "ES2020",
		"strict": true,
		"allowJs": true,
		"declaration": false,
		"moduleResolution": "node16"
	}
```
TypeScript version: 5.0.4

**Comment by brianvoe** [comment]
Im open to a pr if you want to submit something.

**Comment by Miodec** [comment]
Was this actually completed? Im getting the same error about the types
` Could not find a declaration file for module 'slim-select'. (...) There are types at (...) but this result could not be resolved when respecting package.json "exports". The 'slim-select' library may need to update its package.json or typings.`

**Comment by sashasydorenko** [comment]
The same issue for `"moduleResolution": "Bundler"`

**Comment by Miodec** [comment]
Any chance this can be looked into again? Its impossible to use slim select with bundler module resolution, and other parts of the project pretty much dont allow me to use anything else.

**Comment by brianvoe** [comment]
I merged your pr so hopefully it works.
