### ISSUE TITLE
Resizing content in afterOpen

### ISSUE THREAD

**Issue by jerryclinesmith** [brianvoe/slim-select#465]
I'm attempting to size the content dropdown using the following code in afterOpen:

```js
const containerRect = this.slimselect.render.main.main.getBoundingClientRect()
this.slimselect.render.content.main.style.minWidth = containerRect.width + 'px'
this.slimselect.render.content.main.style.width = 'auto';
```

The contents resize, but then immediately reset.  Is there another way I should be doing this?

**Comment by brianvoe** [comment]
I would have to see a working example. If you setup a codepen example ill see if i can help

**Comment by jerryclinesmith** [comment]
https://jsfiddle.net/JerryClinesmith/hfxmd6gc/41/

I'm trying to get the dropdown content to autosize to the option text.

**Comment by brianvoe** [comment]
Ok i see. Ya trying to set a width of a dynamic style field doesn't sound possible. Cause you would always be fighting with slim select updating width. If it was a static width you were trying to set I would say add a classname and set !important on it and hopefully that would take precedence over the style field.
