### ISSUE TITLE
Set aria-live="assertive" when a dropdown opens

### ISSUE THREAD

**Issue by andreanironi** [brianvoe/slim-select#468]
Slim select should consider setting an aria-live attribute whenever a select opens. Aria-live regions can assist visually-impaired users to detect when a block is changed dynamically via Javascript, requiring the user attention. See also: https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Live_Regions

When a user opens a dropdown, its intention is to see the available options and possibly select one of those. Hence I would suggest setting an "assertive" value to aria-live, otherwise the screen reader will speak just when the user is idle.

**Comment by brianvoe** [comment]
Would be more than happy to look at a pr if you submit one.

**Comment by andreanironi** [comment]
Sure. Sorry for the newbie question: I gave this a try, but I'm having a hard time finding a way to compile this project into a single .js file. How are the files on the CDN created? Just by running tsc, or using webpack, or similar? Once done I'll also add a couple of lines to CONTRIBUTING.md :-)

**Comment by brianvoe** [comment]
package.json will have all the scripts it runs. but for your pr. I dont need you to build anything, ill do that, just need to see what code you added to the source.
