### ISSUE TITLE
Styling doesn't honour the initial select state.

### ISSUE THREAD

**Issue by avaz** [brianvoe/slim-select#47]
When the initial state of the select is ```disabled``` the slimselect doesn't apply the proper styling.
Example:

A select like this:

```
<select id="my-select" disabled="disabled">
	<option value="1">Value 1<option>
	<option value="2">Value 2<option>
	<option value="3">Value 3<option>
</select>

<script type="text/javascript">
	var select =  new SlimSelect({
		select: "#my-select"
	});
</script>
``` 

Will not have a the background greyed.

However if after instantiate the ```select.disabled();``` is called the proper styling is applied.

**Comment by brianvoe** [comment]
I tried this on an example select and it applied the class as expected. Can you try to use a class instead of an id to style your item?

**Comment by avaz** [comment]
Well, I'm not sure if I understood you, just to make clear, I have the following html:

```html
<!DOCTYPE html>
<html>
<head>
	<title>SlimSelect Test</title>
<script src="https://cdnjs.cloudflare.com/ajax/libs/slim-select/1.15.0/slimselect.min.js"></script>
<link href="https://cdnjs.cloudflare.com/ajax/libs/slim-select/1.15.0/slimselect.min.css" rel="stylesheet"></link>
</head>
<body>
<select id="my-select" disabled="disabled">
	<option value="1">Value 1<option>
	<option value="2">Value 2<option>
	<option value="3">Value 3<option>
</select>

<script type="text/javascript">
	var select =  new SlimSelect({
		select: "#my-select"
	});
	//select.disable();
</script>
</body>
</html>
```
And it renders the select like this (the slimselect rendered is disabled, i.e. not clickable):
![image](https://user-images.githubusercontent.com/29484/39243759-e85c8c04-488e-11e8-96c5-c6fcbb9de315.png)
However if I uncomment the ```select.disable();``` it renders like this:
![image](https://user-images.githubusercontent.com/29484/39243827-0f0216c6-488f-11e8-9575-6c85dc47f5b0.png)

Shouldn't it render automatically greyed when the html select is initially disabled?

**Comment by brianvoe** [comment]
oh interesting. ok ill look into this

**Comment by brianvoe** [comment]
Ive fixed this and will be out in the next release
