### ISSUE TITLE
Feature Request: Make "Select All" text configurable

### ISSUE THREAD

**Issue by severinkaelin** [brianvoe/slim-select#470]
Hello @brianvoe 
First of all, thanks for this awesome library.

I wanted to ask if you would accept a feature which makes the "Select All" text configurable via the settings.

https://github.com/brianvoe/slim-select/blob/master/src/slim-select/render.ts#L1008

![image](https://github.com/brianvoe/slim-select/assets/39438642/8a52217f-c398-48fa-91dd-d25b2b3ac356)

I'd suggest implementing this similar to the other texts/labels:

```javascript
new SlimSelect({
  select: '#placeholder',
  settings: {
    placeholderText: 'Custom Placeholder Text', // <-- Similiar to this
  }
})
```

Unfortunately, I don't have enough time to contribute a PR at the moment. However, I wanted to take the chance to ask if you would be interested in the feature in general and accept a PR on it? Maybe someone else from the community is also interested in this and has the possibility to take care of the PR.

Thanks a lot.

Kind regards
Severin

**Comment by brianvoe** [comment]
v2.6.0
