### ISSUE TITLE
Allow to set a different selected text from the one in the option

### ISSUE THREAD

**Issue by sergiucaraian** [brianvoe/slim-select#48]
Hi,

I wonder if it's possible to display a different text in the unopened select element from the one in the option. In my case I use innerHTML to populate the option, but I would like to have a different text in the selected box (the element with class "placeholder"). 

You seem to hint that this is possible in the documentation (http://slimselectjs.com/options , the innerHTML section). For a data point such as {innerHTML: '<i>Slim Select you are awesome</i>', text: 'Slim Select awesome'} , I would like to display the value in the 'text' property  ("slim select awesome") in the select box. Instead, in all selects, even when I have valuesUseText set to true, the text inside innerHTML ("Slim Select you are awesome") is displayed.

This can be useful when you have alot of text inside innerHTML (in my case 4-5 lines of text) that would look bad when inlined.

Thank you

**Comment by sergiucaraian** [comment]
Something like this:

![image](https://user-images.githubusercontent.com/7252396/39423576-3caa64a8-4c7b-11e8-8f1b-b4c69e60a238.png)

As you can see, the text inside the selected <option> tag is "Slim select you are awesome". I would like to be able to have a different text in the <select> tag. In the image above, this is "Different text from the selected option".

**Comment by brianvoe** [comment]
I see what you are saying but this seems like a very fringe case and would be tough to justify adding this feature. You can facility this currently by setting the data(using setData) and update the option text of the selected value.

That being said i would be curious as to your use case in which you would need to alter the text of the selected value.

**Comment by sergiucaraian** [comment]
I'm using this library to allow displaying somewhat complex HTML in the option tags. I need to have a select of products. Each option would display certain product details (name, characteristics, price) in about 3-4 lines of text. The problem is that the lines get inlined when shown in the select tag which looks bad. It would look much better if I could show only the title of the chosen product.

Example: 

![image](https://user-images.githubusercontent.com/7252396/39431545-c385a32a-4c99-11e8-92cc-a78cebbd8001.png)

**Comment by brianvoe** [comment]
So you can tell me if this is true or not but if the innerhtml's are the same and you need to have different styles between whats in the options list and the selected values. Then you can target the different div with different css styles.

**Comment by brianvoe** [comment]
Glad you like it. Ill look into updating the docs to add more description on this.

Thanks!
