### ISSUE TITLE
Duplicate id atribute

### ISSUE THREAD

**Issue by ImKubass** [brianvoe/slim-select#481]
**Describe the bug**
Library render duplicate id atribute

**Screenshots**

![SCR-20230904-nmgs](https://github.com/brianvoe/slim-select/assets/22158893/df33ccdd-9269-47dc-803f-725b65a2df9e)
![SCR-20230904-nmdk](https://github.com/brianvoe/slim-select/assets/22158893/4f73a10f-e0d8-4282-89cf-34f3a6749104)

**Comment by tomaston** [comment]
This is unfortunately being flagged as an accessibility issue when scanned on PageSpeed Insights

![Screenshot-2023-09-05-at-18 34 04](https://github.com/brianvoe/slim-select/assets/1652659/499db37c-8549-4630-9337-121485ebd9d2)

**Comment by ImKubass** [comment]
<img width="493" alt="Screenshot at Sep 15 10-03-38" src="https://github.com/brianvoe/slim-select/assets/22158893/79d93b81-707c-4775-88e1-94ddcccefc24">

render.ts

This oneliner could fix that. I cant make pull request.
@brianvoe

**Comment by Kicimanasek** [comment]
This is also flagged as an error with HTML validator and is not consider as best practice.

![Screenshot from 2023-09-15 07-54-23](https://github.com/brianvoe/slim-select/assets/145094964/29a13b62-0385-493a-872f-e2c267cfa708)

**Comment by andreanironi** [comment]
Opened a new PR for this, waiting for a review from the maintainer.

**Comment by brianvoe** [comment]
I know you guys dont think its an issue, but I know the issue will be people use that id to target the slim select div and it will break if i put this in.

Let me put some thought into this.

**Comment by brianvoe** [comment]
I got a fix in will go out in next release
