### ISSUE TITLE
Invalid dropdown position in dialog window

### ISSUE THREAD

**Issue by yevhensayenko** [brianvoe/slim-select#483]
**Describe the bug**
When I place SlimSelect on HTML dialog, it displays its dropdown in an invalid location. Especially when page under the dialog gets scrolled.

**Screenshots**
JSFiddle example: https://jsfiddle.net/djypnf18/1/

**Comment by brianvoe** [comment]
Submit a pr if you find a fix and ill get it in.

**Comment by nplebanskyi** [comment]
Hi, @yevhensayenko , did you find a fix for that issue?

**Comment by brianvoe** [comment]
Its not really an issue. its just a bad placement. wrap a div around it and you should be good.
