### ISSUE TITLE
Navigation using arrow keys starts from top/bottom

### ISSUE THREAD

**Issue by Leonick** [brianvoe/slim-select#486]
Not so much a bug as less than useful behaviour. 
After tabbing to and opening a single select with a preset value I would expect arrow up/down to navigate up or down from the currently select value, especially since the menu is already scrolled to show it. It currently navigates up from the bottom or down from the top.

**Comment by brianvoe** [comment]
I agree. I added it and will go out in the next release. Thanks for pointing it out.
