### ISSUE TITLE
Clear button (x) is still visible when deselecting via options

### ISSUE THREAD

**Issue by JoeKaldas** [brianvoe/slim-select#489]
**Describe the bug**
`ss-deselect` div is still visible for multiple options select when deselecting is allowed and I deselect via the dropdown option

**Screenshots**

Initial state
![Screenshot 2023-10-12 at 12 42 45 AM](https://github.com/brianvoe/slim-select/assets/6186940/a34466a0-92c9-4dfb-bdb7-d48226ac2bc4)

Choosing an option
![Screenshot 2023-10-12 at 12 42 33 AM](https://github.com/brianvoe/slim-select/assets/6186940/c0df349f-1ee0-4428-8d68-3b9b446d5874)

Deselecting that option via select.
![Screenshot 2023-10-12 at 12 42 41 AM](https://github.com/brianvoe/slim-select/assets/6186940/10275576-b7b8-408a-884d-682003b19b57)

Expected: Deselect button (x) should be hidden
Actual: Deselect button (x) is still visible

A quick simple fix would be as follow:

```javascript
this.clearButton = document.getElementsByClassName("ss-deselect")[0];


events: {
  afterChange: (newVal) => {
    if (newVal.length === 0) {
      this.clearButton.classList.add("ss-hide");
    }
  }
}
```

**Comment by brianvoe** [comment]
I dont see this issue happening in the docs not sure how your seeing it.
