### ISSUE TITLE
Slim select is not updating with the original select element in v2

### ISSUE THREAD

**Issue by marioloncarek** [brianvoe/slim-select#492]
**Describe the bug**
Hello all, 
i have a dynamic select element which content is updating with javascript, but the changes of the original select element are not reflected to the slim select, which remains always empty (like the original state of the original select element). This feature was working in the previous version of slim select, but not working in v2. Im currently using `"^2.6.0"` version. Is this now an option or is this a bug? Thanks in advance.

**Screenshots**
<img width="605" alt="Screenshot 2023-10-20 at 11 45 25" src="https://github.com/brianvoe/slim-select/assets/11228203/003aa1eb-d2cc-474a-95d7-a252883b88b1">

**Comment by brianvoe** [comment]
I would have to know more about how you are updating your content.

**Comment by marioloncarek** [comment]
thanks for taking time @brianvoe ! 
Im implementing slim select on a Shopify customer account stuff (for years), the updating of the select options is handled by their global script, which looks like this:

```
Shopify.CountryProvinceSelector = function (country_domid, province_domid, options) {
    this.countryEl = document.getElementById(country_domid);
    this.provinceEl = document.getElementById(province_domid);
    this.provinceContainer = document.getElementById(options['hideElement'] || province_domid);

    Shopify.addListener(this.countryEl, 'change', Shopify.bind(this.countryHandler, this));

    this.initCountry();
    this.initProvince();
};

Shopify.CountryProvinceSelector.prototype = {
    initCountry: function () {
        var value = this.countryEl.getAttribute('data-default');
        Shopify.setSelectorByValue(this.countryEl, value);
        this.countryHandler();
    },

    initProvince: function () {
        var value = this.provinceEl.getAttribute('data-default');
        if (value && this.provinceEl.options.length > 0) {
            Shopify.setSelectorByValue(this.provinceEl, value);
        }
    },

    countryHandler: function (e) {
        var opt = this.countryEl.options[this.countryEl.selectedIndex];
        var raw = opt.getAttribute('data-provinces');
        var provinces = JSON.parse(raw);

        this.clearOptions(this.provinceEl);
        if (provinces && provinces.length == 0) {
            this.provinceContainer.style.display = 'none';
        } else {
            for (var i = 0; i < provinces.length; i++) {
                var opt = document.createElement('option');
                opt.value = provinces[i][0];
                opt.innerHTML = provinces[i][1];
                this.provinceEl.appendChild(opt);
            }

            this.provinceContainer.style.display = '';
        }
    },

    clearOptions: function (selector) {
        while (selector.firstChild) {
            selector.removeChild(selector.firstChild);
        }
    },

    setOptions: function (selector, values) {
        for (var i = 0, count = values.length; i < values.length; i++) {
            var opt = document.createElement('option');
            opt.value = values[i];
            opt.innerHTML = values[i];
            selector.appendChild(opt);
        }
    },
};
```

Basically what this script does is when you select a country that has provinces, the provinces selector is shown and its filled with correct provinces for that country. 
Thanks in advance for your help.

**Comment by brianvoe** [comment]
So the two things that come to mind are:

1. mutation observer - slim select uses a mutation observer so it will look out for changes under the select element and update when it notices changes. I dont know if that is an issue with your usage but something to keep in mind.
2. timing - javascript is tough to ensure linear execution of things and can get tricky to ensure the last thing you called is what you would see at the end. So if any of your functions are called at the same time or really close slim select may start doing one thing you ask and while its doing that you ask is to do something else before its done and can run into issues that way.

I would suggest if possible use the data setting within slim select and you shouldnt have to worry about making sure the mutation observer is operating in the right order.

But those are all guesses cause i still really dont see how your using slim select in its full usage and if there are other things going on as well you can run into other javascript issues of race conditions.

**Comment by marioloncarek** [comment]
again thanks for your time @brianvoe , here is the full implementation of slim select for this case:

1. Concept and the problem
Form contains two select elements, one for country and one for province. Country select is always filled with the list of all countries, while the province select element is empty. When the user selects the country from the country select element which has provinces, the province element gets filled the provinces for that country. Provinces for each country are read from the data attribute which each country option has in the country select element. If the provinces data attribute is not empty the provinces are injected as options in the provinces select element with the Shopifys script in section 3 of this message. This then should be registered by the slim select if you said that its using mutation observer, which is not happening.

2. HTML

```
<!--fieldset-->
<fieldset class="c-form__fieldset c-form__fieldset--column">
    <label class="c-form__label u-a1"
           for="AddressCountry_{{- form.id -}}">
        {{- 'customer.addresses.country' | t -}}
    </label>
    <select class="js-select-input"
            data-search
            id="AddressCountry_{{- form.id -}}"
            name="address[country]"
            data-address-country-select
            data-default="{{- form.country -}}"
            data-form-id="{{- form.id -}}"
            autocomplete="country">
        {{- all_country_option_tags -}}
    </select>
</fieldset>
<!--end fieldset-->
<!--fieldset-->
<fieldset class="c-form__fieldset c-form__fieldset--column"
          id="AddressProvinceContainer_{{- form.id -}}"
          style="display:none;">
    <label class="c-form__label u-a1"
           for="AddressProvince_{{- form.id -}}">
        {{- 'customer.addresses.province' | t -}}
    </label>
    <select class="js-select-input"
            data-search
            id="AddressProvince_{{- form.id -}}"
            name="address[province]"
            data-default="{{- form.province -}}"
            autocomplete="address-level1">
    </select>
</fieldset>
<!--end fieldset-->
```

3. Shopifys script which injects the provinces

```
Shopify.CountryProvinceSelector = function (country_domid, province_domid, options) {
    this.countryEl = document.getElementById(country_domid);
    this.provinceEl = document.getElementById(province_domid);
    this.provinceContainer = document.getElementById(options['hideElement'] || province_domid);

    Shopify.addListener(this.countryEl, 'change', Shopify.bind(this.countryHandler, this));

    this.initCountry();
    this.initProvince();
};

Shopify.CountryProvinceSelector.prototype = {
    initCountry: function () {
        var value = this.countryEl.getAttribute('data-default');
        Shopify.setSelectorByValue(this.countryEl, value);
        this.countryHandler();
    },

    initProvince: function () {
        var value = this.provinceEl.getAttribute('data-default');
        if (value && this.provinceEl.options.length > 0) {
            Shopify.setSelectorByValue(this.provinceEl, value);
        }
    },

    countryHandler: function (e) {
        var opt = this.countryEl.options[this.countryEl.selectedIndex];
        var raw = opt.getAttribute('data-provinces');
        var provinces = JSON.parse(raw);

        this.clearOptions(this.provinceEl);
        if (provinces && provinces.length == 0) {
            this.provinceContainer.style.display = 'none';
        } else {
            for (var i = 0; i < provinces.length; i++) {
                var opt = document.createElement('option');
                opt.value = provinces[i][0];
                opt.innerHTML = provinces[i][1];
                this.provinceEl.appendChild(opt);
            }

            this.provinceContainer.style.display = '';
        }
    },

    clearOptions: function (selector) {
        while (selector.firstChild) {
            selector.removeChild(selector.firstChild);
        }
    },

    setOptions: function (selector, values) {
        for (var i = 0, count = values.length; i < values.length; i++) {
            var opt = document.createElement('option');
            opt.value = values[i];
            opt.innerHTML = values[i];
            selector.appendChild(opt);
        }
    },
};
```

4. Slim select init

```
this.inputs.forEach((input) => {
    new SlimSelect({
        select: input
    });
});
```

Im also sending you an full video of what is happening in the DOM

https://github.com/brianvoe/slim-select/assets/11228203/5f86ab69-4e8a-4c9c-946d-df025f0a5223

**Comment by ranggawisnus** [comment]
I got the same issue

**Comment by brianvoe** [comment]
Ya what it looks like is whatever code is running to update the Province isnt triggering the mutation observer slim select uses to identify when the html options changed.
