### ISSUE TITLE
Slim Select Mobile Search

### ISSUE THREAD

**Issue by phpcodingmaster** [brianvoe/slim-select#493]
**Describe the bug**
A clear and concise description of what the issue is.

Hi,

I am using the slimselect library and it is great, but I have an issue where the search box works on desktop, but not on a mobile device. 
![image](https://github.com/brianvoe/slim-select/assets/79761312/c3fa7fe7-92b3-408a-9f8a-a8e20b46ed3d)

The image above is on desktop, but on mobile it shows the default select dropdown to scroll down all the options. 
Is there a way to show the search box on a mobile device, please?

Mobile Screenshot below
![image](https://github.com/brianvoe/slim-select/assets/79761312/d88fe076-6620-426c-8ba2-035584af717a)

**Comment by brianvoe** [comment]
Your making me second guess myself but I dont believe I have anything that would hide the search bar on mobile. Might want to check your css and see if you are hiding it without knowing.

**Comment by phpcodingmaster** [comment]
Hi @brianvoe, thank you for getting back to me.
I indeed had an issue on my side, managed to fix it.

Thank you for the quick reply though.

**Comment by brianvoe** [comment]
No problem, enjoy!

If this project has been helpful for you consider supporting :)
