### ISSUE TITLE
placeholder is removed if called with setData

### ISSUE THREAD

**Issue by 0419** [brianvoe/slim-select#5]
I am trying to add/remove options at runtime by calling setData, but then it removes placeholder. and also it automatically selects first element, I would like user to select it manually.

**Comment by brianvoe** [comment]
Interesting. Ya that would make sense. So im guessing you are setting initially with raw html and then at a later point using .setData([]) with your new options.

I will definitely look into that and probably update it to all one of the setData options to set placeholder = true.

In the mean time if possible in your situation you can always just update the original select html and a mutation observer will pick up the changes and rerender slim select.

**Comment by brianvoe** [comment]
@0419 Updated to allow setData to add an object with placeholder = true. Update to version 1.1.0. Let me know if that works for you.

```javascript
var slim = new SlimSelect({
  select: '#select',
  placeholder: 'Placeholder Text Here'
})

slim.setData([
  // Make sure placeholder is first value
  {text: '', placeholder: true},
  {text: 'new value'}
])
```

**Comment by yellow1912** [comment]
This is a very old issue, but I think the placeholder should be a completely different setting and not affected by data at all.

**Comment by devBinay** [comment]
> @0419 Updated to allow setData to add an object with placeholder = true. Update to version 1.1.0. Let me know if that works for you.
> 
> ```js
> var slim = new SlimSelect({
>   select: '#select',
>   placeholder: 'Placeholder Text Here'
> })
> 
> slim.setData([
>   // Make sure placeholder is first value
>   {text: '', placeholder: true},
>   {text: 'new value'}
> ])
> ```

How about allowing a new value for placeholder as well instead of just setting it true. Let me know your thoughts on this, as this will be handy. Thanks :)
