### ISSUE TITLE
Flickering dropdown when toggling it

### ISSUE THREAD

**Issue by cuongle-hdwebsoft** [brianvoe/slim-select#505]
**Describe the bug**
The dropdown animation is flickering when it collapses.

Step to reproduce
- Try to scroll down to make Select close to bottom screen
- Open Select, then it will change `listbox` from the `bottom` to `top` automatically
- Close select, and you will see the bug here. The animation seems to be broken or something that I don't understand that behavior

**Screenshots**

https://github.com/brianvoe/slim-select/assets/102006695/4d1ef9e2-f695-44aa-b032-f9978b219921

**Comment by brianvoe** [comment]
I dont see any flickering in your video.

**Comment by cuongle-hdwebsoft** [comment]
Ok let me reproduce this issue in codesandbox:

- [Here is the version `v2.0.2`](https://codesandbox.io/p/sandbox/gracious-babycat-ky35vf?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clqwhuw8o00063b6jwocridfn%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clqwhuw8o00023b6j7l5ym2xl%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clqwhuw8o00033b6jz0j9pf5m%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clqwhuw8o00053b6j6l6re0d8%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clqwhuw8o00023b6j7l5ym2xl%2522%253A%257B%2522id%2522%253A%2522clqwhuw8o00023b6j7l5ym2xl%2522%252C%2522tabs%2522%253A%255B%255D%257D%252C%2522clqwhuw8o00053b6j6l6re0d8%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clqwhuw8o00043b6jvnyoa1c0%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clqwhuw8o00053b6j6l6re0d8%2522%252C%2522activeTabId%2522%253A%2522clqwhuw8o00043b6jvnyoa1c0%2522%257D%252C%2522clqwhuw8o00033b6jz0j9pf5m%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clqwhuw8o00033b6jz0j9pf5m%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)
- [Here is the latest version `v2.8.0`](https://codesandbox.io/p/sandbox/lucid-grass-tgcns6?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clqwhwijh00063b6j5cldp8ef%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clqwhwijh00023b6jersct5ku%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clqwhwijh00033b6j1rlj818z%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clqwhwijh00053b6jevl79rjx%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clqwhwijh00023b6jersct5ku%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clqwhwijh00013b6jq1rpsn1z%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Findex.js%2522%257D%255D%252C%2522id%2522%253A%2522clqwhwijh00023b6jersct5ku%2522%252C%2522activeTabId%2522%253A%2522clqwhwijh00013b6jq1rpsn1z%2522%257D%252C%2522clqwhwijh00053b6jevl79rjx%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clqwhwijh00043b6jsxfu4vsg%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clqwhwijh00053b6jevl79rjx%2522%252C%2522activeTabId%2522%253A%2522clqwhwijh00043b6jsxfu4vsg%2522%257D%252C%2522clqwhwijh00033b6j1rlj818z%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clqwhwijh00033b6j1rlj818z%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

https://github.com/brianvoe/slim-select/assets/102006695/9d25a818-dc63-42b6-97de-aa2eb58942d6

I hope this makes more clear for you

**Comment by brianvoe** [comment]
There might be something there but I just dont really see an issue. If you have a suggestion for a fix I can always look at a pr.

**Comment by cuongle-hdwebsoft** [comment]
https://github.com/brianvoe/slim-select/assets/102006695/92114b99-fa69-4bbc-9e7b-709834fc0677

![CleanShot 2024-01-03 at 07 19 15@2x](https://github.com/brianvoe/slim-select/assets/102006695/1c72d960-39c5-4e6d-b8ab-aa5d68976121)

I think you should try to look at carefully the difference animation when dropdown at the bottom and at the top. It seems like it starts its animation from the red line and then disappears. 

Expected result: It should collapse smoothy, just change the height of the dropdown and do not act the animation like the video.
