### ISSUE TITLE
ClearAll icon not showing while selecting all

### ISSUE THREAD

**Issue by Oute-Oute** [brianvoe/slim-select#506]
**Describe the bug**
When selecting all a group, the "clearAll-Icon" does not display, but if you first select a value then select all a group, it will display (see first gif below)
It's usually not a problem because you have the small "unselectAll" button but in my case it's a problem because i put all my values in a group, which allow me to search a part of the value to select all values matching, but if i do this multiple times, to clear my selected values i have to select then deselect all values with the button (see 2nd gif)

**Screenshots**

![ss-bug](https://github.com/brianvoe/slim-select/assets/61987113/9d392258-71b3-4a87-b57d-b9c1cc8f7515)

![ss-bug-v2](https://github.com/brianvoe/slim-select/assets/61987113/337b3963-cbb1-42b3-8e75-7e61f01d4bbe)

**Comment by brianvoe** [comment]
I updated it to reevaluate the deselect button after each values render.

Just published v2.8.1

If you find that helpful consider donating. https://github.com/sponsors/brianvoe
