### ISSUE TITLE
Deselect the selected value

### ISSUE THREAD

**Issue by SunTzu92** [brianvoe/slim-select#51]
Hi,

I would like to know how I clear the selected value in the slim?

I can not remove.

**Comment by brianvoe** [comment]
Hello,

Thanks for your issue submission you can find information on deselecting under the options section called allowDeselect http://slimselectjs.com/options

If you could like to programmably deselect a value you have to remember that slim select works just like normal selects in that you have to have a selected value(for single select dropdowns), that being said with slim select you can have a placeholder option that doesnt show up on the options list but can be used to set select to that empty value.

Hope this helps or at least points you in the right direction for proper usage.

**Comment by shea-parkes** [comment]
I eventually worked out that you can pass an empty array to the `.select()` method to clear out a multi-select.  It might be worth documenting/showing that somewhere.

**Comment by Omi-R** [comment]
I worked on a multi-select value clear and reset from the slim-select multi-select box. In my case deselect and refresh not working then I used  `$(".ss-value-delete").click();` on button click.

**Comment by tomerb15** [comment]
This is worth Documentation , great project

**Comment by najdovski** [comment]
> I eventually worked out that you can pass an empty array to the `.select()` method to clear out a multi-select. It might be worth documenting/showing that somewhere.

'.select()' is not a method apparently. You have to use the '.set()' methods instead

**Comment by umkasanki** [comment]
```
  const selects = document.querySelectorAll('.js-slim-select')
  const forms = document.querySelectorAll('.js-form')
  let selectsArr = []

  selects.forEach((item) => {
    const select = new SlimSelect({
      select: item,
      settings: {
        showSearch: false,
        placeholderText: 'Select'
      }
    })
    selectsArr.push(select)
  })

  forms.forEach((form) => {
    form.addEventListener('onAfterSubmit', () => {
      selectsArr.forEach((item) => {
        item.setData([])
      })
    })
  })
