### ISSUE TITLE
How can i reset values? 

### ISSUE THREAD

**Issue by nowlights** [brianvoe/slim-select#511]
how can I reset values?

I try use this:

function slimSelectResetData(className) {
let select = new SlimSelect({
select: '.' + className
});
select.setData([{text: "Todos", value: "todos"}]);
}

but not working, i have this error:

Cannot read properties of undefined (reading 'getSelected')

**Comment by brianvoe** [comment]
https://codepen.io/brianvoe/pen/XWGROgg
