### ISSUE TITLE
React dependency? 

### ISSUE THREAD

**Issue by tkoenig** [brianvoe/slim-select#513]
Why is `react` and `react-dom` added as a dependency in the `package.json` file? 
I thought one feature is "No Dependencies" 😄?

Is there a way not  to install those packages?

**Comment by tkoenig** [comment]
So I forked this project and moved react to the `devDependencies` and it still works for me? 
If you want me to create a pull request let me know...

**Comment by brianvoe** [comment]
Sorry i didnt get a chance to pull framework packages out. but i moved the dependencies and did a version release 

v2.8.2
