### ISSUE TITLE
How to get values after create component

### ISSUE THREAD

**Issue by nowlights** [brianvoe/slim-select#515]
So, after create component:

`var select = new SlimSelect({
  select: '#selectElement'
})`

How can i get value from that component, is like that?:

`let select = document.getElementById('selectElement').value`

???

or also to select a value.

I need get value from other JS function, so I can`t use `new SlimSelect()`, right?

**Comment by brianvoe** [comment]
https://codepen.io/brianvoe/pen/MWxVgbV
