### ISSUE TITLE
Chrome Extension Issues

### ISSUE THREAD

**Issue by jbolger4** [brianvoe/slim-select#517]
Our team implemented SlimSelect into a variety of features, and we have gotten a few reports of Chrome Extensions interfering with the dropdown (users not able to select anything, the search immediately clearing, etc.). This is a rare issue, but it is occurring often enough that I am curious if there is any possible solution to this issue!

**Known Chrome Extension Issues:**

1. [Highlight Chrome Extension](https://chromewebstore.google.com/detail/highlight-this-finds-and/fgmbnmjmbjenlhbefngfibmjkpbcljaj)
2. [Hunter Chrome Extension](https://hunter.io/chrome)

**Screenshots**
Not able to include screenshots of the sites and issue, but if you install the chrome extensions above it should recreate the issue for you!

Let me know if you have any additional questions / need clarification anywhere!

Thanks!

**Comment by brianvoe** [comment]
Sorry I am not going to install other extensions. Take screenshot, videos, something visual.

**Comment by jbolger4** [comment]
Hey @brianvoe !

Here is a [video of the issue](https://webpagefx.mangoapps.com/msc/MTU3Nzk5M18xMjY1Njg2MA) that occurs with the Highlight chrome extension. It constantly resets the search if the select has a value in it that the extension is looking for.

As for the Hunter extension, here is a [video of the issue](https://webpagefx.mangoapps.com/msc/MTU3ODA0MV8xMjY1NjkyMQ) that occurs. With this extension, it does not allow you to select at all. I have found that this seems to be more related to the values of the select than the text that appears.

**Comment by brianvoe** [comment]
what do those extensions do?

**Comment by jbolger4** [comment]
The first extension (Highlight) highlights text on the page that you specify. So if I put in "test" into the extension, it will highlight all cases where "test" appears on the page.

The second extension (Hunter) finds emails on the page.

Essentially, both of the extensions are searching for certain text on the site.

**Comment by brianvoe** [comment]
Ya sorry I dont see this being a slim select issue. I dont even know where i would start to look for how I could make any changes to how things function that would make those extensions "work".

You can change the contentLocation and/or position https://slimselectjs.com/settings#contentLocation and bind it somewhere else if that helps.

**Comment by ir3ne** [comment]
@brianvoe I have the same issue and I tried to use `contentLocation` as you suggested. Otherwise the options don't go inside the new container. Do you have an example in codepen or similar, I cannot find any real example for it. Thanks

**Comment by brianvoe** [comment]
The docs site has usage of it. https://slimselectjs.com/settings#contentLocation

I need to see your issue to troubleshoot it. Put an example somewhere i can click and see it. I cant guess an issue like this i need to play with the elements and css to even attempt to make changes to slim select that would "fix" this issue your seeing.

**Comment by ir3ne** [comment]
@brianvoe thanks for the answer. I tried `contentLocation` on an editor and it works, so it's something broken in my project. Thanks for the support!
