### ISSUE TITLE
Is there a way to create select tag if not already present?

### ISSUE THREAD

**Issue by girish3** [brianvoe/slim-select#519]
First of all, I want to thank the author and all contributors to build such a useful library. 🙏

I wanted to know if there is a way to create a select tag if not already present. 
Similar to this react library use case https://react-select.com/home#creatable

<img width="400" alt="Screenshot 2024-02-04 at 4 43 15 PM" src="https://github.com/brianvoe/slim-select/assets/3092070/bd3b0aac-9e2b-41c4-918c-a082bd58a045">

If there is no such way, then is there a plan to implement creatable use case? (Also, I am happy to contribute)

Awaiting reply,

**Comment by brianvoe** [comment]
https://slimselectjs.com/events#addable
