### ISSUE TITLE
HighLight Issue when Using html Code

### ISSUE THREAD

**Issue by sonik14** [brianvoe/slim-select#52]
There is a highlight Issue if you use html code. It shows the whole code and not only the visible text.
This can be fixed by changing the line 1739 inside **option function** as follows: 

option.innerHTML = helper_1.highlight(data.text, this.main.slim.search.input.value, this.main.config.searchHighlighter);

The change is in **from data.innerHTML to data.text**.

I have also added a possibility (if the parameter is set) of deleting the tag by clicking on it, instead of the X only.
If you are interested ask me to push my code somewhere.

**Comment by sonik14** [comment]
I paste 2 screenshots. One with the problem and one with the problem solved.

![screenshot_2018-06-13 innovatiemonitor - innovatiespotter](https://user-images.githubusercontent.com/22293840/41360312-c692279a-6f2c-11e8-8c25-6a93e94385cc.png)

![screenshot_2018-06-13 innovatiemonitor - innovatiespotter 1](https://user-images.githubusercontent.com/22293840/41360319-c996c77a-6f2c-11e8-9867-4a56bb0eb548.png)

**Comment by brianvoe** [comment]
Ah! i think i see what you are saying. when doing searching is it also search the whole innerhtml with would include html tags.

Ok ill look into this and get this fixed as soon as i can.

Thanks!

**Comment by sonik14** [comment]
You are welcome. Keep in mind that I have already made it work. Check the change I have done (if I may miss something) so as to spend less time.

"
This can be fixed by changing the line 1739 inside option function as follows:

option.innerHTML = helper_1.highlight(data.text, this.main.slim.search.input.value, this.main.config.searchHighlighter);

The change is in from data.innerHTML to data.text.
"

**Comment by brianvoe** [comment]
Im open to pull requests if you have them

**Comment by brianvoe** [comment]
Fixed and pushed. version 1.16.0
