### ISSUE TITLE
Feature request: make CSS classes overwritable

### ISSUE THREAD

**Issue by Data5tream** [brianvoe/slim-select#522]
The CSS classes used in the render are already collected in a single object inside the render class, why not make them overwritable during initialization?

If this is something you are interested in, I might be able to provide a PR for it 😃

**Comment by brianvoe** [comment]
I dont know if there is enough value there but if you want to put together a really simple example i would be open to it.

**Comment by Data5tream** [comment]
@brianvoe
I think this issue can be closed, as you have merged my PR. Or do you want anything else done regarding CSS classes?
