### ISSUE TITLE
Accessibility: 'home', 'end', 'pgup' and 'pgdn' keys not registered

### ISSUE THREAD

**Issue by crystaler4** [brianvoe/slim-select#526]
In native select keys 'home', 'end', 'pgup' and 'pgdn' move the cursor to the beginning and to the end. With slim select options can be moved only with arrow keys. 

Can you also register these 4 keys for the most native experience possible?

**Comment by brianvoe** [comment]
if you want to test it out and submit a pr ill take a look at it
