### ISSUE TITLE
The "addable" callback is not triggered when the search bar is empty

### ISSUE THREAD

**Issue by Wykaz** [brianvoe/slim-select#528]
**Describe the bug**
The "addable" callback is not triggered when the search bar is empty

You can test it on this link : 
https://slimselectjs.com/events#addable

If this is how it's supposed to work, could there be an option in the "Option" object?

Can you fix this to give more freedom to the use of slim-select?

**Comment by brianvoe** [comment]
no thanks. not broken. if your allowing people to add an empty I think you might want to reconsider your approach to the problem.

**Comment by Wykaz** [comment]
Would it work if we set an option such as allowEmptyAddable in the Option object to false by default?

**Comment by brianvoe** [comment]
No thanks

**Comment by brianvoe** [comment]
No thanks
