### ISSUE TITLE
Retrieve selected data

### ISSUE THREAD

**Issue by thibaultchazal** [brianvoe/slim-select#53]
Hi @brianvoe ,

Thanks for this great piece of work.

I'm trying to send the user selected option through AJAX each time he add or remove an option.
I can't figure out how to retrieve the options selected by the user...
Do I missed something ?

Thanks per advance,
Thibault

**Comment by brianvoe** [comment]
http://slimselectjs.com/methods

```javascript
var select = new SlimSelect({
  select: '#select'
})
select.selected() // Will return a string or an array of string values
```
