### ISSUE TITLE
SlimSelect + modal (bug)

### ISSUE THREAD

**Issue by Dinver** [brianvoe/slim-select#534]
**Describe the bug**
Hi! Thank you for good library. But her not correct working with modals, especially on mobile devices. Settings "contentPosition" and "contentLocation", not help.

**Recreate it in Codepen**
![demo](https://github.com/brianvoe/slim-select/assets/36528841/e11cc07b-573d-40a0-83db-7362e0174719)

Current demo with micromodal library, but her not working and bootstrap.
https://codepen.io/dinver/pen/VwNbWdQ

**To Reproduce**
1. Open modal;
2. Scroll modal;
3. Open select;
4. Scroll modal.

**Comment by brianvoe** [comment]
Not broken. Its a debounce effect for checking position changes to render where to place the dropdown.

This looks more like you should not be scrolling an open select option.

Thanks for the complete issue submission.

**Comment by Dinver** [comment]
I still consider this a bug, since on a mobile phone scrolling occurs involuntarily, сorrect behavior:
https://codepen.io/dinver/pen/bGJWodq

**Comment by brianvoe** [comment]
submit a pr for close on scroll
