### ISSUE TITLE
Multiselect with HTML data

### ISSUE THREAD

**Issue by steven-bustos** [brianvoe/slim-select#536]
I just updated to v2.8.2 from v1.27, I used to use a multiple select with the innerHtml option, if I choose multiple options, those were displayed as selected with the HTML , now when I select multiple items from the list, I cannot see them as selected with the HTML but with the "text" attribute.

I also set the valuesUseText to false

https://codepen.io/Steven-Bustos/pen/MWROrZW

**Comment by brianvoe** [comment]
i cant put the html in the multiselect selected options.

**Comment by steven-bustos** [comment]
@brianvoe How? have you look the codepen? that's a simplified example of what I have in my project, the multiselect HTML is not set, it only show empty values: 
<img width="345" alt="image" src="https://github.com/brianvoe/slim-select/assets/150702661/c47aced9-426e-4257-9a87-b6c98ae27814">

**Comment by steven-bustos** [comment]
> How? have you look the codepen? that's a simplified example of what I have in my project, the multiselect HTML is not set, it only show empty values:

How? have you look the codepen? that's a simplified example of what I have in my project, the multiselect HTML is not set, it only show empty values:
![image](https://github.com/brianvoe/slim-select/assets/150702661/344fbe6f-0e18-442d-83d2-169ca67c150e)

**Comment by brianvoe** [comment]
set the text field to the value of just the text of your html. the multi select selected options will not use the html field it will use the text field fill out the text field.
