### ISSUE TITLE
Search slimselect not working in  wire-elements/modal(LIVEWIRE V3)

### ISSUE THREAD

**Issue by ign7** [brianvoe/slim-select#538]
When implementing slim select inside a livewire modal (wire-elements/modal), the search doesn't work, I'm using alpine.js to initialize the component, it loads everything correctly, it doesn't lose the css anymore, but the search inside the modal doesn't work, only outside the modal in other components livewire works fine

**Comment by brianvoe** [comment]
Sorry but i cannot account for what other packages or frameworks can or will do to effect the usage of Slim Select
