### ISSUE TITLE
Update function for times when the original select changes

### ISSUE THREAD

**Issue by KaWuGildner** [brianvoe/slim-select#542]
Hi,

is it possible to update slimselect, when the original select changes it's options?

I'm using WooCommerce and have a bunch of varations. WooCommerce reduces the options of a variation by default when selecting an option. 
For example: 
I have 1 Item, with the multiple colors (green, red, blue) and sizes (1,2,3,4,5,6), but not all color and size combinations exists. 
So for the color green there is only the sizes 1,5 and 6.

WooCommerce reduces the options in the original select accordingly, but slimselect won't be updatet. 

Destroying and re-initializing throws errors, so this is not a solution for me.

**Comment by brianvoe** [comment]
Issue not properly submitted. No repeatable example given.
