### ISSUE TITLE
Framework documentation: Rails/Hotwire

### ISSUE THREAD

**Issue by tsvallender** [brianvoe/slim-select#546]
Reaching out in response to the note on the website to do so with documentation getting set up on various frameworks. I’ve just written a short blog post showing how to set it up on a standard Rails setup. I’d be happy to add to/amend this for inclusion elsewhere if desired.

https://tsvallender.co.uk/blog_posts/rails-slim-select

**Comment by brianvoe** [comment]
Hey. Thanks for willing the help! You are more than welcome to contribute with a pr to the frameworks section if you would like. The slim select docs are in the same repo as slim select and uses vue(simple framework usage).

Clone repo, npm install, npm run dev, localhost:{whatever port terminal says}.

Let me know if you need any help

**Comment by mateyr** [comment]
> Reaching out in response to the note on the website to do so with documentation getting set up on various frameworks. I’ve just written a short blog post showing how to set it up on a standard Rails setup. I’d be happy to add to/amend this for inclusion elsewhere if desired.
> 
> https://tsvallender.co.uk/blog_posts/rails-slim-select

Here's another useful guide

https://blog.corsego.com/stimulus-slim-select
