### ISSUE TITLE
Add option to disable automatic focus of search field

### ISSUE THREAD

**Issue by ScoobyDid** [brianvoe/slim-select#549]
Feature request - add option to disable automatic focus of search field

if select has search feature enabled, when it opens, search input gets focus.

This is convenient on desktop, but on mobile, virtual keyboard appears every time select is opened - because search input gets focus.

It would be awesome to have an option to control whether the input should get focus, it probably should be not difficult to implement.

Currently a workaround for this is to blur input as soon as it gets focus, on beforeOpen event, but this is a crutch, it makes top navbar appear in mobile browsers if it was hidden (at least in chrome) and may not work in certain cases.

**Comment by brianvoe** [comment]
no thanks
