### ISSUE TITLE
Making the select required attribute visible

### ISSUE THREAD

**Issue by balessan** [brianvoe/slim-select#551]
**Describe the bug**

Following the discussion on the closed related issue: https://github.com/brianvoe/slim-select/issues/273
It looks like the proposed solutions do not work anymore.

Adding the CSS is overwritten by the slimselect initialization.
The slimSelect.render.showUI() method does not exist anymore

The required attribute presence does not trigger any error/validation message

**Recreate it in Codepen**

Tried to reproduce here: https://codepen.io/brianvoe/pen/MWXqXXV 
But in this basic example, the select is alway set to Option 1, that is not the case in my project though.

**To Reproduce**

**Comment by brianvoe** [comment]
Require hasnt been implement into slim select. If you would like to submit a pr Ill take a look at it.

the css part you didnt give me anything to look at so i have no idea what you issue is.
