### ISSUE TITLE
Does not work in nwjs

### ISSUE THREAD

**Issue by fusionstream** [brianvoe/slim-select#56]
Does not work in Node Webkit (nwjs) when installed as a node module and then imported via "import ... from" or "require". However, using the .js file and .css file directly does work.

**Comment by brianvoe** [comment]
If there is something i can update to make things work for nwjs i would be more than happy to do so but its not clear what needs to be changed in order to make things work for it.

**Comment by fusionstream** [comment]
Sorry I meant to add at the end that this was a placeholder till I found a workaround that didn't involve linking to the files via html, and that this was informative. Feel free to close this again.
