### ISSUE TITLE
CSS Flex-Box and searchHighlight setting

### ISSUE THREAD

**Issue by JakobBernoulli** [brianvoe/slim-select#560]
Hi all

When I set the **searchHighlight** option to `true`, the CSS flex setting causes the spaces around the search string to disappear. Therefore, I recommend removing the '`display: flex`' style from the class `.ss-content .ss-list .ss-option`.

Here is an image with `display:flex` applied:
![bad](https://github.com/user-attachments/assets/5bc6e688-ab86-4f2c-9e37-47333935238f)

And here is an image without `display:flex`:
![good](https://github.com/user-attachments/assets/4bbe5f42-9a8d-4eef-a0fc-f3a54a13d4ef)

What do you think?
Kind regards
Jakob

**Comment by brianvoe** [comment]
Can you give me a working example please

https://codepen.io/brianvoe/pen/MWXqXXV

**Comment by JakobBernoulli** [comment]
Hi brianvoe

didn't know how to edit your pen. But check out mine here:
[https://codepen.io/JakobBernoulli/pen/dyBpvOE](https://codepen.io/JakobBernoulli/pen/dyBpvOE)

**Comment by brianvoe** [comment]
ok i see what your talking about. I do think its something that should change. I have a list of updates im working on and ill try to get this added

**Comment by JakobBernoulli** [comment]
Thanks. Thats great. I am looking forward to the update. 😁

**Comment by brianvoe** [comment]
ok done will be out in next release

**Comment by JakobBernoulli** [comment]
Thank you for your work. I look forward to the change.
