### ISSUE TITLE
CSS Position arrow fixed

### ISSUE THREAD

**Issue by JakobBernoulli** [brianvoe/slim-select#561]
Hi Brian

I have another suggestion regarding CSS customization. With long option texts, the `select` tag is cut off and the arrow disappears. I would therefore position the arrow `fixed` so that it is always on the far right in the visible area. I have recreated the situation for you here: [https://codepen.io/JakobBernoulli/pen/YzoNoma](https://codepen.io/JakobBernoulli/pen/YzoNoma)

I have not recreated this for Multiselect and therefore do not know what influence these adjustments have. But maybe it fits.

What do you think of this idea?
Kind regards
Jakob

**Comment by brianvoe** [comment]
I agree this this as well. ill add this to my current list im working on.

**Comment by brianvoe** [comment]
I tried playing with this. Im not a fan of the absolute positioning. It messes with other things like deselect. 

After considering I think this is ultimately a design flaw of where ever this select dropdown would be placed that it needs to be struck down to such a small space. If you have a real world example like on a actual website you can show me that might help convince me.

Ill close this for now but will keep this in mind in the future.

Thanks

**Comment by JakobBernoulli** [comment]
Hey Brian

That's fine with me. The disappearance of the arrow occurs for me in Responsive Design - i.e. when displayed on a smartphone. I understand your aversion to absolute positioning. However, I can also make this adjustment in my projects myself.

Thank you for looking into this.

**Comment by brianvoe** [comment]
I tried to make it work with any of the flex types but none of them worked. :(
