### ISSUE TITLE
Feature Request: Searchable optgroup labels

### ISSUE THREAD

**Issue by fusionstream** [brianvoe/slim-select#57]
For example, and using the example at http://slimselectjs.com/selects, it would be nice if I am able to search for "Dairy" and have all options related to "Dairy" appear.

**Comment by brianvoe** [comment]
I hear what you are saying but in my original development I implemented that feature and it lead to more confusion and problems then it helped. Basic example is when you search something and non of the actual values matched but a group did that doesnt really help you select a value. If you did say show all value if a group matched then it showed a bunch of values that you are not wanting to see.

Sorry but i think unless i really get a good use case for this im going to punt on this feature.

Thanks anyway!

**Comment by fusionstream** [comment]
A sample use case would be where you have a listing of television sets.

The televisions are defined by model numbers such as SSEG32184-G, SSEG42184-G, PS-43218-36787, MG-4321245L, OLP34-371040, where the ones beginning with SS are from Samsung, the ones with PS and MG are from Panasonic (where MG is for a different type of panel) and the ones beginning with OLP are from Sharp, 

Obviously, these are going to be optgrouped according to brand. Imagine a list a mile long. Searching for say, "Samsung" will show only those in the optgroup with label "Samsung", shortening the list.

My use case is similar to this except I'm using it for professional A/V devices. Some devices are by default, called by their brand name and not their model name. For example, a "lightware" usually refers to a generic matrix switcher from Lightware. The actual model name would be say "MX8x8DVI-PRO". Being able to search for lightware and have all their devices listed, without having to start naming the devices "Lightware MX8x8DVI-PRO", while also retaining the optgroup label "Lightware", would be cool.

This feature does not have to be the default. It could simply be an option {"searchIncludesLabel": true}

**Comment by brianvoe** [comment]
I hear what you are saying. I like your example. Im doing a bit of refactoring at the moment but i will get this in as soon as i can. Do you have a deadline i need to be aware of?

**Comment by fusionstream** [comment]
This is free software and mine will be too. So no actual deadline. Thanks for reopening.

**Comment by fusionstream** [comment]
I've also now come across a situation where it would be cool if the search also searches for the values within the <option>.

With a similar example, the Pulse, made by Analogway, has a model number of PLS300, which in my case, I put in the value attribute of the option. Being able to search by values would also be cool.

I'm not sure if you're users would need this though. With the Dairy example, the optgroup could be Dairy with options of Ultimate Cheddar, Cheese Paste, Johnny Doe's Premium Brie, MerryBold Low Lactose Milk, FarmDirect Pasteurized. With the relevant data/value attributes, searching for Cheese will return the first 3, and searching for Milk will return the last 2.

**Comment by SSYinfo** [comment]
hi, whats the workaround here? 
to search by optgroup instead of the options themselves

**Comment by brianvoe** [comment]
New version of slim select has been released. If this is still an issue let me know and ill try to take care of it.

**Comment by 9mm** [comment]
I def wish it had this feature, it was the very first thing I looked for. Your example edge case above is solved by simply hiding labels that have no values

**Comment by brianvoe** [comment]
Should be an easy one for you to add. Submit a pr and ill get it in asap.
