### ISSUE TITLE
Open and search directly when typing

### ISSUE THREAD

**Issue by JakobBernoulli** [brianvoe/slim-select#573]
Hi Brian

Thank you for the great update recently. While using SlimSelect, I noticed that you can't start typing directly and trigger the search in the dropdown when navigating to the dropdown using the Tab key. I have to either select the dropdown with the Enter key or the mouse. Would it be an option to open the dropdown upon string input and pass the text directly into the search field?

What I don't want is for the dropdown to open automatically on every focus (because I have many such dropdowns, and if they all open one after another when tabbing through, you'd have a nervous breakdown). I only want it to open automatically where the user wants to search for something. Otherwise, on mere focus, nothing should happen.

Kind regards
Jakob Bernoulli

**Comment by brianvoe** [comment]
Sorry i dont fully understand what your saying. Just step by step say what you would like to happen and maybe ill be able to follow you that way.

**Comment by JakobBernoulli** [comment]
Hi Brian

Sorry, I didn't have time to write to your reply. I have now created a pen which should make the issue easier to understand. It would be great if you could take another look at it.

[https://codepen.io/JakobBernoulli/pen/zYVKZKL](https://codepen.io/JakobBernoulli/pen/zYVKZKL)

Best regards
Jakob
