### ISSUE TITLE
Open and search directly when typing — renewed

### ISSUE THREAD

**Issue by JakobBernoulli** [brianvoe/slim-select#585]
Hi Brian

I was too late to reply to your request last time and now I don't think you've seen my reply. That's why I'm taking the liberty of starting a new issue again. I have now created a pen which should make the issue easier to understand. It would be great if you could take another look at it.

[https://codepen.io/JakobBernoulli/pen/zYVKZKL](https://codepen.io/JakobBernoulli/pen/zYVKZKL)

Best regards
Jakob

_Originally posted by @JakobBernoulli in https://github.com/brianvoe/slim-select/issues/573#issuecomment-2431285080_

**Comment by eduardolat** [comment]
+1

**Comment by brianvoe** [comment]
+1

**Comment by brianvoe** [comment]
fixed 2.10.0

**Comment by JakobBernoulli** [comment]
Thanks Brian. Hero of the day :).

**Comment by brianvoe** [comment]
https://github.com/sponsors/brianvoe
