### ISSUE TITLE
Make String "Searching..." configurable

### ISSUE THREAD

**Issue by Shoplifter** [brianvoe/slim-select#59]
.. as the other strings used in SlimSelect

**Comment by brianvoe** [comment]
Ok ill add it to the list

**Comment by Shoplifter** [comment]
Thank you very much

**Comment by brianvoe** [comment]
This has been added and will be out in the next release

**Comment by brianvoe** [comment]
I did update things to version 1.18.0 last night. If you could upgrade and let me know that everything is work as it should that would be a great help
