### ISSUE TITLE
Disable animation setting. Redraw list position after action, not by setInterval

### ISSUE THREAD

**Issue by SergeyXXI** [brianvoe/slim-select#590]
Hi, I need instantly adding or deleting options in multiple select, without any animation and delayed position shifting options list. I didn't find such setting that disables animation, so I've just overrided default css styles, but I've found out as minimum 2 target places in the code, where you use js timeout delays:

1) **render.ts**:

![image](https://github.com/user-attachments/assets/ae6316f0-8cdb-42e8-a25e-3ea785aa24ce)

Here it's not big deal just 100ms, but anyway make this optional please: if (future) setting is disabled, than dont' add class with valueOut animation and setTImeout.

2) **index.ts**:
![image](https://github.com/user-attachments/assets/8e9df66c-62d4-4da5-9124-f7e9491204b2)

Here I've just don't get your idea, so I have some questions. First, why 500 ms interval, and not, for example, 100, 50, 5? And second, why don't you use recalculating and redrawing list position just after adding or deleting option in multiple select, instead of cycling it with interval? If it is some kind of lazy stuff, well, I suggest you to refactor it.

Now, this all can be fixed with contentPosition(relative) + contentLocation + css overriding, but it will be nice in general, if you make it not to be like 'crutch'(I'm not sure, if such term is used in english) fix.

Thanks!

**Comment by brianvoe** [comment]
Javascript forces you to do crazy things.

If you have a better implementation, you are more than welcome to submit a pr.

Thanks.
