### ISSUE TITLE
How to get selected value with multi selects?

### ISSUE THREAD

**Issue by mburakerman** [brianvoe/slim-select#6]
When i call onChange, i can't get selected value with multi select. Can you show me how?

https://jsfiddle.net/amm9d5d3/

**Edit:** [This](https://jsfiddle.net/oh6m2z31/) works but after selecting an option, it fails.

**Comment by lekoaf** [comment]
This seems to work.
https://jsfiddle.net/anf8hwvr/

**Comment by mburakerman** [comment]
No. It does not. When i click, i want to get the value of clicked option.

For ex. [this](https://jsfiddle.net/1utzw8hc/) show first option's value but not clicked option.

**Comment by lekoaf** [comment]
Ah, now I get what you mean. No I don't see how you could know. Since it's not even added last in the array. They are added in the order of the way they are in the select.

**Comment by mburakerman** [comment]
Dude, i checked again and saw that my demo is working.  Click an option, it alerts the clicked value!

https://jsfiddle.net/uvwfqmc8/

**Comment by brianvoe** [comment]
Hey guys, that is an interesting point. So right now it just appends the recent value to the end of the selected array, so they are not in the order of the original select.

To get some better understanding of the issue you are trying to accomplish could explain the real life situation you would like to solve?

**Comment by mburakerman** [comment]
I see.  
I was trying to make demo where i update list when someone select an option. 
Instead of getting all selected options, i tried to get clicked option so, i face with that and wanted to ask.

But, problem is solved. Thanks!

**Comment by brianvoe** [comment]
Ok sounds good. Let me know if there is anything else i can help you with. Also let me know how you like it so far.

Thanks.
