### ISSUE TITLE
Unable to setData when slimselect is disabled.

### ISSUE THREAD

**Issue by fusionstream** [brianvoe/slim-select#60]
Unable to apply setData when slimselect is disabled.

It would be cool if we could do this so that we firmly disallow the user from making changes while we update possible options.

Failing that, would be cool if documentation is updated to point out this limitation.

**Comment by brianvoe** [comment]
This is a good catch. Ill add it to the list of things to update

**Comment by brianvoe** [comment]
Not sure if this was really broken. Or its a specific browser thats the issue. But in the current version im about to release it does allow you to setData when a selection is disabled

**Comment by brianvoe** [comment]
I did update things to version 1.18.0 last night. If you could upgrade and let me know that everything is work as it should that would be a great help
