### ISSUE TITLE
Have initial no selected option with "Select value" as placeholder in single mode

### ISSUE THREAD

**Issue by fusionstream** [brianvoe/slim-select#62]
With the default dropdown, this is possible to achieve by setting the option as selected, disabled, and having a display style of 'none'. Once the user selects another option, the initial option is no longer selectable or visible.

It seems to also be somewhat possible here because when no options are present in the select, slim select displays "Select Value".

Perhaps including the first option with null text and null value could trigger this feature? This would allow this feature to also be present when setData is used to update possible options.

**Comment by fusionstream** [comment]
I have discovered that the initial no-selection is possible to achieve by setting the select's selectedIndex to a negative integer before initialising the slimselect instance.

It doesn't seem possible to achieve this via setData after you've created the instance so I've resorted to updating options with setData, destroying the instance, setting the original select's selectedIndex to -1, then initialising a new instance of slimselect on the select.

**Comment by fusionstream** [comment]
Just for clarification, slimselect actually does allow one to define whether a placeholder is present (the initial value shown when no option is selected) and what text it will show. This is under the 'placeholder' option in the documentation.

For use with setData, your first array object should be
````
{'placeholder':` true, 'text': 'anyarbitrarytext'}
````

**Comment by jnschrag** [comment]
Just responding to say that I also had this use case and @fusionstream's final response was the method I ended up using. It would be great to add this to the docs.

**Comment by brianvoe** [comment]
hey @jnschrag 
I you could add an issue specifically asking for this to be in docs that would help me keep a running list of things i need to update.

Thanks!
