### ISSUE TITLE
Multi select Ajax - previously selected items and menu flashing while adding more items

### ISSUE THREAD

**Issue by zoltantef** [brianvoe/slim-select#63]
Steps to reproduce:

1. Use Ajax multiple here: http://slimselectjs.com/options
2. Search for a text, select one result
3. Search for another text
4. flashing1: the full dropdown menu flashes with the previously selected items
5. flashing2: the previously selected items flashing one more time

Could you check on this?

**Comment by brianvoe** [comment]
This is a great catch. Ill put it on my list of things to tackle.

Thanks for pointing this out.

**Comment by brianvoe** [comment]
Is this a current issue for you that you have a deadline you need to hit?

**Comment by zoltantef** [comment]
I'm thinking about migrating from my current plugin to Slim Select - and this is the part which I would use mainly. I planned to start working on this this weekend, but I have to consider other ways if it is not an easy fix. It is not life or death for me, but it seems so nice, elegant and flexible - I'd feel sad if I couldn't play with it... So I really hope the best. :)

**Comment by brianvoe** [comment]
Its an easy fix. The only reason i ask is because im making other large adjustments to the build system and have a list of other alterations that people wanted to make.

So ill get to it but it make take a week or so to get to.

**Comment by zoltantef** [comment]
Thank you, that's good to hear. I'm looking forward to the fix.

**Comment by brianvoe** [comment]
After looking into this i came to find out its a fetch race condition issue more than anything. I added some notes in the docs to helpfully help with this. Ill be releasing soon.
