### ISSUE TITLE
I can't add a new custom items to an Ajax multiple select

### ISSUE THREAD

**Issue by zoltantef** [brianvoe/slim-select#64]
As promised I'm trying my luck with Slim Select. I'm now facing an issue which I can't seem to solve: I'm using the Ajax based multiple select box, and I want to add custom values too from another part of the UI beside the Ajax search results. 

I'm using this for adding new items: `$('#example').append('<option value="foo" selected="selected">Foo</option>');` which works fine when the select is not Ajax based. But when it is, although the items added to the underlying select, they won't show up, also at the next search they are removed from it.

Any ideas how can I make this work?

**Comment by brianvoe** [comment]
So in your situation it sounds like you may need to adjust your perspective on how you are tackling things like this. What i would do is first get off of jquery, haha. In regards to the options themselves you shouldnt need to append anything to the original select. Let the ajax callback searching derive the values that get populated in your selection options. Basically when your results come in from the ajax request you can add your custom values to that before you pass it to the callback.

Hope this helps.

P.S. Really get of jquery your better than that!

**Comment by zoltantef** [comment]
I think skipping jquery will be a project for my next life :)

What I ment was there are other elements on the site which should add other values to this multi select. Imagine it like you have the Ajax query for movie titles, then you have another combo box from where you can add drama, action, comedy etc. And at the end you submit the multiple selected movie titles together with multiple tags to the search.

**Comment by brianvoe** [comment]
Is that the exact use case. Cause in that situation i would have my primary genre select a static set. The based upon that selection would be the endpoint i would hit for searching of that section.
