### ISSUE TITLE
Is there a way to distinguish between changes triggered by user interaction or pogrammatically

### ISSUE THREAD

**Issue by Shoplifter** [brianvoe/slim-select#65]
Currently both ways to change the current value of a select triggers the change event, where imho only user interaction should do so (as with plain selects).

my use case:
I have 5 select elements interdependent on each other. If one of those is reset `slimSelect.set('')` - the others should be reset too. I can avoid circular reference by `if(slimSelect.selected() !== '') slimSelect.set('')`.
But I also need to reset only one or two selects without triggering all this. Is ther any way to do so?

**Comment by brianvoe** [comment]
Hey @Shoplifter 

I totally hear what you are saying. But i have had people say the same thing on the opposite side where they have a workflow that is based upon the onchange. Mostly thing like do other operations (hide show another dropdown based upon current selects value) that is highly dependent on triggered changes whether those changes are done manually or programatically.

For your situation i wold do what your suggesting and wrap it ```if(slimSelect.selected() !== '') slimSelect.set('')```

For your reset issue can you please give me a little more to go off of. I dont fully grasp your situation.

Thanks.

**Comment by Shoplifter** [comment]
Hi @brianvoe 

here's a scrrenshot:
![image](https://user-images.githubusercontent.com/1181094/44602608-5ecff500-a7e0-11e8-9e37-b20f2ffc58c9.png)

my business logic now is as follows:

- if one of these 5 selects is set to its placeholder value, all others shoud bet set to '' too.
- if some specific order class is selected only LPC and Product Group should be set to ''. (only for some order classes, not all of them)
- in the backend a whitelist is configured, that lists all allowed combinations of these 5 selects, so changing any of these to particular value will trigger rerendering the other 4 selects and remove options from those, so that only valid combinations remain. if no valid combinations are left, the 4 other selects schould be set to '' again. (But not the one that has been changed)

the second task automatically triggers the first one, which is not intended.
the third task may also drive me into that situation.

I do not agree with the people that needed the opposite behaviour. Although this is certainly conveniant under circumstances, for their situation a few lines of code would have solved their problem (either by dispatch event or call directly the functions bound to the change event). But my situation seems like a deadlock to me or at least i cannot see any way out of this. I suppose, plain selects behave as they do for a good reason.

**Comment by brianvoe** [comment]
Hey @Shoplifter 

I see better what you are talking about, thanks for clarifying. Although my answer is the same on this situation, the best i can say right now is even if i wanted to change it to work the other way i couldnt due to the fact it would be a breaking change. So in the next version of things i can reevaluate and see if it makes sense to work the other way around.

Let me know if you have any other questions i can help you out with.

Thanks

**Comment by Shoplifter** [comment]
Hi @brianvoe 
Thanks for answering this. Nobody likes BCs,  so obviously not an issue for current version development. Maybe next version then. As my usecase is concerned, not the smoothest but hopefully accepatble solution would be: Disable and hide the affected fields and then sanitize in backend processing.

**Comment by brianvoe** [comment]
👍
