### ISSUE TITLE
(Optional) different search behaviour?

### ISSUE THREAD

**Issue by Shoplifter** [brianvoe/slim-select#67]
Hi @brianvoe 

Is it possible to introduce a new option to specify how the search is executed, so that the search string has to be at the start of the option text not just anywhere in in it. 
Or even make the appropriate filter function a callback option like e.g. 
```javascript
{
    select: element,
    search: true,
    searchFilter: function(text, search){return text.indexOf(search) !== -1 } // default search
    /* OR */searchFilter: function(text, search){return text.substr(0, search.length) === search } // for matching the start
    /* OR */searchFilter: function(text, search){return text === search } // for exact search
}
```
Sorry, that I cannot send a PR because I am not used to typescript but i modified slimslect.js from dist folder and works pretty well.
Here's a [gist](https://gist.github.com/Shoplifter/b85d9fab681546a61b6f84318189e49b#file-gistfile1-txt) of it.

**Comment by brianvoe** [comment]
For this i would use the ajax function. The function passes in the search value and you can use the callback to pass back the values you want that match your search.

**Comment by Shoplifter** [comment]
Sorry for my late answer. My searchfilter hack worked well, so I had no need to change that for a while, but of course thats a problem for updating to upcoming relesaes.

I just tried to use ajax callback for filtering searches and it works very well.
Thank you. 
To me that is a fairly important feature. Do you consider to take that into documentation?

**Comment by brianvoe** [comment]
So triggering an ajax call on a back to zero is definitely something i will add in. Ill add a separate issue to make sure thats in.

As far as restoring the previous options thats up to the developer to handle

**Comment by Shoplifter** [comment]
Great to hear, than thank you.

**Comment by Shoplifter** [comment]
Well, getting closer and closer, I think.
I'm holding initial options in a var outside the ajax function and that works.
I am using SlimSelects `data.data` to do this

Unfortunately I have two othe issues now
- Using the ajax function interefers somhow with the initial setting of data, what I need to, to use some innerHtml. If I use both, the ajax and the data option, the result is:
the select is rendered without the inner html initially, when i select an item, this is ignored. when I select an item (any item) again I see the inner html and also can select an option now.
- re-setting back the data via ajax (this time without data option on initilization)
In that case setting data attributes also work but [data set name conversion](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/dataset#Name_conversion) seems wrong (it is prefixed with `data-)` but camelCase is  not lconverted back to dash style notation

**Comment by brianvoe** [comment]
Im working on the maintenance of options to keep data attributes. So that should be in there hopefully in the not too distant future.

I regardst to ajax interference with initial data set. I would suggest forking the develop branch and show me how you think it should work to facilitate your needs.

Or maybe its just a matter helping me understand your specific need. Cause i feel like i might tackle your situation differently.

**Comment by Shoplifter** [comment]
hi @brianvoe 
did you have a chance to take a look at the gist I posted above?
I just updated it right now and really think that 'searchFilter' would be a useful option to take for many users. Look for string searchFilter to get the changes, I think it's only 5 lines of code added/changed.
No BCs, just one more option like
````
{
...
searchFIlter: function(opt,search){ return boolean; }
...
}
````
Unfortunately I'm not at all familiar with Typescript, and used the js file of the dist folder instead.
(master branch, ther's no dist in dev branch)

**Comment by brianvoe** [comment]
So whats stopping you from just using ajax and taking in the search string and doing the minimization of your local data set? I would do the same thing

**Comment by Shoplifter** [comment]
Thats the code I would need on user side with a new searchFillter option
````
searchFilter: function(opt, search) {
    return opt.text.substr(0, search.length).toLowerCase() === search;
}
`````
It just works. No downsides I am aware of until now.

And that's the code needed doing with the ajax option:
````
var origData;
var slim = new SlimSelect(element, {
     ....
    ajax: function(search, callback) {
        var data = [],
            l = origData.length;
        search = search.toLowerCase();
        for(var i= 0; i < l; i++) {
            if(origData[i].placeholder === 'true') continue;
            if (origData[i].hasOwnProperty('options')) {
                var options = origData[i].options.filter(function (opt) {
                    if(opt.text.toLowerCase().substr(0, search.length) === search) {
                        data[data.length] = opt;
                    }
                });
            }
            if (origData[i].hasOwnProperty('text')) {
                if(origData[i].text.toLowerCase().substr(0, search.length) === search) {
                    data[data.length] = origData[i];
                }
            }
        }
        callback(data);
    }
});
origData = slim.data.data
````
... which is a lot more bloated and needs to manage data outside the ajax function. Data, that are created when SlimSelect is initialized, but also neded in the ajax function which in turn is provided as parameter for initialization. It duplicates code which is already in the search funtion of slimSelect. And it still has bugs: initial data setting not working, `slim.enable()` / `slim.disable()` throws an errror `Error: Uncaught TypeError: Cannot read property 'observe' of undefined at select.observeMutationObserver`. I have really no idea what to do about that.

Maybe I'm totally on the wrong track doing it the way? I've got the feeling you have something simpler in mind :)
