### ISSUE TITLE
ParsleyJS supported?

### ISSUE THREAD

**Issue by kriss145** [brianvoe/slim-select#69]
Hi,

Slim select works with ParsleyJS? I have a problem when class "parsley-error" isn't added

**Comment by brianvoe** [comment]
Im assuming the class gets added after slim is already initiated. Right now the inherited class only gets grabbed when slim select gets initiated.

**Comment by maciej-laskowski** [comment]
@kriss145 you can try BunnyJS, it works with slim-select if you wrap everything in a div.
