### ISSUE TITLE
Enter submits instead of picking highlighted item

### ISSUE THREAD

**Issue by SebastianVomMeer** [brianvoe/slim-select#7]
I am not sure if that is the intended behaviour or a bug: I start typing, press cursor down to highlight the wanted item and press enter to pick it. But instead of adding it to the collection the whole form is submitted. I think this is confusing. :dizzy: 

Nevertheless, great work and thanks for sharing! :+1:

**Comment by brianvoe** [comment]
Hmm thats a great catch. Ill be sure to update and add prevent default on the input field.

Thanks!

**Comment by brianvoe** [comment]
Sorry for the delay. I did get a chance to make that update for you. you can use version 1.1.2 and it wont submit your forms anymore.

Let me know if that works for you.

Thanks!
