### ISSUE TITLE
Problems in firefox 47 on multi select

### ISSUE THREAD

**Issue by ThomasWT** [brianvoe/slim-select#71]
I can add some of the items on the list but a lot of them is giving me an error onClick.

`TypeError: t[(o - 1)].insertAdjacentElement is not a function`

**Comment by brianvoe** [comment]
ok ill look into this. Thanks!

**Comment by brianvoe** [comment]
Fixed. Will be out in next release

**Comment by brianvoe** [comment]
I did update things to version 1.18.0 last night. If you could upgrade and let me know that everything is work as it should that would be a great help
