### ISSUE TITLE
old typescript issue

### ISSUE THREAD

**Issue by Xiapeixu** [brianvoe/slim-select#72]
Errors can occur if it's an older version of typescript
/ / Events
Ajax: Function Error in this row
[tslint] Don 't use' Function as a type. Get using the ` Function ` type. -- a specific Function type, like ` () = > void `. (ban - types)
[tslint] Missing semicolon (semicolon)

**Comment by Xiapeixu** [comment]
I'm sorry. I know what the problem is.  Do you know tslint. It was an error reported by tslint

**Comment by brianvoe** [comment]
i am familiar with tslint. I used it to build slimselect

**Comment by Xiapeixu** [comment]
I set some rules in tslint.json
