### ISSUE TITLE
Setting data for disabled select does not show placeholder or selected option (if any)

### ISSUE THREAD

**Issue by Shoplifter** [brianvoe/slim-select#75]
maybe related to #60 
Setting data for a disabled select:
Options are rendered, but the selected option does not show up. Neither does the placeholder if no option is selected.
````html
<div class="ss-single-selected ss-disabled">
    <span class="placeholder">{THIS IS EMPTY}</span>
    <span class="ss-deselect">X</span>
    <span class="ss-arrow"><span class="arrow-down"></span></span>
</div>
````

Unfortunately I cannot find a workaround for this either. Enabling, inistatiating and disabling gives the same result. Any other ideas to workaround this?

**Comment by brianvoe** [comment]
Can you show me screen shots or a gif of this?

**Comment by Shoplifter** [comment]
I m AFK till Monday. I ll post the screenshots then as soon as I can. 
But they re not hard to imagine.
If enabled it looks like #65(github.com/brianvoe/slim-select/issues/65)  - the sales account select. If disabled it s just an empty gray rectangle

**Comment by brianvoe** [comment]
I understand what your saying im just not seeing that when doing my own tests. Ive tested setting something to disabled both on the original select as well as via the method call. Both visually display the disable style properly. and then i tested using setData against it when its disabled and the data updates as well as the onChange value triggers.

So in order for me to help you out I just need a little more about what your experiencing that isnt working against the tests i just did. One thing i can say is i did a big release earlier this week, maybe its just a matter of upgrading to the newest version

**Comment by Shoplifter** [comment]
Screenshots:
same html and js for both with the only difference that the second select has the attribute `disabled="disabled"`

![image](https://user-images.githubusercontent.com/1181094/46598764-84d9fc00-cae5-11e8-9536-2963557389f7.png)
![image](https://user-images.githubusercontent.com/1181094/46598803-ad61f600-cae5-11e8-8385-de74c3bf3475.png)

**Comment by brianvoe** [comment]
![set_data_disabled](https://user-images.githubusercontent.com/1580910/46613707-7dacf100-cad9-11e8-8651-f1f49fa218c8.gif)

**Comment by brianvoe** [comment]
So this is why i am curious as to your issue. Cause i am not getting this at all i disabled both single and multiple and was able to set data. you cant see it in the gif but i did move my cursor over the selects and tried to click them.

So at this point im going to need more info from you. What browser are you using, version, os anything you can to help me replicate this in the same environment your in.

Thanks.

**Comment by Shoplifter** [comment]
Hi @brianvoe 
see https://github.com/Shoplifter/slim-select-bug-demo for a demo.
![image](https://user-images.githubusercontent.com/1181094/46620545-511ec680-cb25-11e8-853a-99e81ee5b38a.png)

The disabled selects do not show the placeholder text, nor the text of the selected option.

**Comment by brianvoe** [comment]
It looks more like you have a styling issue than this actually being a slim select issue.

**Comment by brianvoe** [comment]
to easily find out comment out your demo styles.

**Comment by Shoplifter** [comment]
I only added minimal styles in addition to slimselect's default styles, doesn't look different without these.

**Comment by brianvoe** [comment]
Ok i was able to replicate this issue. ill get to the bottom of it and figure it out. Thanks

**Comment by Shoplifter** [comment]
thank you

**Comment by Shoplifter** [comment]
Just saw, that deselcting is also possible with disabled selects. Is this intended?

**Comment by brianvoe** [comment]
No. I saw that too. Looks like they might be related in some aspect.

**Comment by brianvoe** [comment]
This one was a tricky one! But i was able to fix it and also fixed the disabled deselect issue as well. v1.18.2
