### ISSUE TITLE
How do you pre-select elements?

### ISSUE THREAD

**Issue by Drillan767** [brianvoe/slim-select#78]
Hello, 
thank you for your work, it's really awesome!
I just have one question, how sould I pre-select elements?
I have a multi-select that I would like to use in a edit form, and display to the user what element have been selected on an article's creation. I saw it was possible from your multiple examples you give on your website, but I couldn't find any method to preselect anything.

Thank you in advance

**Comment by maciej-laskowski** [comment]
The simpliest way to preselect elements is to make sure they are selected on native `select` element when you initialize slim-select on it. If you render:

```
<select id="multiple" multiple>
  <option value="value 1">Value 1</option>
  <option value="value 2 selected">Value 2</option>
  <option value="value 3 selected">Value 3</option>
</select>
```
and then run 
```
new SlimSelect({
  select: '#multiple'
})
```
two last elements will remain selected in slim-select.

**Comment by brianvoe** [comment]
Thanks for your kind words!

@maciej-laskowski is correct. You can think of it just like any other normal select dropdown. adding selected to your options sets the select. Slim select will look at your select dropdown and get information on how to build slim based upon it.

You can also use data parameter to pass in options you would like to set as data.

**Comment by Drillan767** [comment]
Hello, thank you guys for this quick reply but it, huh, doesn't work.
I'm using VueJS and making a loop to display every single option available.

```
<div class="form-group">
    <label for="tags">Tags</label>
    <select id="tags" multiple v-model="post.tags">
        <option
            v-for="(tag, index) in tags"
           :key="index" :value="tag.id"
           :selected="preset.includes(tag.id)"
         >
            {{ tag.name }}
        </option>
    </select>
</div>
```

I tried "both" ways, either by setting "selected" by default, or, in this case, conditionally. The HTML output works fine, everything that should be selected is correctly. Here is how the rendered select looks like:

```
<select multiple="multiple" id="tags" tabindex="-1" data-ssid="ss-89834" style="display: none;">
    <option selected="selected" value="1">PHP</option>
     <option selected="selected" value="2">Ruby</option>
     <option selected="selected" value="3">JavaScript</option>
     <option selected="selected" value="4">VueJS</option>
</select>
```
However, nothing happens from Slim Select.

**Comment by brianvoe** [comment]
Ok ill take a look at this and see if i can replicate it

**Comment by brianvoe** [comment]
So i just ran this on a [jsfiddle](http://jsfiddle.net/fgz684b7/) and everything worked fine

**Comment by brianvoe** [comment]
I would suggest not using jquery
