### ISSUE TITLE
Tab focus when disabled

### ISSUE THREAD

**Issue by benplum** [brianvoe/slim-select#8]
Users can still tab and change the value when the select is disabled. What about a check to see if the select is disabled before opening it (https://github.com/brianvoe/slim-select/blob/master/src/slim-select/create.ts#L290)?

**Comment by brianvoe** [comment]
Sounds good. Ill make an update and get that working properly. Thanks for the catch!

**Comment by brianvoe** [comment]
Updated and pushed. v1.1.3
I disabled open if tabing to and added disabled to the search input.
Let me know if that works for you.
Good catch!
