### ISSUE TITLE
Required Notification Not Showing on multiple select

### ISSUE THREAD

**Issue by ghost** [brianvoe/slim-select#81]
I'm using your multiple select dropdown and i have added the `required` attribute onto the `select` but if i did not select any of the options it does not display the `Please Select An Item In The List` message as normally it would on Google Chrome version 69.0.3497.100. Any issues here or I have missed out anything

```
<select name="colab[]" id="colab" class="form-control" placeholder="Select Your Member" required multiple>
    <option value="" disabled>Select Your Member</option>
    @foreach ($allUser as $users)
    <option value="{{$users->u_id}}">{{$users->name}}</option>
    @endforeach
</select>

new SlimSelect({
    select: '#colab',
    placeholder: 'Select Your Member',
});

```

**Comment by brianvoe** [comment]
This is an interesting one. Havent had anyone need it yet. Let me put some thought in how i would get this to work with slim select.

**Comment by dextersiah1998** [comment]
Alright thank you

**Comment by brianvoe** [comment]
Well let me start by asking you what do you expect to happen?

**Comment by dextersiah1998** [comment]
Well, i have a form that i need all the fields to be required including the mutiple select. So if i select on my `submit` button without selecting any item in my `select` it would display as the message `Please Select An Item In The List` similar to Google Chrome's required message

**Comment by brianvoe** [comment]
Thats what i figured. Let me figure something out

**Comment by maciej-laskowski** [comment]
I stumbled across this one as well but didn't want to flood @brianvoe with my problems too much ;) Native browser validation does not work as it's applied on the original `select` element that is hidden by `slim-select`. I initially considered adding `oninvalid` event to the original `select`
```
<select id="single" oninvalid="this.slim.slim.container.classList.add('is-invalid')">
  <option value="value 1">Value 1</option>
  <option value="value 2">Value 2</option>
  <option value="value 3">Value 3</option>
</select>
```
This simply add a class to slim select element as original select get invalidated. Slim could register such event listiner internally.

Anyways, the other problem is that only Webkit allows to style those `inline bubbles` as they call them and I need to style validation errors so I dropped native validation in favor of BunnyJS for now. Maybe it is a solution for you @dextersiah1998 as well?

**Comment by maciej-laskowski** [comment]
@dextersiah1998 I believe I found a reliable way to enable native browser validation in slim-select, I'll try to submit a PR soon.

**Comment by brianvoe** [comment]
:+1:

**Comment by brianvoe** [comment]
The more i look into this i would suggest using the beforeOnChange to validate the value before allowing it to change. I looked the pr that made css changes to trick the browser to being there and came a couple of issues that didnt seem like it was as good at utilizing the beforeOnChange callback for validating value changes.

Im open to discussion but im going to close this for now.

**Comment by maciej-laskowski** [comment]
@brianvoe Thank you for your feedback! beforeOnChange can be used to validate the selection but not to validate whether anything has been selected at all which is the `required` attribute intention so it is not ideal.

**Comment by stanolacko** [comment]
Problem is, that currently I you are not testing values in form by some JS and you want to take advantage of HTML5, you are not able to use it with slimselect. When you have empty <select required> with slimselect, Browser do nothing after submit, becasue you get Javascript error:
`An invalid form control with name='person' is not focusable.`
Solution from [maciej-laskowski](/maciej-laskowski) works. I preffer to use his idea.

**Comment by brianvoe** [comment]
The simple solution is style the original select however you want. It currently sets it to display: none. but you can set it to something that better suites your needs.

**Comment by stanolacko** [comment]
Yes it's possible, but it can be confused for others, tha it's not working.

**Comment by karlkras** [comment]
so, I guess there's no solution for this?

**Comment by JoshMayberry** [comment]
If I have a select element with the 'required' attribute, when the form is submitted it should show an error.
Unfortunately, slim-select puts the css style `display: none;` on the select element- so the error message doesn't show.
![image](https://user-images.githubusercontent.com/11482252/196490197-a0b797a6-9f46-4e2c-aa3c-8f0a3a564bff.png)

We should be able to hijack this though. If when the select was invalid it put a class on the root container, and removed it when it was nolonger invalid- we could get an invalid message to show the user why the form is not submitting.

Here is a CodePen that does just that. I'm sure someone else can come up with a more elegant way to do this- but hopefully this will be a good starting point.
https://codepen.io/joshmayberry/pen/YzLbVGd
