### ISSUE TITLE
Search inputs that are generated by Slim Select are not accessibility compliant

### ISSUE THREAD

**Issue by baverstockUX** [brianvoe/slim-select#84]
![image](https://user-images.githubusercontent.com/26738117/48566266-4a3c5e00-e8f2-11e8-8e37-5b1979822448.png)

As these are generated by the script it is difficult to attach ids and labels for them. Is there anything that could be done to get this to pass?

**Comment by brianvoe** [comment]
Can you give me a little bit of context to what you are trying to accomplish. This might help me wrap my head around your issue a little better.

Thanks

**Comment by baverstockUX** [comment]
Thanks very much for replying Brian. The issue is down to Accessbility compliance, namely WCAG 2.0, which is of high priority to one of our customers. We've been looking at various lightweight single/multi selects and have been very impressed with Slim Select. However, we use various tooling validate Accessibility, which flags any issues that would cause problems with either keyboard users or screen readers etc. In this case, it looks as though there is an input created without an associated <label> element, as it is the search bar within the dropdown itself. I'm just wondering what could potentially be done to fix this (happy to try and submit a PR) so that this issue does not get flagged. We may need to dynamically create a label/input id pairing in the JS and then hide the labels except for screen readers.

**Comment by brianvoe** [comment]
Thanks for that explanation. Im not super familiar with accessibility compliance but i am more than happy to help.

If you want to run the docs so you can make sure your changes work. Ill give you a couple of simple steps to get it running locally.
1. clone or fork and pull it down
2. run npm install
3. run npm dev - that will run the docs on port 8080
4. the slim select files are src/slim-select
5. Edit the file slim.ts
6. On line 331 is the part where i create the search div section. There youll find the input field
7. The running app has hot reloading(it uses vue-cli), make sure it works the way you like
8. Do a pr and ill create a release branch for it and get it updated

Let me know if you have any questions.
Thanks.

**Comment by brianvoe** [comment]
Going through some issues and I would like to help tackle this but need a little help making adjustments to fit standards. Ill keep this open a little longer but if i dont hear anything back ill close this till a later date.

**Comment by wojtek-zajac** [comment]
@brianvoe I'm happy to create a PR and add a label to the input element in upcoming days. Are you still interested in this change?

**Comment by brianvoe** [comment]
absolutely!
