### ISSUE TITLE
Add a new options dynamically

### ISSUE THREAD

**Issue by professorkolik** [brianvoe/slim-select#85]
@brianvoe Thank you for very flexible plugin!
I've already spent few hours debugging the library, but no chance to get success with my issue

How I can dynamically add a single option and make it selected?

P.S. By "dynamically" I meant that I have a button and when I click on it, new option going to be added to select and be selected. Thank you in advance!

**Comment by professorkolik** [comment]
*[UPDATE]* Found a way

1. slim.addData({
        value: 'value',
        text: 'text'
      });
2. slim.setSelected('value')

**Comment by brianvoe** [comment]
Sorry i wasnt able to comment quicker. Glad you found the way.
