### ISSUE TITLE
Settings with data and ajax on a multiple select do not display selected items

### ISSUE THREAD

**Issue by Shoplifter** [brianvoe/slim-select#89]
Hi @brianvoe 
I try to use SlimSelect with following options:
![image](https://user-images.githubusercontent.com/1181094/49947318-3be16200-fef1-11e8-9d96-6746f73c195d.png)
This works without the data option, also without the ajax option, but both together wont.
Here are a few screenshots with what happens:
after loading the page:
![image](https://user-images.githubusercontent.com/1181094/49947424-84008480-fef1-11e8-868d-fea5cf4a61db.png)
opening the dropdown (you can see the disabled items that are actually selected)
![image](https://user-images.githubusercontent.com/1181094/49947490-ab575180-fef1-11e8-91d1-de2c9010edad.png)
After a click somewhere in the pulldown:
![image](https://user-images.githubusercontent.com/1181094/49947601-f1acb080-fef1-11e8-945c-ede361ea0e85.png)
The selected items finally appear, but still not with the innerHTML form the data set.
When I scroll down, below the disabled options (only disabled, because already selected) the same options (functionally disabled, but visually enabled) show up a second time.
Searching and majax request work. If I add a new item, it is displayed correctly.
![image](https://user-images.githubusercontent.com/1181094/49947998-d1312600-fef2-11e8-8dcc-1838a7088fdf.png)

**Comment by brianvoe** [comment]
Thanks for submitting this. This is interesting. Let me do some tests to see if i can recreate this given you explanation of how your using it.

**Comment by Shoplifter** [comment]
Have you been able to reproduce these issues?

**Comment by brianvoe** [comment]
Im going to look into this tonight and see if i can replicate this.

**Comment by brianvoe** [comment]
So i was able to replicate this and I think im going to stick with(unless i get a really good reason not to) not auto selected options that have selected: true in it. I couldnt think of a reason why someone would need to auto select values upon doing an ajax request.

Change my mind.

**Comment by Shoplifter** [comment]
@brianvoe 
That seems to be a misunderstanding: The values shall and are NOT auto selected upon the ajax request, but on initialization with the `data` option. But if the in addition to that an `ajax` option is set too (used later in the process upon searching for further selectable options), then this does not work.
Having both options set, the `ajax` options seems to interfere with the `data` option.

Please reopen.

What about this other [thing](https://github.com/brianvoe/slim-select/issues/89#issuecomment-451231996) (double submit of preselected values)? Shall I open another separate issue for that?

**Comment by brianvoe** [comment]
Ok the plot thickens on this. The tricky thing about the ajax functionality in general is maintaining selected data from data that doesnt exist in the actual dataset. It might be the case that i need to go back to the drawing board and rethink how this should work. 

Im open to suggestions and ideas. Thanks.

**Comment by stanolacko** [comment]
Very nice scenario for this is list of selected tags for article. 

Is it any update for this issue?

**Comment by stanolacko** [comment]
Anyway, quick solution to show selected items in multiple with ajax is to add 
`this.slim.values();` into condition `if (this.config.isAjax && selected) {` in `SlimSelect.prototype.setData = function (data) {`
It's working but not tested with every scenarious

**Comment by yellow1912** [comment]
I'm not sure if I have the same error, but for me it seems like if you use ajax, then at the same time initializing the options with `set` causes issues.

**Comment by yellow1912** [comment]
I would like to re-visit this issue and explain it in much more details:

I'm using slimselect with vuejs, so I created a component for slim. Lets say that I have a form to edit a blog post, the blog post as a list of categories (multiple) that I use slimselect input.

1. If the blog already has some selected categories
2. When the vue component is initialized, I need to use setData to initialize the options
3. If ajax is also enabled, then the selected options will not be shown

**Comment by CptChaos** [comment]
I am having the same issue, for a situation much like the one given above. :)
I am building a custom CMS-like system where I want the editors to be able to edit relationships, like movies and TV shows. As there are a lot of them, I use an AJAX call to search for items, but as it's the edit page, I also would like to load in the current related items prior adding items in with the AJAX call.

**Comment by brianvoe** [comment]
New version of slim select has been released. If this is still an issue let me know and ill try to take care of it.
