### ISSUE TITLE
Multi selects displaying count of selection instead of tags

### ISSUE THREAD

**Issue by DuffautM** [brianvoe/slim-select#92]
Hi @brianvoe  

First of all thank you for that Js solution, it is really useful. 

I was wondering if it was possible when using a multi selects to display the number of selected options instead of displaying them all at the top of the dropdown like in the following.

![dropdown](https://user-images.githubusercontent.com/19566148/50890711-feda9380-13fa-11e9-96c5-16ba632757a0.PNG)

Thank you.

**Comment by brianvoe** [comment]
I actually really like this behavior and it would be a pretty simple thing to add. Im a little back up on my pr/issues list but ill be sure to get this in.

Thanks

**Comment by brianvoe** [comment]
Im also open to pr if you want to take a swing at this.

**Comment by brianvoe** [comment]
Tried going through some real implementations and a handful of things would have to change, one being the need to have a deselect of all if clicking on the primary x in the main bar but also having deselect icons in the individual options list to remove single ones.

Im not against this but if you would like this in or if anyone else needed this feature I would probably need a pr for this. Just cause Im not getting a lot of need for this to put time into. Im up for discussion on this and ill leave this open but i just wanted to let you know where im at with this at this moment.

**Comment by evromalarkey** [comment]
This kind of relates to https://github.com/brianvoe/slim-select/issues/127, I think adding deselect icons in the the dropdown to each option is not so necessary. Don't know how hard it would be, but if it would be possible to deselect the option on the same click event as selecting it, that would work. And there is already a `ss-option-selected` class that could be styled to distinguish the selected options.

**Comment by brianvoe** [comment]
Once again im open to prs.

If i was to tackle this, first add the option, get it set in the config. In the slim.ts file where i build the options add a div that would show a X button or something along those lines. Add if statements looking at the config settings for whether or not to allow the option to be clicked on again that would remove it from the data set.

For the placeholder i would at the point in which the tags are added look at the config for the option and if set add a single tag with the number of selected items, and not have a deselect value and have top dropdown options do the deselecting.

**Comment by lochehong** [comment]
Whats a pr?

**Comment by brianvoe** [comment]
pull request

**Comment by evromalarkey** [comment]
This could be also achieved manually with `beforeOnChange` event to count the selected options and `set` method to deselect all values on click event. And if #135 will be merged, you can also deselect each value in dropdown.

example with jquery
```
let select = new SlimSelect({
    select: "#my-select",
    closeOnSelect: false,
    beforeOnChange: (values) => {
        let el = $(select.slim.container).find(".ss-multi-selected");
        let selected = values.length;

        if (!el.find(`.ss-values-selected`).length) {
            el.prepend(`<div class="ss-values-selected"><span class="ss-value-text">${selected} Selected</span><span class="ss-value-delete">x</span></div>`)
            el.find(`.ss-values-selected`).on("click", function(e){
                e.preventDefault();
                e.stopPropagation();
                el.find(`.ss-values-selected`).remove();
                select.set([]);
            });
        } else {
            el.find(`.ss-values-selected`).find(".ss-value-text").text(`${selected} Selected`)
        }
    }
});
```

**Comment by LuisFlores0705** [comment]
Hello, I was wondering if there is any way to be able to select the same option several times, for example .. select two or more times the option with a value of 1

**Comment by MichaelEC** [comment]
Any news on this being a possibility? I love the dropdown although becomes a bit of a mess when you can select 10+ unfortunately.

**Comment by brianvoe** [comment]
New version of slim select has been released. If this is still an issue let me know and ill try to take care of it.
