### ISSUE TITLE
Feature Request: Inherit classlist from options

### ISSUE THREAD

**Issue by numb92** [brianvoe/slim-select#93]
Is it possible to have the slimselect div "options" inherit the classlist from each <option> element? In my case the option of a select can be in three different states which are distinguished by color.

**Comment by brianvoe** [comment]
can you send screen shots of what you would like to accomplish?

**Comment by numb92** [comment]
Sorry, accidentally closed the issue

**Comment by brianvoe** [comment]
Thanks for pointing this out. I dont currently have a class inheritance on the option at the moment. But that would be an easy thing to add and a great addition. Let me put it on the list of things to add. Do you have any rush on this to get it in?

**Comment by numb92** [comment]
Sounds great. I need it during the coming weeks, but I guess I can see if i can figure it out and make a pull request.

**Comment by brianvoe** [comment]
ok sounds good. ill let you know if i start working on it.

**Comment by brianvoe** [comment]
This has been integrated and will be in the next release
