### ISSUE TITLE
Feature Request: Make disabled options differ from selected options

### ISSUE THREAD

**Issue by Shoplifter** [brianvoe/slim-select#94]
Currently disabled (by default) options look the same as the selected option(s) in the pulldown.
There is no way to make them look differently via css, because they have the same class `ss-option ss-disabled.` Maybe set class to `ss-option ss-selected` instead and have the same style properties for `ss-disabled` and `ss-selected` in your css to avoid BCs, but then one could customize the appearance of selected options.

**Comment by brianvoe** [comment]
The reason they look alike it because a select option is disabled due to not being able to click on it.
