### ISSUE TITLE
Slim select does not work in IE11

### ISSUE THREAD

**Issue by marioloncarek** [brianvoe/slim-select#98]
Hello, 

I could not get this plugin to work on ie11, i had the latest version and i got this error: 

`unable to get property 'split' of undefined or null reference` 

In hours spent trying to sort that i just opened your demo site in ie11 (http://slimselectjs.com/) and saw that you have the same error on your demo site in IE11:

`Unable to get property 'split' of undefined or null reference` 

And selects look like default ie selects.

Then i downgraded slimselect firstly to version 1.11.1, and then to 1.16.0 for test, and both versions just display default select from IE and slimselect is not working. But no 'split' error in this versions. 

Could you help?

**Comment by brianvoe** [comment]
ya I can help. how are you testing on ie11?

**Comment by marioloncarek** [comment]
PC + browserstack

**Comment by brianvoe** [comment]
Thanks for catching this! Looks like ie 11 didnt like getting values from classList. I made updates to fix this v1.18.10
